Component:
- changed-files:
  - any-glob-to-any-file: ['packages/component/src/**']

Examples:
- changed-files:
  - any-glob-to-any-file: ['examples/**']

Query:
- changed-files:
  - any-glob-to-any-file: ['packages/query/src/**']

Reactivity:
- changed-files:
  - any-glob-to-any-file: ['packages/reactivity/src/**']

Templating:
- changed-files:
  - any-glob-to-any-file: ['packages/templating/src/**']

Utils:
- changed-files:
  - any-glob-to-any-file: ['packages/utils/src/**']

Tests:
- changed-files:
  - any-glob-to-any-file: ['packages/**/test/**', 'tests/**']

UI Components:
- changed-files:
  - any-glob-to-any-file: ['src/**']

CI:
- changed-files:
  - any-glob-to-any-file: [.github/**]

Tooling:
- changed-files:
  - any-glob-to-any-file: ['package.json', '\.*', '.prettierrc.json']

Docs:
- changed-files:
  - any-glob-to-any-file: ['README.md', ['**/*.md']]
