// package is package.json
export const getBanner = (packageFile) =>
  `/**
 * ${packageFile.name} v${packageFile.version}
 * ${packageFile.description || ''}
 *
 * @license ${packageFile.license || 'MIT'}
 * @copyright (c) ${new Date().getFullYear()} ${packageFile.author || ''}
 * @homepage ${packageFile.homepage || ''}
 *
 * This source code is licensed under the ${packageFile.license || 'MIT'} license found in the
 * LICENSE file in the root directory of this source tree.
 */`;

// This is used for files build internally to concatenate css (see build-ui-deps.js)
export const INTERNAL_CSS_BANNER = `/**
  ---DO NOT EDIT THIS FILE DIRECTLY---
  This CSS file was concatenated from files listed in the css/ folder as part of a build process
  This is to allow for js import with @import links which will not be followed
**/
`;

export const TARGET_BROWSERS = ['chrome130', 'edge130', 'firefox130', 'safari17', 'ios17'];

export const JS_BUILD_CONFIG = {
  // target browser by default for dist
  target: TARGET_BROWSERS,

  platform: 'browser',

  // source is in ESM
  format: 'esm',

  // build tools should log
  logLevel: 'warning',

  // needed to load css and inline for web components
  loader: {
    '.ts': 'ts',
    '.html': 'text',
    '.css': 'text',
    '.wasm': 'file',
    '.png': 'file',
    '.svg': 'file',
    '.jpg': 'file',
    '.jpeg': 'file',
    '.gif': 'file',
  },
};

export const CSS_BUILD_CONFIG = {
  // target browser by default for dist
  target: TARGET_BROWSERS,

  // build tools should log
  platform: 'browser',

  // source is in ESM
  format: 'esm',

  // build tools should log
  logLevel: 'warning',

  // loader settings for css
  loader: {
    '.css': 'css',
    '.png': 'file',
    '.svg': 'dataurl',
    '.jpg': 'file',
    '.jpeg': 'file',
    '.gif': 'file',
  },
};

/* Used when generating CDNized copy (note these are identical to defaults) */
export const CDN_CONFIG = {
  cdnRoot: 'https://cdn.jsdelivr.net/npm',
  directReplacements: {},
  cacheDir: '.cache',
  logging: 'silent',
};
