import { existsSync, readFileSync } from 'fs';
import { join, resolve } from 'path';

// package is package.json
export const getBanner = (packageFile) =>
  `/**
 * ${packageFile.name} v${packageFile.version}
 * ${packageFile.description || ''}
 *
 * @license ${packageFile.license || 'MIT'}
 * @copyright (c) ${new Date().getFullYear()} ${packageFile.author || ''}
 * @homepage ${packageFile.homepage || ''}
 *
 * This source code is licensed under the ${packageFile.license || 'MIT'} license found in the
 * LICENSE file in the root directory of this source tree.
 */`;

// This is used for files build internally to concatenate css (see build-ui-deps.js)
export const INTERNAL_CSS_BANNER = `/**
  ---DO NOT EDIT THIS FILE DIRECTLY---
  This CSS file was concatenated from files listed in the css/ folder as part of a build process
  This is to allow for js import with @import links which will not be followed
**/
`;

export const TARGET_BROWSERS = ['chrome130', 'edge130', 'firefox130', 'safari17', 'ios17'];

export const JS_BUILD_CONFIG = {
  // target browser by default for dist
  target: TARGET_BROWSERS,

  platform: 'browser',

  // source is in ESM
  format: 'esm',

  // build tools should log
  logLevel: 'warning',

  // needed to load css and inline for web components
  loader: {
    '.ts': 'ts',
    '.html': 'text',
    '.css': 'text',
    '.wasm': 'file',
    '.png': 'file',
    '.svg': 'file',
    '.jpg': 'file',
    '.jpeg': 'file',
    '.gif': 'file',
  },
};

export const CSS_BUILD_CONFIG = {
  // target browser by default for dist
  target: TARGET_BROWSERS,

  // build tools should log
  platform: 'browser',

  // source is in ESM
  format: 'esm',

  // build tools should log
  logLevel: 'warning',

  // loader settings for css
  loader: {
    '.css': 'css',
    '.png': 'file',
    '.svg': 'dataurl',
    '.jpg': 'file',
    '.jpeg': 'file',
    '.gif': 'file',
  },
};

const SUI_SCOPE = '@semantic-ui/';

/* Resolve a package's CDN entrypoint from its local package.json */
function resolveEntrypointFromPackageJson(packageName) {
  // Walk up from cwd looking for node_modules containing the package
  let dir = process.cwd();
  while (dir !== resolve(dir, '..')) {
    const pkgPath = join(dir, 'node_modules', ...packageName.split('/'), 'package.json');
    if (existsSync(pkgPath)) {
      return readEntryFromPackageJson(pkgPath);
    }
    dir = resolve(dir, '..');
  }
  return null;
}

function readEntryFromPackageJson(pkgPath) {
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
    const mainExport = pkg.exports?.['.'];
    if (mainExport && typeof mainExport === 'object') {
      // Prefer cdn/jsdelivr/importmap export conditions for CDN format
      const entry = mainExport.cdn
        || mainExport.jsdelivr
        || mainExport.importmap
        || (typeof mainExport.browser === 'string' ? mainExport.browser : null)
        || (typeof mainExport.import === 'string' ? mainExport.import : null)
        || (typeof mainExport.default === 'string' ? mainExport.default : null);
      if (entry) {
        return entry.replace(/^\.\//, '');
      }
    }
    // Fall back to top-level fields
    const entry = pkg.cdn || pkg.jsdelivr || pkg.browser || pkg.module || pkg.main;
    if (entry) {
      return (typeof entry === 'string') ? entry.replace(/^\.\//, '') : null;
    }
  }
  catch { /* fall through */ }
  return null;
}

/* CDN config for cdn.semantic-ui.com */
export const CDN_CONFIG = {
  cdnRoot: process.env.CDN_ROOT || 'https://cdn.semantic-ui.com',
  cacheDir: '.cache',
  logging: 'silent',
  directReplacements: {},

  // SUI packages use bare URL — Worker serves the entry point
  // Third-party resolves from local package.json exports
  resolveEntrypoint(packageName) {
    if (packageName.startsWith(SUI_SCOPE)) {
      return '';
    }
    return resolveEntrypointFromPackageJson(packageName);
  },

  // SUI packages drop the scope, third-party gets /vendor/ prefix
  resolvePackagePath(packageName) {
    if (packageName.startsWith(SUI_SCOPE)) {
      return packageName.slice(SUI_SCOPE.length);
    }
    return `vendor/${packageName}`;
  },
};
