export default {
  uiType: 'element',
  name: 'Table',
  description: 'A table displays a collections of data grouped into rows',
  tagName: 'ui-table',
  exportName: 'Table',
  bundle: ['standard', 'layout'],
  content: [],
  types: [],
  states: [],
  variations: [],
  settings: [],
  events: [],
  supportsPlural: false,
  examples: {
    defaultAttributes: {},
    defaultContent: '',
    defaultPluralContent: '',
  },
};
