import { Template } from '@semantic-ui/templating';
import { beforeEach, describe, expect, it } from 'vitest';
import { defineComponent } from '../../src/index.js';

/*******************************
      Attribute Alias Resolution
*******************************/

/*
  adjustPropertyFromAttribute supports three dialects:
    verbose:  <ui-icon icon="chevron-down">
    concise:  <ui-icon chevron-down>
    classic:  <ui-icon class="chevron-down">

  Within the verbose dialect, values are fuzzed:
    - spaces become dashes ("chevron down" → "chevron-down")
    - dash segments can be reversed ("down-chevron" → "chevron-down")
    - both combined ("down chevron" → "chevron-down")

  Concise dialect requires exact matches in optionAttributes,
  including compound aliases ("chevron-down-icon").
*/

let tagCounter = 0;
function uniqueTag() {
  return `test-alias-${++tagCounter}`;
}

// Minimal spec that mirrors the icon component's structure:
// - "icon" attribute with allowed values including "chevron-down"
// - "link" exists in both icon values and as a boolean variation (causes collision)
// - collision triggers compound alias generation for all icon values
function createIconLikeSpec() {
  return {
    attributes: ['icon', 'link', 'size'],
    properties: [],
    optionAttributes: {
      // bare values
      'chevron-down': 'icon',
      'chevron-up': 'icon',
      'arrow-right': 'icon',
      'home': 'icon',
      'link': 'icon',
      // compound aliases (generated by buildOptionAttributes when "link" collides)
      'chevron-down-icon': 'icon',
      'chevron-up-icon': 'icon',
      'arrow-right-icon': 'icon',
      'home-icon': 'icon',
      'link-icon': 'icon',
      // size values
      'small': 'size',
      'large': 'size',
    },
    propertyTypes: {
      icon: String,
      link: Boolean,
      size: String,
    },
    allowedValues: {
      icon: ['chevron-down', 'chevron-up', 'arrow-right', 'home', 'link'],
      size: ['small', 'large'],
    },
    attributeClasses: [],
  };
}

describe('Attribute Alias Resolution', () => {
  beforeEach(() => {
    document.body.innerHTML = '';
  });

  /*******************************
     Verbose Dialect (icon="value")
  *******************************/

  describe('verbose dialect', () => {
    it('should resolve exact attribute value', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('icon', 'chevron-down');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');
    });

    it('should resolve spaces to dashes in attribute value', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('icon', 'chevron down');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');
    });

    it('should resolve reversed dash segments in attribute value', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('icon', 'down-chevron');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');
    });

    it('should resolve reversed segments with spaces', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('icon', 'down chevron');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');
    });
  });

  /*******************************
     Concise Dialect (<el value>)
  *******************************/

  describe('concise dialect', () => {
    it('should resolve bare attribute via optionAttributes lookup', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('chevron-down', '');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');
    });

    it('should resolve compound alias and extract canonical value', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('chevron-down-icon', '');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');
    });
  });

  /*******************************
     Classic Dialect (class="value")
  *******************************/

  describe('classic dialect', () => {
    it('should resolve class value via recursive attribute lookup', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('class', 'chevron-down');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');
    });

    it('should diff class changes and apply adds/removes separately', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon} {size}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('class', 'chevron-down small');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');
      expect(el.settings.size).toBe('small');

      // change size class, keep icon
      el.setAttribute('class', 'chevron-down large');
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');
      expect(el.settings.size).toBe('large');
    });
  });

  /*******************************
     Boolean Attributes
  *******************************/

  describe('boolean attributes', () => {
    function createButtonLikeSpec() {
      return {
        attributes: ['emphasis', 'disabled', 'active'],
        properties: [],
        optionAttributes: {
          'primary': 'emphasis',
          'secondary': 'emphasis',
          'disabled': 'disabled',
        },
        propertyTypes: {
          emphasis: String,
          disabled: Boolean,
          active: Boolean,
        },
        allowedValues: {
          emphasis: ['primary', 'secondary'],
          disabled: ['disabled'],
        },
        attributeClasses: ['disabled'],
      };
    }

    it('should treat empty boolean attribute as true', async () => {
      const tag = uniqueTag();
      const componentSpec = createButtonLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<button></button>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('disabled', '');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.disabled).toBe(true);
    });

    it('should clear boolean property on attribute removal', async () => {
      const tag = uniqueTag();
      const componentSpec = createButtonLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<button></button>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('disabled', '');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.disabled).toBe(true);

      el.removeAttribute('disabled');
      await el.updateComplete;

      expect(el.disabled).toBe(null);
    });

    it('should treat identity boolean from concise dialect as true', async () => {
      const tag = uniqueTag();
      const componentSpec = createButtonLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<button></button>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('active', '');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.active).toBe(true);
    });

    it('should convert falsy boolean strings to false', async () => {
      const tag = uniqueTag();
      const componentSpec = createButtonLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<button></button>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('active', '');
      document.body.appendChild(el);
      await el.updateComplete;
      expect(el.active).toBe(true);

      // Lit's custom Boolean fromAttribute converts "false" string → false
      el.setAttribute('active', 'false');
      await el.updateComplete;
      expect(el.active).toBe(false);
    });
  });

  /*******************************
     Converters
  *******************************/

  describe('converters', () => {
    it('should apply Boolean fromAttribute converter on kebab alias', async () => {
      const tag = uniqueTag();
      defineComponent({
        tagName: tag,
        template: '<div></div>',
        defaultSettings: {
          useAccordion: false,
        },
      });

      const el = document.createElement(tag);
      el.setAttribute('use-accordion', 'true');
      document.body.appendChild(el);
      await el.updateComplete;

      // fromAttribute converts "true" string → true boolean
      expect(el.settings.useAccordion).toBe(true);
    });

    it('should JSON.parse numeric string in setSetting fallback', async () => {
      const tag = uniqueTag();
      defineComponent({
        tagName: tag,
        template: '<div></div>',
        defaultSettings: {
          maxItems: 5,
        },
      });

      const el = document.createElement(tag);
      el.setAttribute('max-items', '10');
      document.body.appendChild(el);
      await el.updateComplete;

      // setSetting falls back to JSON.parse, "10" → 10
      expect(el.settings.maxItems).toBe(10);
    });

    it('should JSON.parse array string in setSetting fallback', async () => {
      const tag = uniqueTag();
      defineComponent({
        tagName: tag,
        template: '<div></div>',
        defaultSettings: {
          items: [],
        },
      });

      const el = document.createElement(tag);
      el.setAttribute('items', '["a","b"]');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.items).toEqual(['a', 'b']);
    });

    it('should leave unparseable strings as-is', async () => {
      const tag = uniqueTag();
      defineComponent({
        tagName: tag,
        template: '<div></div>',
        defaultSettings: {
          label: '',
        },
      });

      const el = document.createElement(tag);
      el.setAttribute('label', 'hello world');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.label).toBe('hello world');
    });
  });

  /*******************************
     Attribute Removal
  *******************************/

  describe('attribute removal', () => {
    it('should clear concise attribute only when value matches', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('chevron-down', '');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');

      el.removeAttribute('chevron-down');
      await el.updateComplete;

      expect(el.icon).toBe(null);
    });

    it('should clear verbose attribute on removal', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('icon', 'chevron-down');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');

      el.removeAttribute('icon');
      await el.updateComplete;

      expect(el.icon).toBe(null);
    });
  });

  /*******************************
     Settings Proxy Reactivity
  *******************************/

  describe('settings proxy', () => {
    it('should propagate attribute change to settings proxy', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{icon}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('icon', 'chevron-down');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-down');

      // change attribute, settings proxy should reflect
      el.setAttribute('icon', 'chevron-up');
      await el.updateComplete;

      expect(el.settings.icon).toBe('chevron-up');
    });

    it('should propagate concise attribute to settings proxy', async () => {
      const tag = uniqueTag();
      const componentSpec = createIconLikeSpec();
      defineComponent({
        tagName: tag,
        template: '<i class="{size}"></i>',
        componentSpec,
      });

      const el = document.createElement(tag);
      el.setAttribute('small', '');
      document.body.appendChild(el);
      await el.updateComplete;

      expect(el.settings.size).toBe('small');
    });
  });

  /*******************************
     Template as Setting
  *******************************/

  describe('template as setting', () => {
    async function waitForUpdate(el) {
      await el.updateComplete;
      await new Promise(r => setTimeout(r, 0));
      await el.updateComplete;
    }

    it('should register Template instance as property-only (no attribute)', async () => {
      const tag = uniqueTag();
      const Comp = defineComponent({
        tagName: tag,
        template: '<div></div>',
        defaultSettings: {
          rowTemplate: new Template(),
        },
      });

      // Template is a class instance — must be attribute: false
      expect(Comp.properties.rowTemplate.attribute).toBe(false);
    });

    it('should reactively update verbose data=expression when setting changes', async () => {
      const child = defineComponent({
        template: '<span class="child">{label}</span>',
      });

      const tag = uniqueTag();
      defineComponent({
        tagName: tag,
        template: "{> template name='child' data=currentRow}",
        subTemplates: { child },
        createComponent: ({ signal }) => {
          const currentRow = signal({ label: 'initial' });
          return {
            currentRow: () => currentRow.get(),
            setRow: (row) => currentRow.set(row),
          };
        },
      });

      const el = document.createElement(tag);
      document.body.appendChild(el);
      await waitForUpdate(el);

      expect(el.shadowRoot.querySelector('.child').textContent).toBe('initial');

      // update the data expression — should propagate reactively
      el.component.setRow({ label: 'updated' });
      await waitForUpdate(el);

      expect(el.shadowRoot.querySelector('.child').textContent).toBe('updated');
    });
  });
});
