// Auto-generated — do not edit
export const iconNames = [
  'arrow-down',
  'arrow-left',
  'arrow-left-right',
  'arrow-right',
  'arrow-up',
  'arrow-up-down',
  'chevron-down',
  'chevron-first',
  'chevron-last',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevrons-down-up',
  'chevrons-left-right',
  'chevrons-up-down',
  'compass',
  'corner-down-left',
  'corner-down-right',
  'crosshair',
  'external-link',
  'house',
  'layout-panel-left',
  'layout-panel-top',
  'menu',
  'mouse-pointer',
  'square-arrow-out-up-right',
  'archive',
  'archive-restore',
  'archive-x',
  'arrow-down-a-z',
  'arrow-up-a-z',
  'bookmark',
  'bookmark-check',
  'bookmark-plus',
  'circle-ellipsis',
  'circle-minus',
  'circle-plus',
  'circle-x',
  'clipboard',
  'clipboard-paste',
  'cloud-download',
  'cloud-upload',
  'copy',
  'copy-check',
  'delete',
  'download',
  'ellipsis',
  'ellipsis-vertical',
  'expand',
  'eye',
  'eye-off',
  'grip-horizontal',
  'grip-vertical',
  'hand',
  'heart',
  'heart-off',
  'link',
  'list-checks',
  'maximize',
  'merge',
  'minimize',
  'minus',
  'mouse-pointer-click',
  'move',
  'paperclip',
  'pencil',
  'pin',
  'pin-off',
  'plus',
  'redo',
  'refresh-ccw',
  'replace',
  'rocket',
  'rotate-ccw',
  'rotate-cw',
  'save',
  'scan',
  'scissors',
  'search',
  'share',
  'split',
  'thumbs-down',
  'thumbs-up',
  'trash',
  'undo',
  'unlink',
  'upload',
  'vote',
  'x',
  'zoom-in',
  'zoom-out',
  'badge-alert',
  'badge-check',
  'badge-info',
  'ban',
  'check',
  'check-check',
  'circle-alert',
  'circle-check',
  'circle-dashed',
  'circle-question-mark',
  'construction',
  'flag',
  'flame',
  'frown',
  'info',
  'life-buoy',
  'loader',
  'loader-circle',
  'meh',
  'server-crash',
  'triangle-alert',
  'zap',
  'circle-user',
  'contact',
  'id-card',
  'user',
  'user-check',
  'user-cog',
  'user-minus',
  'user-plus',
  'user-search',
  'user-x',
  'users',
  'circle-dot',
  'rectangle-ellipsis',
  'square-check',
  'text-cursor-input',
  'toggle-left',
  'toggle-right',
  'activity',
  'chart-area',
  'chart-bar',
  'chart-bar-stacked',
  'chart-candlestick',
  'chart-gantt',
  'chart-line',
  'chart-network',
  'chart-pie',
  'chart-scatter',
  'clipboard-list',
  'funnel',
  'gauge',
  'grid-2x2',
  'grid-3x3',
  'layout-dashboard',
  'layout-grid',
  'layout-list',
  'list-filter',
  'list-tree',
  'qr-code',
  'radar',
  'sigma',
  'table',
  'table-cells-merge',
  'table-cells-split',
  'trending-down',
  'trending-up',
  'file',
  'file-archive',
  'file-check',
  'file-code',
  'file-image',
  'file-lock',
  'file-plus',
  'file-search',
  'file-spreadsheet',
  'file-text',
  'file-x',
  'files',
  'folder',
  'folder-open',
  'folder-plus',
  'folder-tree',
  'newspaper',
  'notebook',
  'presentation',
  'scroll-text',
  'sticky-note',
  'audio-lines',
  'camera',
  'camera-off',
  'captions',
  'film',
  'gallery-horizontal',
  'image',
  'image-off',
  'image-plus',
  'images',
  'mic',
  'mic-off',
  'music',
  'podcast',
  'video',
  'video-off',
  'circle-pause',
  'circle-play',
  'circle-stop',
  'fast-forward',
  'pause',
  'picture-in-picture',
  'play',
  'repeat',
  'rewind',
  'shuffle',
  'skip-back',
  'skip-forward',
  'volume-2',
  'volume-low',
  'volume-x',
  'a-arrow-down',
  'a-arrow-up',
  'a-large-small',
  'asterisk',
  'bold',
  'hash',
  'heading',
  'heading-1',
  'heading-2',
  'heading-3',
  'italic',
  'list',
  'list-indent-decrease',
  'list-indent-increase',
  'list-ordered',
  'quote',
  'remove-formatting',
  'spell-check',
  'strikethrough',
  'subscript',
  'superscript',
  'table-of-contents',
  'text-align-center',
  'text-align-end',
  'text-align-justify',
  'text-align-start',
  'text-quote',
  'text-select',
  'type',
  'underline',
  'align-center-horizontal',
  'align-center-vertical',
  'align-end-horizontal',
  'align-end-vertical',
  'align-start-horizontal',
  'align-start-vertical',
  'bring-to-front',
  'columns-2',
  'columns-3',
  'crop',
  'droplet',
  'eraser',
  'flip-horizontal',
  'flip-vertical',
  'highlighter',
  'layers',
  'paint-bucket',
  'paintbrush',
  'palette',
  'pipette',
  'ruler',
  'send-to-back',
  'shapes',
  'signature',
  'at-sign',
  'bell',
  'bell-dot',
  'bell-off',
  'bell-ring',
  'forward',
  'inbox',
  'mail',
  'mail-open',
  'mail-plus',
  'megaphone',
  'message-circle',
  'message-circle-more',
  'message-circle-plus',
  'message-square',
  'message-square-dot',
  'message-square-reply',
  'messages-square',
  'phone',
  'phone-call',
  'phone-missed',
  'phone-off',
  'reply',
  'reply-all',
  'screen-share',
  'screen-share-off',
  'send',
  'smile',
  'voicemail',
  'barcode',
  'box',
  'credit-card',
  'gift',
  'package',
  'package-open',
  'receipt',
  'shopping-bag',
  'shopping-cart',
  'store',
  'tag',
  'tags',
  'ticket',
  'truck',
  'alarm-clock',
  'calendar',
  'calendar-check',
  'calendar-clock',
  'calendar-days',
  'calendar-plus',
  'calendar-range',
  'calendar-x',
  'clock',
  'history',
  'hourglass',
  'timer',
  'cookie',
  'fingerprint',
  'globe-lock',
  'key-round',
  'lock',
  'lock-open',
  'log-in',
  'log-out',
  'scan-face',
  'shield',
  'shield-alert',
  'shield-check',
  'shield-off',
  'shield-x',
  'vault',
  'venetian-mask',
  'languages',
  'moon',
  'settings',
  'sliders-horizontal',
  'sun-moon',
  'wrench',
  'building',
  'kanban',
  'milestone',
  'briefcase',
  'banknote',
  'circle-dollar-sign',
  'coins',
  'dollar-sign',
  'euro',
  'landmark',
  'percent',
  'scale',
  'wallet',
  'car',
  'hospital',
  'locate',
  'locate-fixed',
  'map',
  'map-pin',
  'map-pin-off',
  'map-pin-plus',
  'plane',
  'route',
  'waypoints',
  'app-window',
  'command',
  'panel-bottom',
  'panel-bottom-close',
  'panel-bottom-open',
  'panel-left',
  'panel-left-close',
  'panel-left-open',
  'panel-right',
  'panel-right-close',
  'panel-right-open',
  'power',
  'separator-horizontal',
  'battery',
  'battery-charging',
  'battery-full',
  'battery-low',
  'battery-medium',
  'battery-warning',
  'computer',
  'cpu',
  'hard-drive',
  'headphones',
  'keyboard',
  'laptop',
  'monitor',
  'monitor-smartphone',
  'mouse',
  'printer',
  'server',
  'smartphone',
  'tablet',
  'tv',
  'usb',
  'watch',
  'webcam',
  'bluetooth',
  'bluetooth-off',
  'cast',
  'cloud-off',
  'cloud-sync',
  'globe',
  'network',
  'plug',
  'radio-tower',
  'router',
  'rss',
  'signal',
  'unplug',
  'wifi',
  'wifi-high',
  'wifi-low',
  'wifi-off',
  'wifi-zero',
  'braces',
  'bug',
  'code',
  'component',
  'container',
  'database',
  'database-backup',
  'diff',
  'git-branch',
  'git-commit-horizontal',
  'git-compare',
  'git-fork',
  'git-graph',
  'git-merge',
  'git-pull-request',
  'git-pull-request-closed',
  'git-pull-request-draft',
  'logs',
  'puzzle',
  'regex',
  'search-code',
  'terminal',
  'variable',
  'webhook',
  'workflow',
  'github',
  'award',
  'crown',
  'dices',
  'party-popper',
  'star',
  'star-half',
  'trophy',
  'bot',
  'brain',
  'sparkles',
  'wand-sparkles',
  'book',
  'book-open',
  'flask-conical',
  'graduation-cap',
  'library',
  'cloud',
  'cloud-lightning',
  'cloud-rain',
  'snowflake',
  'sun',
  'thermometer',
  'wind',
  'accessibility',
  'calculator',
  'circle',
  'coffee',
  'copyright',
  'cross',
  'hexagon',
  'infinity',
  'leaf',
  'lightbulb',
  'recycle',
  'square',
  'target',
  'triangle',
];

export const iconAliases = {
  'down': 'arrow-down',
  'arrow-downward': 'arrow-down',
  'move-down': 'arrow-down',
  'left': 'arrow-left',
  'back': 'arrow-left',
  'arrow-back': 'arrow-left',
  'previous': 'arrow-left',
  'horizontal': 'arrow-left-right',
  'resize-horizontal': 'arrow-left-right',
  'swap-horizontal': 'arrow-left-right',
  'swap-horiz': 'arrow-left-right',
  'arrows-horizontal': 'arrow-left-right',
  'bidirectional': 'arrow-left-right',
  'right': 'arrow-right',
  'arrow-forward': 'arrow-right',
  'next': 'arrow-right',
  'go-right': 'arrow-right',
  'up': 'arrow-up',
  'arrow-upward': 'arrow-up',
  'move-up': 'arrow-up',
  'vertical': 'arrow-up-down',
  'resize-vertical': 'arrow-up-down',
  'swap-vertical': 'arrow-up-down',
  'swap-vert': 'arrow-up-down',
  'arrows-vertical': 'arrow-up-down',
  'caret-down': 'chevron-down',
  'dropdown': 'chevron-down',
  'arrow-drop-down': 'chevron-down',
  'select-arrow': 'chevron-down',
  'collapse-down': 'chevron-down',
  'angle-down': 'chevron-down',
  'skip-to-start': 'chevron-first',
  'first-page': 'chevron-first',
  'page-first': 'chevron-first',
  'go-to-first': 'chevron-first',
  'chevron-double-left': 'chevron-first',
  'step-first': 'chevron-first',
  'skip-to-end': 'chevron-last',
  'last-page': 'chevron-last',
  'page-last': 'chevron-last',
  'go-to-last': 'chevron-last',
  'chevron-double-right': 'chevron-last',
  'step-last': 'chevron-last',
  'caret-left': 'chevron-left',
  'collapse-left': 'chevron-left',
  'nav-left': 'chevron-left',
  'angle-left': 'chevron-left',
  'caret-right': 'chevron-right',
  'expand-right': 'chevron-right',
  'nav-right': 'chevron-right',
  'angle-right': 'chevron-right',
  'caret-up': 'chevron-up',
  'collapse': 'chevron-up',
  'collapse-up': 'chevron-up',
  'angle-up': 'chevron-up',
  'collapse-vertical': 'chevrons-down-up',
  'unfold-less': 'chevrons-down-up',
  'collapse-all': 'chevrons-down-up',
  'fold': 'chevrons-down-up',
  'expand-horizontal': 'chevrons-left-right',
  'unfold-horizontal': 'chevrons-left-right',
  'expand-width': 'chevrons-left-right',
  'expand-vertical': 'chevrons-up-down',
  'unfold-more': 'chevrons-up-down',
  'sort-indicator': 'chevrons-up-down',
  'selector': 'chevrons-up-down',
  'select': 'chevrons-up-down',
  'caret-up-down': 'chevrons-up-down',
  'unfold': 'chevrons-up-down',
  'explore': 'compass',
  'direction': 'compass',
  'navigate': 'compass',
  'discover': 'compass',
  'safari': 'compass',
  'return-key': 'corner-down-left',
  'enter': 'corner-down-left',
  'subdirectory-left': 'corner-down-left',
  'arrow-bend-down-left': 'corner-down-left',
  'carriage-return': 'corner-down-left',
  'subdirectory-right': 'corner-down-right',
  'arrow-bend-down-right': 'corner-down-right',
  'forward-down': 'corner-down-right',
  'target-location': 'crosshair',
  'aim': 'crosshair',
  'gps': 'crosshair',
  'location-searching': 'crosshair',
  'viewfinder': 'crosshair',
  'scope': 'crosshair',
  'open-in-new': 'external-link',
  'new-window': 'external-link',
  'new-tab': 'external-link',
  'launch': 'external-link',
  'arrow-square-out': 'external-link',
  'outbound': 'external-link',
  'home': 'house',
  'homepage': 'house',
  'main': 'house',
  'sidebar': 'layout-panel-left',
  'sidebar-left': 'layout-panel-left',
  'layout-sidebar': 'layout-panel-left',
  'view-sidebar': 'layout-panel-left',
  'side-panel': 'layout-panel-left',
  'navbar': 'layout-panel-top',
  'layout-navbar': 'layout-panel-top',
  'header-panel': 'layout-panel-top',
  'top-bar': 'layout-panel-top',
  'web-asset': 'layout-panel-top',
  'hamburger': 'menu',
  'hamburger-menu': 'menu',
  'bars-3': 'menu',
  'navigation-menu': 'menu',
  'nav-menu': 'menu',
  'cursor': 'mouse-pointer',
  'pointer': 'mouse-pointer',
  'arrow-cursor': 'mouse-pointer',
  'cursor-arrow': 'mouse-pointer',
  'arrow-selector': 'mouse-pointer',
  'open-external': 'square-arrow-out-up-right',
  'archive-box': 'archive',
  'file-away': 'archive',
  'put-away': 'archive',
  'unarchive': 'archive-restore',
  'restore': 'archive-restore',
  'archive-undo': 'archive-restore',
  'archive-remove': 'archive-x',
  'archive-delete': 'archive-x',
  'archive-off': 'archive-x',
  'sort-alpha-asc': 'arrow-down-a-z',
  'sort-ascending': 'arrow-down-a-z',
  'sort-alpha-down': 'arrow-down-a-z',
  'sort-az': 'arrow-down-a-z',
  'sort-alphabetical': 'arrow-down-a-z',
  'sort-alpha-desc': 'arrow-up-a-z',
  'sort-descending': 'arrow-up-a-z',
  'sort-alpha-up': 'arrow-up-a-z',
  'sort-za': 'arrow-up-a-z',
  'sort-alphabetical-reverse': 'arrow-up-a-z',
  'save-for-later': 'bookmark',
  'saved': 'bookmark',
  'flag-bookmark': 'bookmark',
  'reading-list': 'bookmark',
  'bookmark-saved': 'bookmark-check',
  'bookmark-done': 'bookmark-check',
  'bookmark-confirmed': 'bookmark-check',
  'bookmark-add': 'bookmark-plus',
  'add-bookmark': 'bookmark-plus',
  'bookmark-new': 'bookmark-plus',
  'more-circle': 'circle-ellipsis',
  'dots-circle': 'circle-ellipsis',
  'pending-actions': 'circle-ellipsis',
  'options-circle': 'circle-ellipsis',
  'remove-circle': 'circle-minus',
  'subtract-circle': 'circle-minus',
  'minus-circle': 'circle-minus',
  'add-circle': 'circle-plus',
  'create-circle': 'circle-plus',
  'plus-circle': 'circle-plus',
  'new-circle': 'circle-plus',
  'cancel': 'circle-x',
  'close-circle': 'circle-x',
  'dismiss': 'circle-x',
  'x-circle': 'circle-x',
  'paste-board': 'clipboard',
  'assignment': 'clipboard',
  'copy-board': 'clipboard',
  'paste': 'clipboard-paste',
  'content-paste': 'clipboard-paste',
  'paste-from-clipboard': 'clipboard-paste',
  'download-cloud': 'cloud-download',
  'cloud-save': 'cloud-download',
  'cloud-arrow-down': 'cloud-download',
  'upload-cloud': 'cloud-upload',
  'cloud-push': 'cloud-upload',
  'cloud-arrow-up': 'cloud-upload',
  'duplicate': 'copy',
  'clone': 'copy',
  'content-copy': 'copy',
  'copy-to-clipboard': 'copy',
  'copied': 'copy-check',
  'copy-success': 'copy-check',
  'clipboard-check': 'copy-check',
  'copy-confirmed': 'copy-check',
  'backspace': 'delete',
  'back-delete': 'delete',
  'erase-back': 'delete',
  'remove-character': 'delete',
  'download-file': 'download',
  'export': 'download',
  'arrow-down-tray': 'download',
  'more': 'ellipsis',
  'dots': 'ellipsis',
  'three-dots': 'ellipsis',
  'more-horizontal': 'ellipsis',
  'kebab-horizontal': 'ellipsis',
  'options': 'ellipsis',
  'more-vertical': 'ellipsis-vertical',
  'dots-vertical': 'ellipsis-vertical',
  'three-dots-vertical': 'ellipsis-vertical',
  'kebab-menu': 'ellipsis-vertical',
  'kebab': 'ellipsis-vertical',
  'options-vertical': 'ellipsis-vertical',
  'fullscreen': 'expand',
  'enlarge': 'expand',
  'arrows-out': 'expand',
  'open-in-full': 'expand',
  'grow': 'expand',
  'view': 'eye',
  'visible': 'eye',
  'show': 'eye',
  'visibility': 'eye',
  'preview': 'eye',
  'hidden': 'eye-off',
  'hide': 'eye-off',
  'invisible': 'eye-off',
  'visibility-off': 'eye-off',
  'eye-slash': 'eye-off',
  'conceal': 'eye-off',
  'drag-handle': 'grip-horizontal',
  'drag-horizontal': 'grip-horizontal',
  'dots-six': 'grip-horizontal',
  'handle-horizontal': 'grip-horizontal',
  'reorder': 'grip-horizontal',
  'drag-indicator': 'grip-vertical',
  'drag-vertical': 'grip-vertical',
  'dots-six-vertical': 'grip-vertical',
  'handle-vertical': 'grip-vertical',
  'stop': 'hand',
  'hand-stop': 'hand',
  'hand-raised': 'hand',
  'raise-hand': 'hand',
  'pan-tool': 'hand',
  'halt': 'hand',
  'like': 'heart',
  'love': 'heart',
  'favorite': 'heart',
  'favourite': 'heart',
  'unlike': 'heart-off',
  'heart-broken': 'heart-off',
  'unfavorite': 'heart-off',
  'dislike': 'heart-off',
  'heart-break': 'heart-off',
  'hyperlink': 'link',
  'url': 'link',
  'chain': 'link',
  'anchor': 'link',
  'list-check': 'list-checks',
  'completed-tasks': 'list-checks',
  'expand-full': 'maximize',
  'arrows-maximize': 'maximize',
  'combine': 'merge',
  'join': 'merge',
  'arrows-merge': 'merge',
  'converge': 'merge',
  'exit-fullscreen': 'minimize',
  'shrink': 'minimize',
  'collapse-full': 'minimize',
  'arrows-minimize': 'minimize',
  'arrows-in': 'minimize',
  'reduce': 'minimize',
  'subtract': 'minus',
  'remove': 'minus',
  'dash': 'minus',
  'cursor-click': 'mouse-pointer-click',
  'click': 'mouse-pointer-click',
  'tap': 'mouse-pointer-click',
  'pointer-click': 'mouse-pointer-click',
  'ads-click': 'mouse-pointer-click',
  'drag': 'move',
  'reposition': 'move',
  'arrows-move': 'move',
  'open-with': 'move',
  'arrows-out-cardinal': 'move',
  'rearrange': 'move',
  'attach': 'paperclip',
  'attachment': 'paperclip',
  'attach-file': 'paperclip',
  'paper-clip': 'paperclip',
  'clip': 'paperclip',
  'edit': 'pencil',
  'modify': 'pencil',
  'write': 'pencil',
  'pen': 'pencil',
  'push-pin': 'pin',
  'pinned': 'pin',
  'thumbtack': 'pin',
  'keep': 'pin',
  'tack': 'pin',
  'unpin': 'pin-off',
  'pinned-off': 'pin-off',
  'remove-pin': 'pin-off',
  'keep-off': 'pin-off',
  'add': 'plus',
  'create': 'plus',
  'new': 'plus',
  'insert': 'plus',
  'redo-action': 'redo',
  'arrow-clockwise': 'redo',
  'step-forward': 'redo',
  'refresh': 'refresh-ccw',
  'reload': 'refresh-ccw',
  'sync': 'refresh-ccw',
  'update': 'refresh-ccw',
  'retry': 'refresh-ccw',
  'find-replace': 'replace',
  'swap': 'replace',
  'substitute': 'replace',
  'search-replace': 'replace',
  'find-and-replace': 'replace',
  'deploy': 'rocket',
  'liftoff': 'rocket',
  'rocket-launch': 'rocket',
  'blast-off': 'rocket',
  'ship-it': 'rocket',
  'rotate-left': 'rotate-ccw',
  'rotate-counter-clockwise': 'rotate-ccw',
  'turn-left': 'rotate-ccw',
  'rotate-right': 'rotate-cw',
  'rotate-clockwise': 'rotate-cw',
  'turn-right': 'rotate-cw',
  'floppy-disk': 'save',
  'floppy': 'save',
  'persist': 'save',
  'save-file': 'save',
  'device-floppy': 'save',
  'crop-free': 'scan',
  'camera-scan': 'scan',
  'viewfinder-circle': 'scan',
  'cut': 'scissors',
  'content-cut': 'scissors',
  'snip': 'scissors',
  'clip-content': 'scissors',
  'find': 'search',
  'magnifying-glass': 'search',
  'lookup': 'search',
  'look-up': 'search',
  'share-link': 'share',
  'distribute': 'share',
  'spread': 'share',
  'share-network': 'share',
  'divide': 'split',
  'fork-vertical': 'split',
  'call-split': 'split',
  'downvote': 'thumbs-down',
  'thumb-down': 'thumbs-down',
  'reject': 'thumbs-down',
  'disapprove': 'thumbs-down',
  'upvote': 'thumbs-up',
  'thumb-up': 'thumbs-up',
  'approve': 'thumbs-up',
  'recommend': 'thumbs-up',
  'bin': 'trash',
  'garbage': 'trash',
  'discard': 'trash',
  'revert': 'undo',
  'undo-action': 'undo',
  'arrow-counter-clockwise': 'undo',
  'go-back': 'undo',
  'step-back': 'undo',
  'link-break': 'unlink',
  'remove-link': 'unlink',
  'disconnect-link': 'unlink',
  'link-off': 'unlink',
  'chain-break': 'unlink',
  'publish': 'upload',
  'export-file': 'upload',
  'arrow-up-tray': 'upload',
  'upload-file': 'upload',
  'ballot': 'vote',
  'poll': 'vote',
  'election': 'vote',
  'how-to-vote': 'vote',
  'cast-vote': 'vote',
  'close': 'x',
  'remove-mark': 'x',
  'x-mark': 'x',
  'magnify': 'zoom-in',
  'zoom-plus': 'zoom-in',
  'magnifying-glass-plus': 'zoom-in',
  'scale-up': 'zoom-in',
  'badge-warning': 'badge-alert',
  'seal-warning': 'badge-alert',
  'badge-exclamation': 'badge-alert',
  'verified-warning': 'badge-alert',
  'verified': 'badge-check',
  'certified': 'badge-check',
  'seal-check': 'badge-check',
  'badge-verified': 'badge-check',
  'rosette': 'badge-check',
  'badge-question': 'badge-info',
  'seal-info': 'badge-info',
  'badge-information': 'badge-info',
  'block': 'ban',
  'prohibit': 'ban',
  'forbidden': 'ban',
  'no-entry': 'ban',
  'restricted': 'ban',
  'no-symbol': 'ban',
  'done': 'check',
  'confirm': 'check',
  'checkmark': 'check',
  'tick': 'check',
  'complete': 'check',
  'yes': 'check',
  'ok': 'check',
  'double-check': 'check-check',
  'read-receipt': 'check-check',
  'done-all': 'check-check',
  'all-done': 'check-check',
  'verified-check': 'check-check',
  'error': 'circle-alert',
  'error-circle': 'circle-alert',
  'warning-circle': 'circle-alert',
  'alert-circle': 'circle-alert',
  'exclamation-circle': 'circle-alert',
  'circle-exclamation': 'circle-alert',
  'circle-warning': 'circle-alert',
  'success': 'circle-check',
  'check-circle': 'circle-check',
  'complete-circle': 'circle-check',
  'done-circle': 'circle-check',
  'approved': 'circle-check',
  'circle-success': 'circle-check',
  'pending': 'circle-dashed',
  'in-progress': 'circle-dashed',
  'loading-circle': 'circle-dashed',
  'incomplete': 'circle-dashed',
  'help': 'circle-question-mark',
  'help-circle': 'circle-question-mark',
  'faq': 'circle-question-mark',
  'question': 'circle-question-mark',
  'question-circle': 'circle-question-mark',
  'support': 'circle-question-mark',
  'under-construction': 'construction',
  'maintenance': 'construction',
  'roadblock': 'construction',
  'barricade': 'construction',
  'wip': 'construction',
  'report': 'flag',
  'flag-report': 'flag',
  'flagged': 'flag',
  'mark': 'flag',
  'banner': 'flag',
  'fire': 'flame',
  'hot': 'flame',
  'popular': 'flame',
  'burn': 'flame',
  'lit': 'flame',
  'sad': 'frown',
  'unhappy': 'frown',
  'dissatisfied': 'frown',
  'negative': 'frown',
  'sad-face': 'frown',
  'emoji-sad': 'frown',
  'information': 'info',
  'info-circle': 'info',
  'information-circle': 'info',
  'about': 'info',
  'details': 'info',
  'lifebuoy': 'life-buoy',
  'rescue': 'life-buoy',
  'life-ring': 'life-buoy',
  'spinner': 'loader',
  'loading': 'loader',
  'spinner-gap': 'loader',
  'autorenew': 'loader',
  'busy': 'loader',
  'spinner-circle': 'loader-circle',
  'progress-activity': 'loader-circle',
  'buffering': 'loader-circle',
  'neutral': 'meh',
  'indifferent': 'meh',
  'smiley-meh': 'meh',
  'sentiment-neutral': 'meh',
  'expressionless': 'meh',
  'server-error': 'server-crash',
  'server-down': 'server-crash',
  'server-off': 'server-crash',
  'server-failure': 'server-crash',
  'outage': 'server-crash',
  'warning': 'triangle-alert',
  'caution': 'triangle-alert',
  'alert-triangle': 'triangle-alert',
  'danger': 'triangle-alert',
  'exclamation-triangle': 'triangle-alert',
  'lightning': 'zap',
  'bolt': 'zap',
  'flash': 'zap',
  'electric': 'zap',
  'instant': 'zap',
  'avatar': 'circle-user',
  'user-circle': 'circle-user',
  'account-circle': 'circle-user',
  'profile': 'circle-user',
  'user-avatar': 'circle-user',
  'address-book': 'contact',
  'contact-card': 'contact',
  'vcard': 'contact',
  'person-details': 'contact',
  'identification': 'contact',
  'badge': 'id-card',
  'identity-card': 'id-card',
  'id': 'id-card',
  'name-badge': 'id-card',
  'credentials': 'id-card',
  'person': 'user',
  'account': 'user',
  'member': 'user',
  'user-verified': 'user-check',
  'user-approved': 'user-check',
  'person-check': 'user-check',
  'how-to-reg': 'user-check',
  'user-confirm': 'user-check',
  'user-settings': 'user-cog',
  'user-preferences': 'user-cog',
  'manage-accounts': 'user-cog',
  'user-gear': 'user-cog',
  'user-config': 'user-cog',
  'remove-user': 'user-minus',
  'unfriend': 'user-minus',
  'person-remove': 'user-minus',
  'user-remove': 'user-minus',
  'add-user': 'user-plus',
  'new-user': 'user-plus',
  'person-add': 'user-plus',
  'user-add': 'user-plus',
  'invite-user': 'user-plus',
  'find-user': 'user-search',
  'person-search': 'user-search',
  'lookup-user': 'user-search',
  'user-find': 'user-search',
  'block-user': 'user-x',
  'ban-user': 'user-x',
  'person-off': 'user-x',
  'user-block': 'user-x',
  'user-reject': 'user-x',
  'group': 'users',
  'team': 'users',
  'people': 'users',
  'members': 'users',
  'community': 'users',
  'radio-button': 'circle-dot',
  'radio': 'circle-dot',
  'record': 'circle-dot',
  'bullseye': 'circle-dot',
  'selected': 'circle-dot',
  'password-field': 'rectangle-ellipsis',
  'hidden-input': 'rectangle-ellipsis',
  'password-input': 'rectangle-ellipsis',
  'dots-input': 'rectangle-ellipsis',
  'checkbox': 'square-check',
  'checkbox-checked': 'square-check',
  'check-box': 'square-check',
  'check-square': 'square-check',
  'task-done': 'square-check',
  'text-input': 'text-cursor-input',
  'cursor-text': 'text-cursor-input',
  'input-cursor': 'text-cursor-input',
  'text-field': 'text-cursor-input',
  'toggle-off': 'toggle-left',
  'toggle-inactive': 'toggle-left',
  'toggle-on': 'toggle-right',
  'switch-on': 'toggle-right',
  'toggle-active': 'toggle-right',
  'pulse': 'activity',
  'heartbeat': 'activity',
  'heart-rate': 'activity',
  'vital-signs': 'activity',
  'monitoring': 'activity',
  'area-chart': 'chart-area',
  'graph-area': 'chart-area',
  'chart-area-line': 'chart-area',
  'bar-chart': 'chart-bar',
  'graph-bar': 'chart-bar',
  'bar-graph': 'chart-bar',
  'histogram': 'chart-bar',
  'analytics': 'chart-bar',
  'stacked-bar': 'chart-bar-stacked',
  'stacked-chart': 'chart-bar-stacked',
  'stacked-bar-chart': 'chart-bar-stacked',
  'candlestick': 'chart-candlestick',
  'stock-chart': 'chart-candlestick',
  'financial-chart': 'chart-candlestick',
  'ohlc': 'chart-candlestick',
  'gantt': 'chart-gantt',
  'timeline-chart': 'chart-gantt',
  'project-timeline': 'chart-gantt',
  'project-chart': 'chart-gantt',
  'line-chart': 'chart-line',
  'graph-line': 'chart-line',
  'line-graph': 'chart-line',
  'trend': 'chart-line',
  'show-chart': 'chart-line',
  'graph': 'chart-line',
  'network-graph': 'chart-network',
  'graph-network': 'chart-network',
  'topology': 'chart-network',
  'node-graph': 'chart-network',
  'relationship-graph': 'chart-network',
  'mind-map': 'chart-network',
  'pie-chart': 'chart-pie',
  'donut-chart': 'chart-pie',
  'graph-pie': 'chart-pie',
  'pie-graph': 'chart-pie',
  'scatter-plot': 'chart-scatter',
  'dot-plot': 'chart-scatter',
  'scatter-chart': 'chart-scatter',
  'data-points': 'chart-scatter',
  'task-list': 'clipboard-list',
  'checklist': 'clipboard-list',
  'todo-list': 'clipboard-list',
  'assignment-list': 'clipboard-list',
  'filter-list': 'funnel',
  'sort-funnel': 'funnel',
  'filter-alt': 'funnel',
  'sieve': 'funnel',
  'speedometer': 'gauge',
  'performance': 'gauge',
  'speed': 'gauge',
  'meter': 'gauge',
  'dashboard-gauge': 'gauge',
  'tachometer': 'gauge',
  'grid-four': 'grid-2x2',
  'grid-view': 'grid-2x2',
  'squares-2x2': 'grid-2x2',
  'grid-small': 'grid-2x2',
  'grid-nine': 'grid-3x3',
  'grid-large': 'grid-3x3',
  'dashboard': 'layout-dashboard',
  'widgets': 'layout-dashboard',
  'dashboard-layout': 'layout-dashboard',
  'rectangle-group': 'layout-dashboard',
  'apps': 'layout-grid',
  'grid-layout': 'layout-grid',
  'app-grid': 'layout-grid',
  'list-view': 'layout-list',
  'view-list': 'layout-list',
  'queue-list': 'layout-list',
  'filter': 'list-filter',
  'sort-filter': 'list-filter',
  'tree-view': 'list-tree',
  'nested-list': 'list-tree',
  'qrcode': 'qr-code',
  'barcode-2d': 'qr-code',
  'chart-polar': 'radar',
  'sonar': 'radar',
  'detection': 'radar',
  'sweep': 'radar',
  'sum': 'sigma',
  'summation': 'sigma',
  'aggregate': 'sigma',
  'total': 'sigma',
  'math-sigma': 'sigma',
  'data-table': 'table',
  'grid': 'table',
  'data-grid': 'table',
  'merge-cells': 'table-cells-merge',
  'cell-merge': 'table-cells-merge',
  'combine-cells': 'table-cells-merge',
  'split-cells': 'table-cells-split',
  'cell-split': 'table-cells-split',
  'unmerge-cells': 'table-cells-split',
  'trend-down': 'trending-down',
  'decrease': 'trending-down',
  'decline': 'trending-down',
  'arrow-trending-down': 'trending-down',
  'downtrend': 'trending-down',
  'trend-up': 'trending-up',
  'increase': 'trending-up',
  'growth': 'trending-up',
  'arrow-trending-up': 'trending-up',
  'uptrend': 'trending-up',
  'document': 'file',
  'page': 'file',
  'doc': 'file',
  'draft': 'file',
  'zip': 'file-archive',
  'compressed': 'file-archive',
  'archive-file': 'file-archive',
  'file-zip': 'file-archive',
  'rar': 'file-archive',
  'file-verified': 'file-check',
  'file-approved': 'file-check',
  'file-done': 'file-check',
  'document-check': 'file-check',
  'source-file': 'file-code',
  'code-file': 'file-code',
  'script': 'file-code',
  'integration-instructions': 'file-code',
  'image-file': 'file-image',
  'photo-file': 'file-image',
  'picture-file': 'file-image',
  'media-file': 'file-image',
  'file-protected': 'file-lock',
  'file-encrypted': 'file-lock',
  'secure-file': 'file-lock',
  'file-shield': 'file-lock',
  'new-file': 'file-plus',
  'create-file': 'file-plus',
  'add-file': 'file-plus',
  'file-add': 'file-plus',
  'note-add': 'file-plus',
  'find-in-file': 'file-search',
  'search-file': 'file-search',
  'file-find': 'file-search',
  'find-in-page': 'file-search',
  'excel': 'file-spreadsheet',
  'csv': 'file-spreadsheet',
  'file-xls': 'file-spreadsheet',
  'spreadsheet': 'file-spreadsheet',
  'file-table': 'file-spreadsheet',
  'text-file': 'file-text',
  'document-text': 'file-text',
  'readme': 'file-text',
  'description': 'file-text',
  'file-document': 'file-text',
  'file-remove': 'file-x',
  'file-delete': 'file-x',
  'file-reject': 'file-x',
  'remove-file': 'file-x',
  'documents': 'files',
  'multiple-files': 'files',
  'file-copy': 'files',
  'file-stack': 'files',
  'directory': 'folder',
  'dir': 'folder',
  'open-folder': 'folder-open',
  'folder-opened': 'folder-open',
  'directory-open': 'folder-open',
  'new-folder': 'folder-plus',
  'create-folder': 'folder-plus',
  'add-folder': 'folder-plus',
  'folder-add': 'folder-plus',
  'directory-tree': 'folder-tree',
  'file-tree': 'folder-tree',
  'folder-structure': 'folder-tree',
  'sitemap': 'folder-tree',
  'hierarchy': 'folder-tree',
  'account-tree': 'folder-tree',
  'news': 'newspaper',
  'article': 'newspaper',
  'press': 'newspaper',
  'publication': 'newspaper',
  'headline': 'newspaper',
  'journal': 'notebook',
  'diary': 'notebook',
  'notepad': 'notebook',
  'menu-book': 'notebook',
  'slides': 'presentation',
  'keynote': 'presentation',
  'pitch-deck': 'presentation',
  'terms': 'scroll-text',
  'legal-document': 'scroll-text',
  'terms-of-service': 'scroll-text',
  'scroll': 'scroll-text',
  'manuscript': 'scroll-text',
  'note': 'sticky-note',
  'memo': 'sticky-note',
  'post-it': 'sticky-note',
  'reminder-note': 'sticky-note',
  'waveform': 'audio-lines',
  'sound-wave': 'audio-lines',
  'equalizer': 'audio-lines',
  'audio-wave': 'audio-lines',
  'graphic-eq': 'audio-lines',
  'spectrum': 'audio-lines',
  'photo': 'camera',
  'take-photo': 'camera',
  'snapshot': 'camera',
  'capture': 'camera',
  'photography': 'camera',
  'photo-camera': 'camera',
  'no-camera': 'camera-off',
  'camera-disabled': 'camera-off',
  'camera-slash': 'camera-off',
  'no-photography': 'camera-off',
  'subtitles': 'captions',
  'closed-captions': 'captions',
  'cc': 'captions',
  'closed-captioning': 'captions',
  'subtitle': 'captions',
  'movie': 'film',
  'video-film': 'film',
  'cinema': 'film',
  'reel': 'film',
  'film-strip': 'film',
  'carousel': 'gallery-horizontal',
  'image-gallery': 'gallery-horizontal',
  'slideshow': 'gallery-horizontal',
  'photo-gallery': 'gallery-horizontal',
  'view-carousel': 'gallery-horizontal',
  'picture': 'image',
  'img': 'image',
  'photograph': 'image',
  'image-broken': 'image-off',
  'photo-off': 'image-off',
  'broken-image': 'image-off',
  'hide-image': 'image-off',
  'no-image': 'image-off',
  'add-photo': 'image-plus',
  'photo-plus': 'image-plus',
  'add-image': 'image-plus',
  'camera-plus': 'image-plus',
  'upload-image': 'image-plus',
  'gallery': 'images',
  'photo-library': 'images',
  'photo-album': 'images',
  'photos': 'images',
  'library-photo': 'images',
  'microphone': 'mic',
  'record-audio': 'mic',
  'voice': 'mic',
  'mute': 'mic-off',
  'microphone-off': 'mic-off',
  'muted': 'mic-off',
  'mic-mute': 'mic-off',
  'microphone-slash': 'mic-off',
  'song': 'music',
  'music-note': 'music',
  'musical-note': 'music',
  'tune': 'music',
  'audio-show': 'podcast',
  'podcasts': 'podcast',
  'radio-show': 'podcast',
  'camera-video': 'video',
  'videocam': 'video',
  'video-camera': 'video',
  'record-video': 'video',
  'cam': 'video',
  'camera-off-video': 'video-off',
  'videocam-off': 'video-off',
  'video-disabled': 'video-off',
  'video-camera-slash': 'video-off',
  'no-video': 'video-off',
  'pause-circle': 'circle-pause',
  'pause-button': 'circle-pause',
  'play-circle': 'circle-play',
  'play-button': 'circle-play',
  'stop-circle': 'circle-stop',
  'stop-button': 'circle-stop',
  'skip-ahead': 'fast-forward',
  'speed-up': 'fast-forward',
  'ff': 'fast-forward',
  'next-track': 'fast-forward',
  'hold': 'pause',
  'player-pause': 'pause',
  'pause-playback': 'pause',
  'pip': 'picture-in-picture',
  'floating-video': 'picture-in-picture',
  'mini-player': 'picture-in-picture',
  'start': 'play',
  'resume': 'play',
  'play-arrow': 'play',
  'player-play': 'play',
  'loop': 'repeat',
  'repeat-playback': 'repeat',
  'cycle': 'repeat',
  'fast-rewind': 'rewind',
  'skip-backward': 'rewind',
  'backward': 'rewind',
  'player-track-prev': 'rewind',
  'randomize': 'shuffle',
  'mix': 'shuffle',
  'arrows-shuffle': 'shuffle',
  'previous-track': 'skip-back',
  'skip-previous': 'skip-back',
  'step-backward': 'skip-back',
  'player-skip-back': 'skip-back',
  'skip-next': 'skip-forward',
  'player-skip-forward': 'skip-forward',
  'volume-high': 'volume-2',
  'volume-up': 'volume-2',
  'speaker': 'volume-2',
  'speaker-high': 'volume-2',
  'sound': 'volume-2',
  'volume-down': 'volume-low',
  'volume-1': 'volume-low',
  'speaker-low': 'volume-low',
  'quiet': 'volume-low',
  'low-volume': 'volume-low',
  'volume-mute': 'volume-x',
  'volume-off': 'volume-x',
  'speaker-mute': 'volume-x',
  'sound-off': 'volume-x',
  'speaker-x-mark': 'volume-x',
  'no-sound': 'volume-x',
  'font-size-decrease': 'a-arrow-down',
  'text-decrease': 'a-arrow-down',
  'font-decrease': 'a-arrow-down',
  'text-smaller': 'a-arrow-down',
  'font-size-increase': 'a-arrow-up',
  'text-increase': 'a-arrow-up',
  'font-increase': 'a-arrow-up',
  'text-larger': 'a-arrow-up',
  'font-size': 'a-large-small',
  'text-resize': 'a-large-small',
  'format-size': 'a-large-small',
  'text-size': 'a-large-small',
  'required': 'asterisk',
  'star-small': 'asterisk',
  'wildcard': 'asterisk',
  'footnote': 'asterisk',
  'text-bold': 'bold',
  'format-bold': 'bold',
  'strong': 'bold',
  'hashtag': 'hash',
  'number-sign': 'hash',
  'pound': 'hash',
  'title': 'heading',
  'text-h': 'heading',
  'h1': 'heading',
  'h2': 'heading-2',
  'h3': 'heading-3',
  'format-italic': 'italic',
  'text-italic': 'italic',
  'emphasis': 'italic',
  'unordered-list': 'list',
  'bullet-list': 'list',
  'list-bullet': 'list',
  'list-ul': 'list',
  'format-list-bulleted': 'list',
  'outdent': 'list-indent-decrease',
  'indent-decrease': 'list-indent-decrease',
  'text-outdent': 'list-indent-decrease',
  'dedent': 'list-indent-decrease',
  'indent': 'list-indent-increase',
  'indent-increase': 'list-indent-increase',
  'text-indent': 'list-indent-increase',
  'tab': 'list-indent-increase',
  'numbered-list': 'list-ordered',
  'list-numbers': 'list-ordered',
  'list-ol': 'list-ordered',
  'format-list-numbered': 'list-ordered',
  'ordered-list': 'list-ordered',
  'blockquote': 'quote',
  'citation': 'quote',
  'quotes': 'quote',
  'format-quote': 'quote',
  'quotation': 'quote',
  'clear-formatting': 'remove-formatting',
  'format-clear': 'remove-formatting',
  'strip-formatting': 'remove-formatting',
  'plain-text': 'remove-formatting',
  'spellcheck': 'spell-check',
  'grammar': 'spell-check',
  'proofread': 'spell-check',
  'abc-check': 'spell-check',
  'line-through': 'strikethrough',
  'text-strikethrough': 'strikethrough',
  'format-strikethrough': 'strikethrough',
  'crossed-out': 'strikethrough',
  'text-subscript': 'subscript',
  'format-subscript': 'subscript',
  'sub': 'subscript',
  'text-superscript': 'superscript',
  'format-superscript': 'superscript',
  'sup': 'superscript',
  'toc': 'table-of-contents',
  'index': 'table-of-contents',
  'outline': 'table-of-contents',
  'page-index': 'table-of-contents',
  'align-center': 'text-align-center',
  'center-align': 'text-align-center',
  'format-align-center': 'text-align-center',
  'align-right': 'text-align-end',
  'right-align': 'text-align-end',
  'text-align-right': 'text-align-end',
  'format-align-right': 'text-align-end',
  'justify': 'text-align-justify',
  'align-justify': 'text-align-justify',
  'format-align-justify': 'text-align-justify',
  'align-left': 'text-align-start',
  'left-align': 'text-align-start',
  'text-align-left': 'text-align-start',
  'format-align-left': 'text-align-start',
  'quote-block': 'text-quote',
  'pull-quote': 'text-quote',
  'select-text': 'text-select',
  'text-selection': 'text-select',
  'highlight-text': 'text-select',
  'selection': 'text-select',
  'select-all': 'text-select',
  'typography': 'type',
  'font': 'type',
  'text-format': 'type',
  'text-fields': 'type',
  'typeface': 'type',
  'text-underline': 'underline',
  'format-underline': 'underline',
  'format-underlined': 'underline',
  'align-horizontal-center': 'align-center-horizontal',
  'center-horizontal': 'align-center-horizontal',
  'align-vertical-center': 'align-center-vertical',
  'center-vertical': 'align-center-vertical',
  'align-horizontal-right': 'align-end-horizontal',
  'align-right-horizontal': 'align-end-horizontal',
  'align-bottom-horizontal': 'align-end-horizontal',
  'align-vertical-bottom': 'align-end-vertical',
  'align-bottom-vertical': 'align-end-vertical',
  'align-right-vertical': 'align-end-vertical',
  'align-horizontal-left': 'align-start-horizontal',
  'align-left-horizontal': 'align-start-horizontal',
  'align-top-horizontal': 'align-start-horizontal',
  'align-vertical-top': 'align-start-vertical',
  'align-top-vertical': 'align-start-vertical',
  'align-left-vertical': 'align-start-vertical',
  'layer-front': 'bring-to-front',
  'move-front': 'bring-to-front',
  'foreground': 'bring-to-front',
  'stack-front': 'bring-to-front',
  'flip-to-front': 'bring-to-front',
  'two-columns': 'columns-2',
  'split-view': 'columns-2',
  'dual-pane': 'columns-2',
  'view-column': 'columns-2',
  'three-columns': 'columns-3',
  'triple-pane': 'columns-3',
  'multi-column': 'columns-3',
  'trim': 'crop',
  'crop-image': 'crop',
  'resize-crop': 'crop',
  'water': 'droplet',
  'drop': 'droplet',
  'color-drop': 'droplet',
  'water-drop': 'droplet',
  'liquid': 'droplet',
  'ink': 'droplet',
  'clear': 'eraser',
  'erase': 'eraser',
  'rubber': 'eraser',
  'wipe': 'eraser',
  'mirror-horizontal': 'flip-horizontal',
  'reflect-horizontal': 'flip-horizontal',
  'mirror-vertical': 'flip-vertical',
  'reflect-vertical': 'flip-vertical',
  'highlight': 'highlighter',
  'marker': 'highlighter',
  'ink-highlighter': 'highlighter',
  'text-highlight': 'highlighter',
  'stack': 'layers',
  'stacked': 'layers',
  'depth': 'layers',
  'rectangle-stack': 'layers',
  'overlay': 'layers',
  'fill': 'paint-bucket',
  'color-fill': 'paint-bucket',
  'flood-fill': 'paint-bucket',
  'format-color-fill': 'paint-bucket',
  'brush': 'paintbrush',
  'paint': 'paintbrush',
  'draw': 'paintbrush',
  'color-palette': 'palette',
  'swatch': 'palette',
  'theme-colors': 'palette',
  'colors': 'palette',
  'eyedropper': 'pipette',
  'color-picker': 'pipette',
  'colorize': 'pipette',
  'eye-dropper': 'pipette',
  'color-sample': 'pipette',
  'measure': 'ruler',
  'dimensions': 'ruler',
  'straighten': 'ruler',
  'measurement': 'ruler',
  'move-back': 'send-to-back',
  'layer-back': 'send-to-back',
  'stack-back': 'send-to-back',
  'flip-to-back': 'send-to-back',
  'behind': 'send-to-back',
  'geometry': 'shapes',
  'design-elements': 'shapes',
  'primitives': 'shapes',
  'autograph': 'signature',
  'sign': 'signature',
  'handwriting': 'signature',
  'at': 'at-sign',
  'mention': 'at-sign',
  'email-at': 'at-sign',
  'at-symbol': 'at-sign',
  'notification': 'bell',
  'alert': 'bell',
  'notifications': 'bell',
  'reminder-bell': 'bell',
  'notification-badge': 'bell-dot',
  'notification-unread': 'bell-dot',
  'bell-badge': 'bell-dot',
  'bell-alert': 'bell-dot',
  'notification-new': 'bell-dot',
  'bell-important': 'bell-dot',
  'notification-off': 'bell-off',
  'mute-notification': 'bell-off',
  'bell-mute': 'bell-off',
  'bell-slash': 'bell-off',
  'notifications-off': 'bell-off',
  'do-not-disturb': 'bell-off',
  'notification-active': 'bell-ring',
  'bell-ringing': 'bell-ring',
  'bell-active': 'bell-ring',
  'notifications-active': 'bell-ring',
  'ringing': 'bell-ring',
  'forward-message': 'forward',
  'send-forward': 'forward',
  'share-forward': 'forward',
  'tray': 'inbox',
  'mailbox': 'inbox',
  'email': 'mail',
  'envelope': 'mail',
  'letter': 'mail',
  'e-mail': 'mail',
  'email-open': 'mail-open',
  'envelope-open': 'mail-open',
  'read-mail': 'mail-open',
  'mail-opened': 'mail-open',
  'drafts': 'mail-open',
  'compose': 'mail-plus',
  'new-email': 'mail-plus',
  'new-mail': 'mail-plus',
  'write-email': 'mail-plus',
  'outgoing-mail': 'mail-plus',
  'announcement': 'megaphone',
  'broadcast': 'megaphone',
  'campaign': 'megaphone',
  'speakerphone': 'megaphone',
  'bullhorn': 'megaphone',
  'promote': 'megaphone',
  'chat': 'message-circle',
  'chat-bubble': 'message-circle',
  'conversation': 'message-circle',
  'chat-circle': 'message-circle',
  'comment-circle': 'message-circle',
  'bubble': 'message-circle',
  'chat-dots': 'message-circle-more',
  'chat-typing': 'message-circle-more',
  'message-dots': 'message-circle-more',
  'chat-loading': 'message-circle-more',
  'new-chat': 'message-circle-plus',
  'add-comment': 'message-circle-plus',
  'new-conversation': 'message-circle-plus',
  'start-chat': 'message-circle-plus',
  'comment': 'message-square',
  'chat-square': 'message-square',
  'message': 'message-square',
  'speech-bubble': 'message-square',
  'chat-bubble-left': 'message-square',
  'unread-message': 'message-square-dot',
  'new-message': 'message-square-dot',
  'chat-notification': 'message-square-dot',
  'mark-chat-unread': 'message-square-dot',
  'reply-message': 'message-square-reply',
  'message-reply': 'message-square-reply',
  'quick-reply': 'message-square-reply',
  'respond': 'message-square-reply',
  'forum': 'messages-square',
  'conversation-thread': 'messages-square',
  'chats': 'messages-square',
  'discussion': 'messages-square',
  'chat-thread': 'messages-square',
  'call': 'phone',
  'telephone': 'phone',
  'dial': 'phone',
  'handset': 'phone',
  'incoming-call': 'phone-call',
  'phone-ringing': 'phone-call',
  'active-call': 'phone-call',
  'phone-in-talk': 'phone-call',
  'missed-call': 'phone-missed',
  'phone-x': 'phone-missed',
  'phone-disabled': 'phone-off',
  'end-call': 'phone-off',
  'hangup': 'phone-off',
  'phone-slash': 'phone-off',
  'no-phone': 'phone-off',
  'write-back': 'reply',
  'arrow-reply': 'reply',
  'respond-all': 'reply-all',
  'reply-to-all': 'reply-all',
  'present-screen': 'screen-share',
  'share-display': 'screen-share',
  'cast-screen': 'screen-share',
  'stop-screenshare': 'screen-share-off',
  'stop-screen-share': 'screen-share-off',
  'end-presentation': 'screen-share-off',
  'screencast-off': 'screen-share-off',
  'submit': 'send',
  'paper-plane': 'send',
  'dispatch': 'send',
  'paper-airplane': 'send',
  'smiley': 'smile',
  'happy': 'smile',
  'emoji': 'smile',
  'face-smile': 'smile',
  'mood-happy': 'smile',
  'sentiment-satisfied': 'smile',
  'voice-message': 'voicemail',
  'answering-machine': 'voicemail',
  'phone-voicemail': 'voicemail',
  'upc': 'barcode',
  'product-code': 'barcode',
  'scan-code': 'barcode',
  'cube': 'box',
  'crate': 'box',
  'parcel': 'box',
  'carton': 'box',
  'inventory': 'box',
  'card': 'credit-card',
  'debit-card': 'credit-card',
  'pay': 'credit-card',
  'billing': 'credit-card',
  'present': 'gift',
  'reward': 'gift',
  'redeem': 'gift',
  'giveaway': 'gift',
  'shipment': 'package',
  'box-sealed': 'package',
  'delivery': 'package',
  'bundle': 'package',
  'unbox': 'package-open',
  'unboxing': 'package-open',
  'package-unpack': 'package-open',
  'cube-transparent': 'package-open',
  'invoice': 'receipt',
  'receipt-text': 'receipt',
  'transaction': 'receipt',
  'receipt-percent': 'receipt',
  'bag': 'shopping-bag',
  'purchase-bag': 'shopping-bag',
  'store-bag': 'shopping-bag',
  'retail-bag': 'shopping-bag',
  'cart': 'shopping-cart',
  'basket': 'shopping-cart',
  'checkout': 'shopping-cart',
  'trolley': 'shopping-cart',
  'add-to-cart': 'shopping-cart',
  'shop': 'store',
  'storefront': 'store',
  'retail': 'store',
  'marketplace': 'store',
  'building-store': 'store',
  'label': 'tag',
  'price-tag': 'tag',
  'sell': 'tag',
  'badge-tag': 'tag',
  'labels': 'tags',
  'multi-tag': 'tags',
  'price-tags': 'tags',
  'coupon': 'ticket',
  'admission': 'ticket',
  'pass': 'ticket',
  'confirmation-number': 'ticket',
  'voucher': 'ticket',
  'shipping': 'truck',
  'freight': 'truck',
  'local-shipping': 'truck',
  'transport': 'truck',
  'alarm': 'alarm-clock',
  'reminder': 'alarm-clock',
  'wake-up': 'alarm-clock',
  'timer-alert': 'alarm-clock',
  'date': 'calendar',
  'schedule': 'calendar',
  'datepicker': 'calendar',
  'date-picker': 'calendar',
  'calendar-today': 'calendar',
  'event-confirmed': 'calendar-check',
  'date-confirmed': 'calendar-check',
  'calendar-done': 'calendar-check',
  'event-available': 'calendar-check',
  'calendar-confirmed': 'calendar-check',
  'schedule-time': 'calendar-clock',
  'event-time': 'calendar-clock',
  'calendar-time': 'calendar-clock',
  'date-time': 'calendar-clock',
  'appointment': 'calendar-clock',
  'calendar-month': 'calendar-days',
  'calendar-event': 'calendar-days',
  'date-range-view': 'calendar-days',
  'monthly-view': 'calendar-days',
  'add-event': 'calendar-plus',
  'new-event': 'calendar-plus',
  'calendar-add': 'calendar-plus',
  'schedule-new': 'calendar-plus',
  'create-event': 'calendar-plus',
  'date-range': 'calendar-range',
  'date-span': 'calendar-range',
  'calendar-period': 'calendar-range',
  'date-picker-range': 'calendar-range',
  'cancel-event': 'calendar-x',
  'remove-event': 'calendar-x',
  'calendar-cancel': 'calendar-x',
  'event-busy': 'calendar-x',
  'calendar-delete': 'calendar-x',
  'time': 'clock',
  'hour': 'clock',
  'oclock': 'clock',
  'recent': 'history',
  'clock-history': 'history',
  'time-past': 'history',
  'activity-log': 'history',
  'timer-sand': 'hourglass',
  'waiting': 'hourglass',
  'sandglass': 'hourglass',
  'hourglass-empty': 'hourglass',
  'stopwatch': 'timer',
  'countdown': 'timer',
  'elapsed': 'timer',
  'time-elapsed': 'timer',
  'consent': 'cookie',
  'browser-cookie': 'cookie',
  'biscuit': 'cookie',
  'gdpr': 'cookie',
  'biometric': 'fingerprint',
  'touch-id': 'fingerprint',
  'identity-verify': 'fingerprint',
  'finger-print': 'fingerprint',
  'fingerprint-pattern': 'fingerprint',
  'vpn': 'globe-lock',
  'vpn-lock': 'globe-lock',
  'secure-web': 'globe-lock',
  'private-browsing': 'globe-lock',
  'key': 'key-round',
  'password': 'key-round',
  'access': 'key-round',
  'vpn-key': 'key-round',
  'credential': 'key-round',
  'authentication': 'key-round',
  'locked': 'lock',
  'secure': 'lock',
  'private': 'lock',
  'lock-closed': 'lock',
  'padlock': 'lock',
  'unlocked': 'lock-open',
  'unlock': 'lock-open',
  'unsecured': 'lock-open',
  'lock-opened': 'lock-open',
  'padlock-open': 'lock-open',
  'sign-in': 'log-in',
  'login': 'log-in',
  'signin': 'log-in',
  'sign-out': 'log-out',
  'logout': 'log-out',
  'signout': 'log-out',
  'exit': 'log-out',
  'face-id': 'scan-face',
  'face-recognition': 'scan-face',
  'facial-recognition': 'scan-face',
  'face-scan': 'scan-face',
  'security': 'shield',
  'protection': 'shield',
  'defend': 'shield',
  'guard': 'shield',
  'armor': 'shield',
  'security-warning': 'shield-alert',
  'shield-warning': 'shield-alert',
  'shield-exclamation': 'shield-alert',
  'vulnerability': 'shield-alert',
  'verified-user': 'shield-check',
  'protected': 'shield-check',
  'shield-verified': 'shield-check',
  'unprotected': 'shield-off',
  'insecure': 'shield-off',
  'shield-disabled': 'shield-off',
  'shield-slash': 'shield-off',
  'remove-moderator': 'shield-off',
  'shield-rejected': 'shield-x',
  'blocked': 'shield-x',
  'shield-bad': 'shield-x',
  'security-error': 'shield-x',
  'gpp-bad': 'shield-x',
  'safe': 'vault',
  'secure-storage': 'vault',
  'strongbox': 'vault',
  'encrypted': 'vault',
  'incognito': 'venetian-mask',
  'anonymous': 'venetian-mask',
  'disguise': 'venetian-mask',
  'mask': 'venetian-mask',
  'privacy-mask': 'venetian-mask',
  'translate': 'languages',
  'translation': 'languages',
  'language': 'languages',
  'i18n': 'languages',
  'localization': 'languages',
  'l10n': 'languages',
  'dark-mode': 'moon',
  'night': 'moon',
  'dark-theme': 'moon',
  'crescent': 'moon',
  'preferences': 'settings',
  'config': 'settings',
  'configuration': 'settings',
  'gear': 'settings',
  'cog': 'settings',
  'adjustments': 'sliders-horizontal',
  'filters-horizontal': 'sliders-horizontal',
  'theme-toggle': 'sun-moon',
  'dark-mode-toggle': 'sun-moon',
  'appearance': 'sun-moon',
  'light-dark': 'sun-moon',
  'brightness-toggle': 'sun-moon',
  'tool': 'wrench',
  'spanner': 'wrench',
  'fix': 'wrench',
  'repair': 'wrench',
  'build': 'wrench',
  'configure': 'wrench',
  'company': 'building',
  'office': 'building',
  'organization': 'building',
  'enterprise': 'building',
  'corporate': 'building',
  'apartment': 'building',
  'board': 'kanban',
  'task-board': 'kanban',
  'columns': 'kanban',
  'view-kanban': 'kanban',
  'trello': 'kanban',
  'checkpoint': 'milestone',
  'flag-pennant': 'milestone',
  'diamond': 'milestone',
  'goal': 'milestone',
  'work': 'briefcase',
  'business': 'briefcase',
  'job': 'briefcase',
  'portfolio': 'briefcase',
  'career': 'briefcase',
  'professional': 'briefcase',
  'money': 'banknote',
  'cash': 'banknote',
  'bill': 'banknote',
  'currency': 'banknote',
  'payment': 'banknote',
  'dollar-bill': 'banknote',
  'price': 'circle-dollar-sign',
  'cost': 'circle-dollar-sign',
  'money-circle': 'circle-dollar-sign',
  'coin': 'circle-dollar-sign',
  'currency-coins': 'coins',
  'change': 'coins',
  'tokens': 'coins',
  'dollar': 'dollar-sign',
  'usd': 'dollar-sign',
  'money-sign': 'dollar-sign',
  'currency-dollar': 'dollar-sign',
  'eur': 'euro',
  'euro-sign': 'euro',
  'currency-euro': 'euro',
  'bank': 'landmark',
  'institution': 'landmark',
  'finance': 'landmark',
  'building-bank': 'landmark',
  'account-balance': 'landmark',
  'courthouse': 'landmark',
  'percentage': 'percent',
  'discount': 'percent',
  'rate': 'percent',
  'percent-badge': 'percent',
  'balance': 'scale',
  'justice': 'scale',
  'weigh': 'scale',
  'scales': 'scale',
  'legal': 'scale',
  'purse': 'wallet',
  'billfold': 'wallet',
  'account-balance-wallet': 'wallet',
  'vehicle': 'car',
  'automobile': 'car',
  'driving': 'car',
  'auto': 'car',
  'directions-car': 'car',
  'clinic': 'hospital',
  'emergency': 'hospital',
  'local-hospital': 'hospital',
  'current-location': 'locate',
  'near-me': 'locate',
  'my-location': 'locate',
  'find-location': 'locate',
  'gps-fixed': 'locate-fixed',
  'gps-fix': 'locate-fixed',
  'my-location-fixed': 'locate-fixed',
  'location-locked': 'locate-fixed',
  'atlas': 'map',
  'geography': 'map',
  'map-trifold': 'map',
  'directions': 'map',
  'location': 'map-pin',
  'location-on': 'map-pin',
  'pin-drop': 'map-pin',
  'place': 'map-pin',
  'location-off': 'map-pin-off',
  'no-location': 'map-pin-off',
  'remove-location': 'map-pin-off',
  'unpin-location': 'map-pin-off',
  'add-location': 'map-pin-plus',
  'new-location': 'map-pin-plus',
  'add-place': 'map-pin-plus',
  'pin-plus': 'map-pin-plus',
  'airplane': 'plane',
  'flight': 'plane',
  'travel': 'plane',
  'aircraft': 'plane',
  'path': 'route',
  'navigation': 'route',
  'itinerary': 'route',
  'route-points': 'waypoints',
  'journey': 'waypoints',
  'milestones': 'waypoints',
  'conversion-path': 'waypoints',
  'arrow-path': 'waypoints',
  'window': 'app-window',
  'desktop-window': 'app-window',
  'application': 'app-window',
  'browser-window': 'app-window',
  'cmd': 'command',
  'meta': 'command',
  'command-key': 'command',
  'keyboard-command': 'command',
  'bottom-panel': 'panel-bottom',
  'dock-bottom': 'panel-bottom',
  'layout-bottombar': 'panel-bottom',
  'bottom-panel-close': 'panel-bottom-close',
  'collapse-bottom': 'panel-bottom-close',
  'layout-bottombar-collapse': 'panel-bottom-close',
  'bottom-panel-open': 'panel-bottom-open',
  'expand-bottom': 'panel-bottom-open',
  'layout-bottombar-expand': 'panel-bottom-open',
  'left-panel': 'panel-left',
  'drawer': 'panel-left',
  'navigation-panel': 'panel-left',
  'sidebar-close': 'panel-left-close',
  'left-panel-close': 'panel-left-close',
  'collapse-sidebar': 'panel-left-close',
  'drawer-close': 'panel-left-close',
  'sidebar-open': 'panel-left-open',
  'left-panel-open': 'panel-left-open',
  'expand-sidebar': 'panel-left-open',
  'drawer-open': 'panel-left-open',
  'right-panel': 'panel-right',
  'sidebar-right': 'panel-right',
  'aside': 'panel-right',
  'layout-sidebar-right': 'panel-right',
  'right-panel-close': 'panel-right-close',
  'sidebar-right-close': 'panel-right-close',
  'collapse-right': 'panel-right-close',
  'right-panel-open': 'panel-right-open',
  'sidebar-right-open': 'panel-right-open',
  'shutdown': 'power',
  'power-off': 'power',
  'on-off': 'power',
  'switch-off': 'power',
  'power-button': 'power',
  'divider': 'separator-horizontal',
  'horizontal-rule': 'separator-horizontal',
  'hr': 'separator-horizontal',
  'line-separator': 'separator-horizontal',
  'power-cell': 'battery',
  'battery-standard': 'battery',
  'battery-indicator': 'battery',
  'battery-charge': 'battery-charging',
  'charging': 'battery-charging',
  'power-charging': 'battery-charging',
  'battery-100': 'battery-full',
  'battery-complete': 'battery-full',
  'power-full': 'battery-full',
  'battery-empty': 'battery-low',
  'battery-0': 'battery-low',
  'battery-critical': 'battery-low',
  'low-power': 'battery-low',
  'battery-50': 'battery-medium',
  'battery-mid': 'battery-medium',
  'battery-half': 'battery-medium',
  'battery-alert': 'battery-warning',
  'battery-error': 'battery-warning',
  'battery-critical-alert': 'battery-warning',
  'desktop': 'computer',
  'pc': 'computer',
  'workstation': 'computer',
  'desktop-tower': 'computer',
  'device-desktop': 'computer',
  'processor': 'cpu',
  'chip': 'cpu',
  'microchip': 'cpu',
  'computing': 'cpu',
  'cpu-chip': 'cpu',
  'hdd': 'hard-drive',
  'disk': 'hard-drive',
  'storage': 'hard-drive',
  'drive': 'hard-drive',
  'audio': 'headphones',
  'earphones': 'headphones',
  'headset': 'headphones',
  'input': 'keyboard',
  'typing': 'keyboard',
  'keys': 'keyboard',
  'notebook-computer': 'laptop',
  'laptop-mac': 'laptop',
  'computer-desktop': 'laptop',
  'device-laptop': 'laptop',
  'portable': 'laptop',
  'display': 'monitor',
  'screen': 'monitor',
  'responsive': 'monitor-smartphone',
  'devices': 'monitor-smartphone',
  'device-phone-mobile': 'monitor-smartphone',
  'multi-device': 'monitor-smartphone',
  'cursor-device': 'mouse',
  'pointing-device': 'mouse',
  'print': 'printer',
  'printing': 'printer',
  'backend': 'server',
  'host': 'server',
  'rack': 'server',
  'hard-drives': 'server',
  'datacenter': 'server',
  'mobile': 'smartphone',
  'phone-mobile': 'smartphone',
  'device-mobile': 'smartphone',
  'cell-phone': 'smartphone',
  'iphone': 'smartphone',
  'ipad': 'tablet',
  'device-tablet': 'tablet',
  'tablet-device': 'tablet',
  'television': 'tv',
  'monitor-tv': 'tv',
  'device-tv': 'tv',
  'usb-port': 'usb',
  'usb-drive': 'usb',
  'usb-cable': 'usb',
  'usb-connection': 'usb',
  'smartwatch': 'watch',
  'wristwatch': 'watch',
  'device-watch': 'watch',
  'timepiece': 'watch',
  'web-camera': 'webcam',
  'camera-front': 'webcam',
  'video-camera-front': 'webcam',
  'facecam': 'webcam',
  'bt': 'bluetooth',
  'wireless-bluetooth': 'bluetooth',
  'bluetooth-disabled': 'bluetooth-off',
  'bt-off': 'bluetooth-off',
  'screencast': 'cast',
  'chromecast': 'cast',
  'airplay': 'cast',
  'screen-mirror': 'cast',
  'stream-to': 'cast',
  'offline': 'cloud-off',
  'no-cloud': 'cloud-off',
  'cloud-slash': 'cloud-off',
  'disconnected-cloud': 'cloud-off',
  'cloud-refresh': 'cloud-sync',
  'sync-cloud': 'cloud-sync',
  'cloud-update': 'cloud-sync',
  'cloud-connection': 'cloud-sync',
  'world': 'globe',
  'earth': 'globe',
  'internet': 'globe',
  'web': 'globe',
  'globe-alt': 'globe',
  'nodes': 'network',
  'hub': 'network',
  'connected': 'network',
  'mesh': 'network',
  'plugin': 'plug',
  'socket': 'plug',
  'outlet': 'plug',
  'connector': 'plug',
  'power-plug': 'plug',
  'broadcast-tower': 'radio-tower',
  'cell-tower': 'radio-tower',
  'antenna': 'radio-tower',
  'transmission-tower': 'radio-tower',
  'tower': 'radio-tower',
  'wireless': 'router',
  'access-point': 'router',
  'modem': 'router',
  'gateway': 'router',
  'rss-feed': 'rss',
  'feed': 'rss',
  'syndication': 'rss',
  'web-feed': 'rss',
  'cell-signal': 'signal',
  'signal-strength': 'signal',
  'reception': 'signal',
  'cellular': 'signal',
  'bars': 'signal',
  'disconnect': 'unplug',
  'unplugged': 'unplug',
  'plug-off': 'unplug',
  'power-disconnect': 'unplug',
  'network-wireless': 'wifi',
  'wi-fi': 'wifi',
  'wifi-strong': 'wifi-high',
  'wifi-full': 'wifi-high',
  'network-wifi': 'wifi-high',
  'signal-strong': 'wifi-high',
  'wifi-weak': 'wifi-low',
  'wifi-1-bar': 'wifi-low',
  'poor-signal': 'wifi-low',
  'weak-connection': 'wifi-low',
  'no-wifi': 'wifi-off',
  'wireless-off': 'wifi-off',
  'wifi-disabled': 'wifi-off',
  'no-signal': 'wifi-zero',
  'wifi-none': 'wifi-zero',
  'disconnected-wifi': 'wifi-zero',
  'signal-none': 'wifi-zero',
  'curly-braces': 'braces',
  'brackets-curly': 'braces',
  'json': 'braces',
  'code-block': 'braces',
  'data-object': 'braces',
  'code-bracket': 'braces',
  'issue': 'bug',
  'defect': 'bug',
  'bug-report': 'bug',
  'debug': 'bug',
  'error-bug': 'bug',
  'bug-ant': 'bug',
  'source-code': 'code',
  'markup': 'code',
  'code-brackets': 'code',
  'dev': 'code',
  'develop': 'code',
  'widget': 'component',
  'module': 'component',
  'extension': 'component',
  'docker': 'container',
  'box-package': 'container',
  'shipping-container': 'container',
  'deployed-code': 'container',
  'db': 'database',
  'datastore': 'database',
  'data-storage': 'database',
  'circle-stack': 'database',
  'sql': 'database',
  'db-backup': 'database-backup',
  'backup-restore': 'database-backup',
  'data-export': 'database-backup',
  'database-restore': 'database-backup',
  'compare': 'diff',
  'file-diff': 'diff',
  'code-diff': 'diff',
  'git-diff': 'diff',
  'difference': 'diff',
  'branch': 'git-branch',
  'version-branch': 'git-branch',
  'fork-branch': 'git-branch',
  'vcs-branch': 'git-branch',
  'commit': 'git-commit-horizontal',
  'git-commit': 'git-commit-horizontal',
  'version-commit': 'git-commit-horizontal',
  'compare-branches': 'git-compare',
  'git-diff-branches': 'git-compare',
  'pull-compare': 'git-compare',
  'compare-arrows': 'git-compare',
  'fork': 'git-fork',
  'branch-fork': 'git-fork',
  'repo-fork': 'git-fork',
  'git-history': 'git-graph',
  'commit-graph': 'git-graph',
  'git-log': 'git-graph',
  'merge-branch': 'git-merge',
  'branch-merge': 'git-merge',
  'pull-request': 'git-pull-request',
  'pr': 'git-pull-request',
  'merge-request': 'git-pull-request',
  'pr-closed': 'git-pull-request-closed',
  'pull-request-closed': 'git-pull-request-closed',
  'merge-request-closed': 'git-pull-request-closed',
  'pr-draft': 'git-pull-request-draft',
  'pull-request-draft': 'git-pull-request-draft',
  'merge-request-draft': 'git-pull-request-draft',
  'log-file': 'logs',
  'audit-log': 'logs',
  'receipt-long': 'logs',
  'event-log': 'logs',
  'addon': 'puzzle',
  'puzzle-piece': 'puzzle',
  'integration': 'puzzle',
  'add-on': 'puzzle',
  'regular-expression': 'regex',
  'regexp': 'regex',
  'pattern-match': 'regex',
  'code-search': 'search-code',
  'find-in-code': 'search-code',
  'grep': 'search-code',
  'search-source': 'search-code',
  'console': 'terminal',
  'command-line': 'terminal',
  'cli': 'terminal',
  'shell': 'terminal',
  'prompt': 'terminal',
  'var': 'variable',
  'parameter': 'variable',
  'code-variable': 'variable',
  'callback': 'webhook',
  'http-hook': 'webhook',
  'api-hook': 'webhook',
  'webhooks': 'webhook',
  'pipeline': 'workflow',
  'flow': 'workflow',
  'process': 'workflow',
  'dag': 'workflow',
  'github-logo': 'github',
  'brand-github': 'github',
  'medal': 'award',
  'achievement': 'award',
  'ribbon': 'award',
  'badge-award': 'award',
  'prize': 'award',
  'premium': 'crown',
  'king': 'crown',
  'queen': 'crown',
  'vip': 'crown',
  'royalty': 'crown',
  'pro': 'crown',
  'dice': 'dices',
  'random': 'dices',
  'chance': 'dices',
  'gamble': 'dices',
  'casino': 'dices',
  'roll': 'dices',
  'celebrate': 'party-popper',
  'celebration': 'party-popper',
  'confetti': 'party-popper',
  'hooray': 'party-popper',
  'tada': 'party-popper',
  'rating': 'star',
  'bookmark-star': 'star',
  'half-rating': 'star-half',
  'partial-star': 'star-half',
  'rating-half': 'star-half',
  'winner': 'trophy',
  'champion': 'trophy',
  'cup': 'trophy',
  'robot': 'bot',
  'ai-bot': 'bot',
  'chatbot': 'bot',
  'smart-toy': 'bot',
  'automation': 'bot',
  'ai': 'brain',
  'intelligence': 'brain',
  'mind': 'brain',
  'cognitive': 'brain',
  'neural': 'brain',
  'smart': 'brain',
  'psychology': 'brain',
  'magic': 'sparkles',
  'auto-enhance': 'sparkles',
  'stars': 'sparkles',
  'glitter': 'sparkles',
  'sparkle': 'sparkles',
  'magic-wand': 'wand-sparkles',
  'auto-fix': 'wand-sparkles',
  'enhance': 'wand-sparkles',
  'wizard': 'wand-sparkles',
  'wand': 'wand-sparkles',
  'documentation': 'book',
  'manual': 'book',
  'reference': 'book',
  'textbook': 'book',
  'guidebook': 'book',
  'read': 'book-open',
  'reading': 'book-open',
  'open-book': 'book-open',
  'story': 'book-open',
  'novel': 'book-open',
  'flask': 'flask-conical',
  'lab': 'flask-conical',
  'experiment': 'flask-conical',
  'science': 'flask-conical',
  'beaker': 'flask-conical',
  'chemistry': 'flask-conical',
  'test-tube': 'flask-conical',
  'school': 'graduation-cap',
  'academic-cap': 'graduation-cap',
  'education': 'graduation-cap',
  'graduate': 'graduation-cap',
  'mortarboard': 'graduation-cap',
  'books': 'library',
  'bookshelf': 'library',
  'collection': 'library',
  'local-library': 'library',
  'cloud-storage': 'cloud',
  'saas': 'cloud',
  'hosted': 'cloud',
  'thunderstorm': 'cloud-lightning',
  'storm': 'cloud-lightning',
  'cloud-storm': 'cloud-lightning',
  'thunder': 'cloud-lightning',
  'rain': 'cloud-rain',
  'rainy': 'cloud-rain',
  'precipitation': 'cloud-rain',
  'weather-rain': 'cloud-rain',
  'cold': 'snowflake',
  'winter': 'snowflake',
  'freeze': 'snowflake',
  'ac': 'snowflake',
  'air-conditioning': 'snowflake',
  'light-mode': 'sun',
  'brightness': 'sun',
  'sunny': 'sun',
  'day': 'sun',
  'temperature': 'thermometer',
  'thermostat': 'thermometer',
  'temp': 'thermometer',
  'air': 'wind',
  'breeze': 'wind',
  'windy': 'wind',
  'gust': 'wind',
  'wheelchair': 'accessibility',
  'accessible': 'accessibility',
  'a11y': 'accessibility',
  'disability': 'accessibility',
  'calculate': 'calculator',
  'math': 'calculator',
  'computation': 'calculator',
  'arithmetic': 'calculator',
  'dot-large': 'circle',
  'ring': 'circle',
  'radio-button-off': 'circle',
  'empty-circle': 'circle',
  'cafe': 'coffee',
  'break': 'coffee',
  'mug': 'coffee',
  'espresso': 'coffee',
  'local-cafe': 'coffee',
  'ip': 'copyright',
  'rights': 'copyright',
  'legal-copyright': 'copyright',
  'medical': 'cross',
  'first-aid': 'cross',
  'hospital-cross': 'cross',
  'health': 'cross',
  'red-cross': 'cross',
  'medical-cross': 'cross',
  'unlimited': 'infinity',
  'infinite': 'infinity',
  'all-inclusive': 'infinity',
  'forever': 'infinity',
  'eco': 'leaf',
  'nature': 'leaf',
  'plant': 'leaf',
  'organic': 'leaf',
  'green': 'leaf',
  'environment': 'leaf',
  'idea': 'lightbulb',
  'tip': 'lightbulb',
  'bulb': 'lightbulb',
  'light-bulb': 'lightbulb',
  'hint': 'lightbulb',
  'suggestion': 'lightbulb',
  'recycling': 'recycle',
  'sustainable': 'recycle',
  'rectangle': 'square',
  'box-empty': 'square',
  'shape-square': 'square',
  'crosshair-circle': 'target',
  'focal-point': 'target',
  'shape-triangle': 'triangle',
  'delta': 'triangle',
  'change-history': 'triangle',
};
