// Auto-generated — do not edit
export const iconNames = [
  'home',
  'dashboard',
  'menu',
  'close',
  'back',
  'next',
  'up',
  'down',
  'external-link',
  'chevron-right',
  'chevron-down',
  'chevron-up',
  'chevron-left',
  'more',
  'more-options',
  'sidebar',
  'columns',
  'anchor',
  'user',
  'avatar',
  'users',
  'add-user',
  'remove-user',
  'assigned',
  'admin',
  'user-settings',
  'anonymous',
  'roles',
  'login',
  'logout',
  'fingerprint',
  'add',
  'edit',
  'delete',
  'save',
  'check',
  'refresh',
  'undo',
  'redo',
  'copy',
  'clipboard',
  'copied',
  'paste',
  'cut',
  'move',
  'drag-handle',
  'upload',
  'download',
  'import',
  'export',
  'print',
  'share',
  'send',
  'minus',
  'file',
  'document',
  'pdf',
  'folder',
  'new-folder',
  'open-folder',
  'archive',
  'zip',
  'attachment',
  'link',
  'unlink',
  'file-add',
  'file-remove',
  'image',
  'gallery',
  'video',
  'video-off',
  'camera',
  'camera-off',
  'volume',
  'volume-low',
  'mute',
  'music',
  'microphone',
  'microphone-off',
  'headphones',
  'podcast',
  'broadcast',
  'crop',
  'rotate',
  'play',
  'pause',
  'stop',
  'skip-next',
  'skip-previous',
  'fast-forward',
  'rewind',
  'shuffle',
  'repeat',
  'record',
  'filter',
  'sort',
  'list',
  'table',
  'grid',
  'chart-bar',
  'chart-line',
  'chart-pie',
  'view',
  'hide',
  'search',
  'zoom-in',
  'zoom-out',
  'fullscreen',
  'exit-fullscreen',
  'board',
  'activity',
  'calendar',
  'schedule',
  'scheduled',
  'overdue',
  'clock',
  'timer',
  'watch',
  'success',
  'error',
  'warning',
  'info',
  'help',
  'loading',
  'filled-circle',
  'empty-circle',
  'verified',
  'smile',
  'frown',
  'checkbox',
  'checkbox-empty',
  'toggle',
  'toggle-off',
  'heart',
  'unlike',
  'star',
  'bookmark',
  'thumbs-up',
  'thumbs-down',
  'reply',
  'comment',
  'comments',
  'typing',
  'mention',
  'ban',
  'flag',
  'pin',
  'award',
  'trophy',
  'gift',
  'target',
  'notifications',
  'email',
  'inbox',
  'phone',
  'contacts',
  'notifications-off',
  'chat',
  'megaphone',
  'lock',
  'unlock',
  'security',
  'secure',
  'key',
  'security-off',
  'settings',
  'sliders',
  'theme',
  'sun',
  'dark-mode',
  'accessibility',
  'plugin',
  'webhook',
  'globe',
  'cart',
  'add-to-cart',
  'payment',
  'wallet',
  'money',
  'tag',
  'tags',
  'percent',
  'ticket',
  'package',
  'shipping',
  'delivery',
  'return',
  'receipt',
  'invoice',
  'store',
  'shopping-bag',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'code',
  'quote',
  'heading',
  'paragraph',
  'bullet-list',
  'numbered-list',
  'checklist',
  'indent',
  'outdent',
  'align-left',
  'align-center',
  'align-right',
  'justify',
  'emoji',
  'type',
  'brush',
  'pen',
  'color',
  'eraser',
  'mouse-pointer',
  'layers',
  'fork',
  'tree',
  'progress',
  'milestone',
  'tasks',
  'location',
  'map',
  'directions',
  'compass',
  'current-location',
  'hospital',
  'measure',
  'desktop',
  'laptop',
  'mobile',
  'tablet',
  'keyboard',
  'cpu',
  'storage',
  'usb',
  'cast',
  'tv',
  'charging',
  'terminal',
  'database',
  'server',
  'cloud',
  'cloud-upload',
  'cloud-download',
  'network',
  'wifi',
  'bluetooth',
  'wifi-off',
  'bug',
  'branch',
  'merge',
  'pull-request',
  'commit',
  'sparkles',
  'wand',
  'bot',
  'tip',
  'zap',
  'rocket',
  'power',
  'battery',
  'tool',
  'tools',
  'qr-code',
  'barcode',
  'calculator',
  'random',
  'history',
  'command',
  'hash',
  'rain',
  'storm',
  'snow',
  'wind',
  'temperature',
  'water',
  'fire',
  'trending-up',
  'trending-down',
  'balance',
  'swap',
  'savings',
  'vault',
  'docs',
  'book-open',
  'graduation',
  'support',
  'briefcase',
  'company',
  'organization',
  'news',
  'rss',
  'coffee',
  'infinity',
  'eco',
  'hexagon',
  'triangle',
  'github',
  'apple',
  'facebook',
  'twitter',
  'linkedin',
  'slack',
  'instagram',
  'youtube',
];

export const iconAliases = {
  'hamburger': 'menu',
  'bars': 'menu',
  'cancel': 'close',
  'dismiss': 'close',
  'x': 'close',
  'previous': 'back',
  'arrow-left': 'back',
  'forward': 'next',
  'arrow-right': 'next',
  'arrow-up': 'up',
  'level-up': 'up',
  'arrow-down': 'down',
  'open-in-new': 'external-link',
  'external': 'external-link',
  'caret-right': 'chevron-right',
  'angle-right': 'chevron-right',
  'pointing-right': 'chevron-right',
  'caret-down': 'chevron-down',
  'dropdown': 'chevron-down',
  'expand': 'fullscreen',
  'angle-down': 'chevron-down',
  'caret-up': 'chevron-up',
  'collapse': 'chevron-up',
  'angle-up': 'chevron-up',
  'caret-left': 'chevron-left',
  'angle-left': 'chevron-left',
  'ellipsis': 'more',
  'dots': 'more',
  'ellipsis-vertical': 'more-options',
  'kebab': 'more-options',
  'options': 'more-options',
  'panel': 'sidebar',
  'drawer': 'sidebar',
  'layout': 'columns',
  'jump-to': 'anchor',
  'person': 'user',
  'profile': 'user',
  'account': 'avatar',
  'user-circle': 'avatar',
  'team': 'users',
  'people': 'users',
  'group': 'users',
  'user-plus': 'add-user',
  'invite': 'add-user',
  'user-minus': 'remove-user',
  'user-check': 'assigned',
  'user-shield': 'admin',
  'user-gear': 'user-settings',
  'moderator': 'user-settings',
  'guest': 'anonymous',
  'incognito': 'anonymous',
  'permissions': 'roles',
  'sign-in': 'login',
  'log-in': 'login',
  'sign-out': 'logout',
  'exit': 'logout',
  'log-out': 'logout',
  'biometric': 'fingerprint',
  'plus': 'add',
  'create': 'add',
  'new': 'add',
  'plus-circle': 'add',
  'add-circle': 'add',
  'add-square': 'add',
  'pencil': 'edit',
  'modify': 'edit',
  'write': 'edit',
  'compose': 'edit',
  'trash': 'delete',
  'remove': 'minus',
  'floppy-disk': 'save',
  'done': 'check',
  'confirm': 'check',
  'complete': 'success',
  'checkmark': 'check',
  'reload': 'refresh',
  'sync': 'refresh',
  'synchronize': 'refresh',
  'revert': 'undo',
  'duplicate': 'copy',
  'clone': 'copy',
  'clipboard-check': 'copied',
  'scissors': 'cut',
  'grip': 'drag-handle',
  'reorder': 'drag-handle',
  'submit': 'send',
  'subtract': 'minus',
  'remove-circle': 'minus',
  'minus-circle': 'minus',
  'file-text': 'document',
  'content': 'document',
  'file-pdf': 'pdf',
  'directory': 'folder',
  'folder-plus': 'new-folder',
  'folder-open': 'open-folder',
  'box': 'package',
  'compress': 'zip',
  'paperclip': 'attachment',
  'attach': 'attachment',
  'url': 'link',
  'chain': 'link',
  'linkify': 'link',
  'disconnect': 'unlink',
  'file-plus': 'file-add',
  'new-file': 'file-add',
  'file-minus': 'file-remove',
  'delete-file': 'file-remove',
  'photo': 'image',
  'picture': 'image',
  'images': 'gallery',
  'photos': 'gallery',
  'movie': 'video',
  'video-camera': 'video',
  'video-disabled': 'video-off',
  'camera-slash': 'camera-off',
  'audio': 'music',
  'speaker': 'volume',
  'unmute': 'volume',
  'volume-off': 'mute',
  'volume-x': 'mute',
  'song': 'music',
  'mic': 'microphone',
  'mic-off': 'microphone-off',
  'mute-mic': 'microphone-off',
  'headset': 'headphones',
  'live': 'broadcast',
  'radio-tower': 'broadcast',
  'trim': 'crop',
  'turn': 'rotate',
  'play-circle': 'play',
  'pause-circle': 'pause',
  'forward-step': 'skip-next',
  'next-track': 'skip-next',
  'backward-step': 'skip-previous',
  'previous-track': 'skip-previous',
  'random': 'shuffle',
  'loop': 'repeat',
  'funnel': 'filter',
  'sort-content-ascending': 'sort',
  'sort-content-descending': 'sort',
  'sort-numeric-ascending': 'sort',
  'list-view': 'list',
  'list-layout': 'list',
  'table-view': 'table',
  'grid-view': 'grid',
  'card-view': 'grid',
  'bar-chart': 'chart-bar',
  'chart': 'chart-bar',
  'line-chart': 'chart-line',
  'analytics': 'chart-line',
  'trends': 'chart-line',
  'line-graph': 'chart-line',
  'pie-chart': 'chart-pie',
  'statistics': 'chart-pie',
  'show': 'view',
  'visible': 'view',
  'eye': 'view',
  'invisible': 'hide',
  'eye-off': 'hide',
  'blind': 'hide',
  'magnifying-glass': 'search',
  'find': 'search',
  'zoom': 'zoom-in',
  'maximize': 'fullscreen',
  'minimize': 'exit-fullscreen',
  'kanban': 'board',
  'board-view': 'board',
  'pulse': 'activity',
  'date': 'calendar',
  'events': 'schedule',
  'calendar-days': 'schedule',
  'due-date': 'scheduled',
  'calendar-check': 'scheduled',
  'deadline': 'overdue',
  'calendar-x': 'overdue',
  'time': 'clock',
  'countdown': 'timer',
  'stopwatch': 'timer',
  'smartwatch': 'watch',
  'check-circle': 'success',
  'x-circle': 'error',
  'failed': 'error',
  'alert': 'warning',
  'caution': 'warning',
  'attention': 'warning',
  'warning-circle': 'warning',
  'exclamation-circle': 'warning',
  'exclamation': 'warning',
  'warning-sign': 'warning',
  'exclamation-triangle': 'warning',
  'information': 'info',
  'info-circle': 'info',
  'question': 'help',
  'faq': 'help',
  'help-circle': 'help',
  'question-circle': 'help',
  'spinner': 'loading',
  'wait': 'loading',
  'hourglass': 'loading',
  'active': 'filled-circle',
  'selected': 'filled-circle',
  'radio': 'filled-circle',
  'radio-selected': 'filled-circle',
  'circle-dot': 'filled-circle',
  'disc': 'filled-circle',
  'dot': 'filled-circle',
  'inactive': 'empty-circle',
  'unselected': 'empty-circle',
  'radio-empty': 'empty-circle',
  'radio-unselected': 'empty-circle',
  'circle': 'empty-circle',
  'badge-check': 'verified',
  'certificate': 'verified',
  'happy': 'smile',
  'satisfied': 'smile',
  'sad': 'frown',
  'dissatisfied': 'frown',
  'square-check': 'checkbox',
  'checked': 'checkbox',
  'unchecked': 'checkbox-empty',
  'square': 'checkbox-empty',
  'switch': 'toggle',
  'toggle-on': 'toggle',
  'switch-off': 'toggle-off',
  'like': 'heart',
  'favorite': 'star',
  'heart-crack': 'unlike',
  'rating': 'star',
  'empty-star': 'star',
  'star-outline': 'star',
  'save': 'bookmark',
  'remove-bookmark': 'bookmark',
  'upvote': 'thumbs-up',
  'dislike': 'thumbs-down',
  'downvote': 'thumbs-down',
  'message': 'comment',
  'discussion': 'comments',
  'message-dots': 'typing',
  'at': 'mention',
  'at-sign': 'mention',
  'block': 'ban',
  'restricted': 'ban',
  'dont': 'ban',
  'prohibited': 'ban',
  'report': 'flag',
  'thumbtack': 'pin',
  'pinned': 'pin',
  'badge': 'award',
  'achievement': 'award',
  'winner': 'trophy',
  'reward': 'gift',
  'present': 'gift',
  'goal': 'target',
  'bullseye': 'target',
  'bell': 'notifications',
  'alerts': 'notifications',
  'alarm': 'notifications',
  'mail': 'email',
  'envelope': 'email',
  'call': 'phone',
  'address-book': 'contacts',
  'bell-off': 'notifications-off',
  'alerts-off': 'notifications-off',
  'message-square': 'chat',
  'im': 'chat',
  'direct-message': 'chat',
  'announcement': 'megaphone',
  'bullhorn': 'megaphone',
  'loudspeaker': 'megaphone',
  'locked': 'lock',
  'secure': 'lock',
  'privacy': 'lock',
  'unlocked': 'unlock',
  'shield': 'security',
  'shield-check': 'secure',
  'protected': 'secure',
  'password': 'key',
  'access': 'key',
  'shield-off': 'security-off',
  'unprotected': 'security-off',
  'gear': 'settings',
  'cog': 'settings',
  'preferences': 'settings',
  'configure': 'settings',
  'cogs': 'settings',
  'setting': 'settings',
  'adjustments': 'sliders',
  'palette': 'theme',
  'appearance': 'theme',
  'light-mode': 'sun',
  'moon': 'dark-mode',
  'extension': 'plugin',
  'puzzle': 'plugin',
  'api': 'webhook',
  'world': 'globe',
  'public': 'globe',
  'language': 'globe',
  'browser': 'globe',
  'shopping-cart': 'cart',
  'cart-plus': 'add-to-cart',
  'credit-card': 'payment',
  'billing': 'payment',
  'dollar': 'money',
  'currency': 'money',
  'usd': 'money',
  'label': 'tag',
  'price': 'tag',
  'labels': 'tags',
  'discount': 'percent',
  'coupon': 'ticket',
  'order': 'package',
  'cube': 'package',
  'cubes': 'package',
  'truck': 'shipping',
  'express': 'delivery',
  'shop': 'store',
  'bag': 'shopping-bag',
  'blockquote': 'quote',
  'h1': 'heading',
  'title': 'heading',
  'list-ul': 'bullet-list',
  'unordered-list': 'bullet-list',
  'list-ol': 'numbered-list',
  'ordered-list': 'numbered-list',
  'todo-list': 'checklist',
  'align-justify': 'justify',
  'smiley': 'emoji',
  'typography': 'type',
  'font': 'type',
  'paint': 'brush',
  'draw': 'pen',
  'eyedropper': 'color',
  'color-picker': 'color',
  'clear': 'eraser',
  'cursor': 'mouse-pointer',
  'select': 'mouse-pointer',
  'pointer': 'mouse-pointer',
  'stack': 'layers',
  'hierarchy': 'tree',
  'sitemap': 'tree',
  'org-chart': 'tree',
  'diamond': 'milestone',
  'todos': 'tasks',
  'map-pin': 'location',
  'marker': 'location',
  'route': 'directions',
  'navigate': 'compass',
  'crosshairs': 'current-location',
  'near-me': 'current-location',
  'medical': 'hospital',
  'clinic': 'hospital',
  'ruler': 'measure',
  'distance': 'measure',
  'monitor': 'desktop',
  'computer': 'desktop',
  'notebook': 'laptop',
  'smartphone': 'mobile',
  'ipad': 'tablet',
  'processor': 'cpu',
  'chip': 'cpu',
  'hard-drive': 'storage',
  'disk': 'storage',
  'chromecast': 'cast',
  'airplay': 'cast',
  'television': 'tv',
  'screen': 'tv',
  'battery-charging': 'charging',
  'console': 'terminal',
  'command-line': 'terminal',
  'db': 'database',
  'backup': 'cloud-upload',
  'wifi-disabled': 'wifi-off',
  'no-wifi': 'wifi-off',
  'offline': 'wifi-off',
  'issue': 'bug',
  'commit': 'commit',
  'ai': 'sparkles',
  'magic': 'sparkles',
  'wizard': 'wand',
  'robot': 'bot',
  'automation': 'bot',
  'idea': 'tip',
  'lightbulb': 'tip',
  'hint': 'tip',
  'lightning': 'storm',
  'fast': 'zap',
  'instant': 'zap',
  'launch': 'rocket',
  'deploy': 'rocket',
  'boost': 'rocket',
  'shutdown': 'power',
  'wrench': 'tool',
  'toolbox': 'tools',
  'qr': 'qr-code',
  'qrcode': 'qr-code',
  'dice': 'random',
  'restore': 'history',
  'cmd': 'command',
  'hashtag': 'hash',
  'number-sign': 'hash',
  'pound': 'hash',
  'rainy': 'rain',
  'stormy': 'storm',
  'cold': 'snow',
  'snowflake': 'snow',
  'windy': 'wind',
  'thermometer': 'temperature',
  'droplet': 'water',
  'humidity': 'water',
  'hot': 'fire',
  'flame': 'fire',
  'trending': 'fire',
  'increase': 'trending-up',
  'growth': 'trending-up',
  'decrease': 'trending-down',
  'decline': 'trending-down',
  'scale': 'balance',
  'transfer': 'swap',
  'exchange': 'swap',
  'piggy-bank': 'savings',
  'safe': 'vault',
  'book': 'docs',
  'documentation': 'docs',
  'reading': 'book-open',
  'education': 'graduation',
  'academic': 'graduation',
  'student': 'graduation',
  'lifebuoy': 'support',
  'work': 'briefcase',
  'job': 'briefcase',
  'building': 'company',
  'office': 'company',
  'org': 'organization',
  'corporate': 'organization',
  'enterprise': 'organization',
  'newspaper': 'news',
  'article': 'news',
  'feed': 'rss',
  'cafe': 'coffee',
  'break': 'coffee',
  'unlimited': 'infinity',
  'leaf': 'eco',
  'nature': 'eco',
};
