// Cross-library icon mappings
// Keys are canonical Semantic UI icon names
export const iconMappings = {
  'home': {
    category: 'navigation',
    aliases: [],
    description: 'Home/start page',
    lucide: 'house',
    phosphor: 'house',
    tabler: 'home',
    materialSymbols: 'home',
    heroicons: 'home',
  },
  'dashboard': {
    category: 'navigation',
    aliases: [],
    description: 'Dashboard/overview',
    lucide: 'layout-dashboard',
    phosphor: 'squares-four',
    tabler: 'dashboard',
    materialSymbols: 'dashboard',
    heroicons: 'squares-2x2',
  },
  'menu': {
    category: 'navigation',
    aliases: ['hamburger'],
    description: 'Menu/hamburger',
    lucide: 'menu',
    phosphor: 'list',
    tabler: 'menu-2',
    materialSymbols: 'menu',
    heroicons: 'bars-3',
  },
  'close': {
    category: 'navigation',
    aliases: ['cancel', 'dismiss', 'x'],
    description: 'Close modal/panel',
    lucide: 'x',
    phosphor: 'x',
    tabler: 'x',
    materialSymbols: 'close',
    heroicons: 'x-mark',
  },
  'back': {
    category: 'navigation',
    aliases: ['previous', 'arrow-left'],
    description: 'Go back',
    lucide: 'arrow-left',
    phosphor: 'arrow-left',
    tabler: 'arrow-left',
    materialSymbols: 'arrow_back',
    heroicons: 'arrow-left',
  },
  'next': {
    category: 'navigation',
    aliases: ['forward', 'arrow-right'],
    description: 'Go forward',
    lucide: 'arrow-right',
    phosphor: 'arrow-right',
    tabler: 'arrow-right',
    materialSymbols: 'arrow_forward',
    heroicons: 'arrow-right',
  },
  'up': {
    category: 'navigation',
    aliases: ['arrow-up'],
    description: 'Go up',
    lucide: 'arrow-up',
    phosphor: 'arrow-up',
    tabler: 'arrow-up',
    materialSymbols: 'arrow_upward',
    heroicons: 'arrow-up',
  },
  'down': {
    category: 'navigation',
    aliases: ['arrow-down'],
    description: 'Go down',
    lucide: 'arrow-down',
    phosphor: 'arrow-down',
    tabler: 'arrow-down',
    materialSymbols: 'arrow_downward',
    heroicons: 'arrow-down',
  },
  'external-link': {
    category: 'navigation',
    aliases: ['open-in-new'],
    description: 'Open external link',
    lucide: 'external-link',
    phosphor: 'arrow-square-out',
    tabler: 'external-link',
    materialSymbols: 'open_in_new',
    heroicons: 'arrow-top-right-on-square',
  },
  'chevron-right': {
    category: 'navigation',
    aliases: ['caret-right'],
    description: 'Chevron right',
    lucide: 'chevron-right',
    phosphor: 'caret-right',
    tabler: 'chevron-right',
    materialSymbols: 'chevron_right',
    heroicons: 'chevron-right',
  },
  'chevron-down': {
    category: 'navigation',
    aliases: ['caret-down', 'dropdown', 'expand'],
    description: 'Chevron down',
    lucide: 'chevron-down',
    phosphor: 'caret-down',
    tabler: 'chevron-down',
    materialSymbols: 'keyboard_arrow_down',
    heroicons: 'chevron-down',
  },
  'chevron-up': {
    category: 'navigation',
    aliases: ['caret-up', 'collapse'],
    description: 'Chevron up',
    lucide: 'chevron-up',
    phosphor: 'caret-up',
    tabler: 'chevron-up',
    materialSymbols: 'keyboard_arrow_up',
    heroicons: 'chevron-up',
  },
  'chevron-left': {
    category: 'navigation',
    aliases: ['caret-left'],
    description: 'Chevron left',
    lucide: 'chevron-left',
    phosphor: 'caret-left',
    tabler: 'chevron-left',
    materialSymbols: 'chevron_left',
    heroicons: 'chevron-left',
  },
  'more': {
    category: 'navigation',
    aliases: ['ellipsis', 'dots'],
    description: 'More options (horizontal)',
    lucide: 'ellipsis',
    phosphor: 'dots-three',
    tabler: 'dots',
    materialSymbols: 'more_horiz',
    heroicons: 'ellipsis-horizontal',
  },
  'more-options': {
    category: 'navigation',
    aliases: ['ellipsis-vertical', 'kebab'],
    description: 'More options (vertical)',
    lucide: 'ellipsis-vertical',
    phosphor: 'dots-three-vertical',
    tabler: 'dots-vertical',
    materialSymbols: 'more_vert',
    heroicons: 'ellipsis-vertical',
  },
  'sidebar': {
    category: 'navigation',
    aliases: ['panel', 'drawer'],
    description: 'Toggle sidebar',
    lucide: 'panel-left',
    phosphor: 'sidebar-simple',
    tabler: 'layout-sidebar',
    materialSymbols: 'view_sidebar',
    heroicons: 'bars-3-bottom-left',
  },
  'columns': {
    category: 'navigation',
    aliases: ['layout'],
    description: 'Column layout',
    lucide: 'columns-3',
    phosphor: 'columns',
    tabler: 'layout-columns',
    materialSymbols: 'view_column',
    heroicons: 'view-columns',
  },
  'anchor': {
    category: 'navigation',
    aliases: ['jump-to'],
    description: 'Anchor link',
    lucide: 'hash',
    phosphor: 'anchor-simple',
    tabler: 'anchor',
    materialSymbols: 'tag',
    heroicons: null,
  },
  'user': {
    category: 'user',
    aliases: ['person', 'profile'],
    description: 'Single user',
    lucide: 'user',
    phosphor: 'user',
    tabler: 'user',
    materialSymbols: 'person',
    heroicons: 'user',
  },
  'avatar': {
    category: 'user',
    aliases: ['account', 'user-circle'],
    description: 'User avatar',
    lucide: 'circle-user-round',
    phosphor: 'user-circle',
    tabler: 'user-circle',
    materialSymbols: 'account_circle',
    heroicons: 'user-circle',
  },
  'users': {
    category: 'user',
    aliases: ['team', 'people', 'group'],
    description: 'Multiple users/team',
    lucide: 'users',
    phosphor: 'users',
    tabler: 'users',
    materialSymbols: 'group',
    heroicons: 'user-group',
  },
  'add-user': {
    category: 'user',
    aliases: ['user-plus', 'invite'],
    description: 'Add user',
    lucide: 'user-plus',
    phosphor: 'user-plus',
    tabler: 'user-plus',
    materialSymbols: 'person_add',
    heroicons: 'user-plus',
  },
  'remove-user': {
    category: 'user',
    aliases: ['user-minus'],
    description: 'Remove user',
    lucide: 'user-minus',
    phosphor: 'user-minus',
    tabler: 'user-minus',
    materialSymbols: 'person_remove',
    heroicons: 'user-minus',
  },
  'assigned': {
    category: 'user',
    aliases: ['user-check'],
    description: 'Verified/assigned user',
    lucide: 'user-check',
    phosphor: 'user-check',
    tabler: 'user-check',
    materialSymbols: 'how_to_reg',
    heroicons: null,
  },
  'admin': {
    category: 'user',
    aliases: ['user-shield'],
    description: 'Admin user',
    lucide: 'shield-user',
    phosphor: 'shield-check',
    tabler: 'user-shield',
    materialSymbols: 'admin_panel_settings',
    heroicons: 'shield-check',
  },
  'user-settings': {
    category: 'user',
    aliases: ['user-gear', 'moderator'],
    description: 'User settings',
    lucide: 'user-cog',
    phosphor: 'user-gear',
    tabler: 'user-cog',
    materialSymbols: 'manage_accounts',
    heroicons: null,
  },
  'anonymous': {
    category: 'user',
    aliases: ['guest', 'incognito'],
    description: 'Anonymous user',
    lucide: 'venetian-mask',
    phosphor: 'detective',
    tabler: 'user-question',
    materialSymbols: null,
    heroicons: null,
  },
  'roles': {
    category: 'user',
    aliases: ['permissions'],
    description: 'User roles',
    lucide: 'user-cog',
    phosphor: 'identification-badge',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'login': {
    category: 'user',
    aliases: ['sign-in'],
    description: 'Log in',
    lucide: 'log-in',
    phosphor: 'sign-in',
    tabler: 'login',
    materialSymbols: 'login',
    heroicons: 'arrow-right-end-on-rectangle',
  },
  'logout': {
    category: 'user',
    aliases: ['sign-out', 'exit'],
    description: 'Log out',
    lucide: 'log-out',
    phosphor: 'sign-out',
    tabler: 'logout',
    materialSymbols: 'logout',
    heroicons: 'arrow-left-start-on-rectangle',
  },
  'fingerprint': {
    category: 'user',
    aliases: ['biometric'],
    description: 'Biometric authentication',
    lucide: 'fingerprint',
    phosphor: 'fingerprint',
    tabler: 'fingerprint',
    materialSymbols: 'fingerprint',
    heroicons: 'finger-print',
  },
  'add': {
    category: 'action',
    aliases: ['plus', 'create', 'new'],
    description: 'Add new item',
    lucide: 'plus',
    phosphor: 'plus',
    tabler: 'plus',
    materialSymbols: 'add',
    heroicons: 'plus',
  },
  'edit': {
    category: 'action',
    aliases: ['pencil', 'modify'],
    description: 'Edit/modify item',
    lucide: 'pencil',
    phosphor: 'pencil-simple',
    tabler: 'pencil',
    materialSymbols: 'edit',
    heroicons: 'pencil-square',
  },
  'delete': {
    category: 'action',
    aliases: ['trash', 'remove'],
    description: 'Delete/trash item',
    lucide: 'trash-2',
    phosphor: 'trash',
    tabler: 'trash',
    materialSymbols: 'delete',
    heroicons: 'trash',
  },
  'save': {
    category: 'action',
    aliases: ['floppy-disk'],
    description: 'Save changes',
    lucide: 'save',
    phosphor: 'floppy-disk',
    tabler: 'device-floppy',
    materialSymbols: 'save',
    heroicons: null,
  },
  'check': {
    category: 'action',
    aliases: ['done', 'confirm', 'complete'],
    description: 'Confirm/approve action',
    lucide: 'check',
    phosphor: 'check',
    tabler: 'check',
    materialSymbols: 'check',
    heroicons: 'check',
  },
  'refresh': {
    category: 'action',
    aliases: ['reload', 'sync', 'synchronize'],
    description: 'Refresh/reload/sync content',
    lucide: 'refresh-cw',
    phosphor: 'arrows-clockwise',
    tabler: 'refresh',
    materialSymbols: 'sync',
    heroicons: 'arrow-path',
  },
  'undo': {
    category: 'action',
    aliases: ['revert'],
    description: 'Undo last action',
    lucide: 'undo-2',
    phosphor: 'arrow-counter-clockwise',
    tabler: 'arrow-back-up',
    materialSymbols: 'undo',
    heroicons: 'arrow-uturn-left',
  },
  'redo': {
    category: 'action',
    aliases: [],
    description: 'Redo last action',
    lucide: 'redo-2',
    phosphor: 'arrow-clockwise',
    tabler: 'arrow-forward-up',
    materialSymbols: 'redo',
    heroicons: 'arrow-uturn-right',
  },
  'copy': {
    category: 'action',
    aliases: ['duplicate', 'clone'],
    description: 'Copy item',
    lucide: 'copy',
    phosphor: 'copy',
    tabler: 'copy',
    materialSymbols: 'content_copy',
    heroicons: 'document-duplicate',
  },
  'clipboard': {
    category: 'action',
    aliases: [],
    description: 'Clipboard',
    lucide: 'clipboard',
    phosphor: 'clipboard',
    tabler: 'clipboard',
    materialSymbols: 'assignment',
    heroicons: 'clipboard',
  },
  'copied': {
    category: 'action',
    aliases: ['clipboard-check'],
    description: 'Copied to clipboard',
    lucide: 'clipboard-check',
    phosphor: 'clipboard-text',
    tabler: 'clipboard-check',
    materialSymbols: 'assignment_turned_in',
    heroicons: 'clipboard-document-check',
  },
  'paste': {
    category: 'action',
    aliases: [],
    description: 'Paste from clipboard',
    lucide: 'clipboard-paste',
    phosphor: 'clipboard-text',
    tabler: 'clipboard-text',
    materialSymbols: 'content_paste',
    heroicons: 'clipboard-document',
  },
  'cut': {
    category: 'action',
    aliases: ['scissors'],
    description: 'Cut selection',
    lucide: 'scissors',
    phosphor: 'scissors',
    tabler: 'scissors',
    materialSymbols: 'content_cut',
    heroicons: 'scissors',
  },
  'move': {
    category: 'action',
    aliases: [],
    description: 'Move item',
    lucide: 'move',
    phosphor: 'arrows-out-cardinal',
    tabler: 'arrows-move',
    materialSymbols: 'open_with',
    heroicons: null,
  },
  'drag-handle': {
    category: 'action',
    aliases: ['grip', 'reorder'],
    description: 'Drag handle',
    lucide: 'grip-vertical',
    phosphor: 'dots-six-vertical',
    tabler: 'grip-vertical',
    materialSymbols: 'drag_indicator',
    heroicons: 'bars-2',
  },
  'upload': {
    category: 'action',
    aliases: [],
    description: 'Upload file',
    lucide: 'upload',
    phosphor: 'upload-simple',
    tabler: 'upload',
    materialSymbols: 'upload',
    heroicons: 'arrow-up-tray',
  },
  'download': {
    category: 'action',
    aliases: [],
    description: 'Download file',
    lucide: 'download',
    phosphor: 'download-simple',
    tabler: 'download',
    materialSymbols: 'download',
    heroicons: 'arrow-down-tray',
  },
  'import': {
    category: 'action',
    aliases: [],
    description: 'Import data',
    lucide: 'file-input',
    phosphor: 'sign-in',
    tabler: 'file-import',
    materialSymbols: null,
    heroicons: 'arrow-down-on-square',
  },
  'export': {
    category: 'action',
    aliases: [],
    description: 'Export data',
    lucide: 'file-output',
    phosphor: 'sign-out',
    tabler: 'file-export',
    materialSymbols: null,
    heroicons: 'arrow-up-on-square',
  },
  'print': {
    category: 'action',
    aliases: [],
    description: 'Print document',
    lucide: 'printer',
    phosphor: 'printer',
    tabler: 'printer',
    materialSymbols: 'print',
    heroicons: 'printer',
  },
  'share': {
    category: 'action',
    aliases: [],
    description: 'Share content',
    lucide: 'share-2',
    phosphor: 'share-network',
    tabler: 'share',
    materialSymbols: 'share',
    heroicons: 'share',
  },
  'send': {
    category: 'action',
    aliases: ['submit'],
    description: 'Send message',
    lucide: 'send',
    phosphor: 'paper-plane-tilt',
    tabler: 'send',
    materialSymbols: 'send',
    heroicons: 'paper-airplane',
  },
  'minus': {
    category: 'action',
    aliases: ['subtract', 'remove'],
    description: 'Minus/subtract',
    lucide: 'minus',
    phosphor: 'minus',
    tabler: 'minus',
    materialSymbols: 'remove',
    heroicons: null,
  },
  'file': {
    category: 'file',
    aliases: [],
    description: 'Generic file',
    lucide: 'file',
    phosphor: 'file',
    tabler: 'file',
    materialSymbols: 'draft',
    heroicons: 'document',
  },
  'document': {
    category: 'file',
    aliases: ['file-text'],
    description: 'Text document',
    lucide: 'file-text',
    phosphor: 'file-text',
    tabler: 'file-text',
    materialSymbols: 'description',
    heroicons: 'document-text',
  },
  'pdf': {
    category: 'file',
    aliases: ['file-pdf'],
    description: 'PDF document',
    lucide: 'file-text',
    phosphor: 'file-pdf',
    tabler: 'file-type-pdf',
    materialSymbols: 'picture_as_pdf',
    heroicons: null,
  },
  'folder': {
    category: 'file',
    aliases: ['directory'],
    description: 'Folder',
    lucide: 'folder',
    phosphor: 'folder',
    tabler: 'folder',
    materialSymbols: 'folder',
    heroicons: 'folder',
  },
  'new-folder': {
    category: 'file',
    aliases: ['folder-plus'],
    description: 'Create new folder',
    lucide: 'folder-plus',
    phosphor: 'folder-plus',
    tabler: 'folder-plus',
    materialSymbols: 'create_new_folder',
    heroicons: 'folder-plus',
  },
  'open-folder': {
    category: 'file',
    aliases: ['folder-open'],
    description: 'Open folder',
    lucide: 'folder-open',
    phosphor: 'folder-open',
    tabler: 'folder-open',
    materialSymbols: 'folder_open',
    heroicons: 'folder-open',
  },
  'archive': {
    category: 'file',
    aliases: ['box'],
    description: 'Archive item',
    lucide: 'archive',
    phosphor: 'archive',
    tabler: 'archive',
    materialSymbols: 'archive',
    heroicons: 'archive-box',
  },
  'zip': {
    category: 'file',
    aliases: ['compress'],
    description: 'Compressed file',
    lucide: 'file-archive',
    phosphor: 'file-zip',
    tabler: 'file-zip',
    materialSymbols: 'folder_zip',
    heroicons: null,
  },
  'attachment': {
    category: 'file',
    aliases: ['paperclip', 'attach'],
    description: 'File attachment',
    lucide: 'paperclip',
    phosphor: 'paperclip',
    tabler: 'paperclip',
    materialSymbols: 'attach_file',
    heroicons: 'paper-clip',
  },
  'link': {
    category: 'file',
    aliases: ['url'],
    description: 'Link/URL',
    lucide: 'link',
    phosphor: 'link',
    tabler: 'link',
    materialSymbols: 'link',
    heroicons: 'link',
  },
  'unlink': {
    category: 'file',
    aliases: ['disconnect'],
    description: 'Unlink/remove link',
    lucide: 'unlink',
    phosphor: 'link-break',
    tabler: 'unlink',
    materialSymbols: 'link_off',
    heroicons: 'link-slash',
  },
  'file-add': {
    category: 'file',
    aliases: ['file-plus', 'new-file'],
    description: 'Add file',
    lucide: 'file-plus',
    phosphor: 'file-plus',
    tabler: 'file-plus',
    materialSymbols: 'note_add',
    heroicons: null,
  },
  'file-remove': {
    category: 'file',
    aliases: ['file-minus', 'delete-file'],
    description: 'Remove file',
    lucide: 'file-minus',
    phosphor: 'file-minus',
    tabler: 'file-minus',
    materialSymbols: null,
    heroicons: null,
  },
  'image': {
    category: 'media',
    aliases: ['photo', 'picture'],
    description: 'Image/photo',
    lucide: 'image',
    phosphor: 'image',
    tabler: 'photo',
    materialSymbols: 'image',
    heroicons: 'photo',
  },
  'gallery': {
    category: 'media',
    aliases: ['images', 'photos'],
    description: 'Image gallery',
    lucide: 'images',
    phosphor: 'images-square',
    tabler: null,
    materialSymbols: 'photo_library',
    heroicons: null,
  },
  'video': {
    category: 'media',
    aliases: ['movie'],
    description: 'Video',
    lucide: 'video',
    phosphor: 'video-camera',
    tabler: 'video',
    materialSymbols: 'videocam',
    heroicons: 'video-camera',
  },
  'video-off': {
    category: 'media',
    aliases: ['video-disabled'],
    description: 'Video disabled',
    lucide: 'video-off',
    phosphor: 'video-camera-slash',
    tabler: 'video-off',
    materialSymbols: 'videocam_off',
    heroicons: null,
  },
  'camera': {
    category: 'media',
    aliases: [],
    description: 'Camera/photo capture',
    lucide: 'camera',
    phosphor: 'camera',
    tabler: 'camera',
    materialSymbols: 'photo_camera',
    heroicons: 'camera',
  },
  'camera-off': {
    category: 'media',
    aliases: ['camera-slash'],
    description: 'Camera off',
    lucide: 'camera-off',
    phosphor: 'camera-slash',
    tabler: 'camera-off',
    materialSymbols: 'no_photography',
    heroicons: null,
  },
  'volume': {
    category: 'media',
    aliases: ['audio', 'speaker'],
    description: 'Volume on',
    lucide: 'volume-2',
    phosphor: 'speaker-high',
    tabler: 'volume',
    materialSymbols: 'volume_up',
    heroicons: 'speaker-wave',
  },
  'volume-low': {
    category: 'media',
    aliases: [],
    description: 'Volume low',
    lucide: 'volume-1',
    phosphor: 'speaker-low',
    tabler: 'volume-2',
    materialSymbols: 'volume_down',
    heroicons: null,
  },
  'mute': {
    category: 'media',
    aliases: ['volume-off', 'volume-x'],
    description: 'Volume muted',
    lucide: 'volume-x',
    phosphor: 'speaker-x',
    tabler: 'volume-off',
    materialSymbols: 'volume_off',
    heroicons: 'speaker-x-mark',
  },
  'music': {
    category: 'media',
    aliases: ['audio', 'song'],
    description: 'Music/audio',
    lucide: 'music',
    phosphor: 'music-note',
    tabler: 'music',
    materialSymbols: 'music_note',
    heroicons: 'musical-note',
  },
  'microphone': {
    category: 'media',
    aliases: ['mic'],
    description: 'Microphone/record audio',
    lucide: 'mic',
    phosphor: 'microphone',
    tabler: 'microphone',
    materialSymbols: 'mic',
    heroicons: 'microphone',
  },
  'microphone-off': {
    category: 'media',
    aliases: ['mic-off', 'mute-mic'],
    description: 'Microphone muted',
    lucide: 'mic-off',
    phosphor: 'microphone-slash',
    tabler: 'microphone-off',
    materialSymbols: 'mic_off',
    heroicons: null,
  },
  'headphones': {
    category: 'media',
    aliases: ['headset'],
    description: 'Headphones/audio',
    lucide: 'headphones',
    phosphor: 'headphones',
    tabler: 'headphones',
    materialSymbols: 'headphones',
    heroicons: null,
  },
  'podcast': {
    category: 'media',
    aliases: [],
    description: 'Podcast',
    lucide: 'podcast',
    phosphor: null,
    tabler: null,
    materialSymbols: 'podcasts',
    heroicons: null,
  },
  'broadcast': {
    category: 'media',
    aliases: ['live', 'radio-tower'],
    description: 'Broadcast/live',
    lucide: 'radio-tower',
    phosphor: 'broadcast',
    tabler: 'live-photo',
    materialSymbols: 'cell_tower',
    heroicons: 'signal',
  },
  'crop': {
    category: 'media',
    aliases: ['trim'],
    description: 'Crop image',
    lucide: 'crop',
    phosphor: 'crop',
    tabler: 'crop',
    materialSymbols: 'crop',
    heroicons: null,
  },
  'rotate': {
    category: 'media',
    aliases: ['turn'],
    description: 'Rotate',
    lucide: 'rotate-cw',
    phosphor: 'arrows-counter-clockwise',
    tabler: 'rotate',
    materialSymbols: 'rotate_right',
    heroicons: null,
  },
  'play': {
    category: 'media-controls',
    aliases: [],
    description: 'Play media',
    lucide: 'play',
    phosphor: 'play',
    tabler: 'player-play',
    materialSymbols: 'play_arrow',
    heroicons: 'play',
  },
  'pause': {
    category: 'media-controls',
    aliases: [],
    description: 'Pause media',
    lucide: 'pause',
    phosphor: 'pause',
    tabler: 'player-pause',
    materialSymbols: 'pause',
    heroicons: 'pause',
  },
  'stop': {
    category: 'media-controls',
    aliases: [],
    description: 'Stop media',
    lucide: 'square',
    phosphor: 'stop',
    tabler: 'player-stop',
    materialSymbols: 'stop',
    heroicons: 'stop-circle',
  },
  'skip-next': {
    category: 'media-controls',
    aliases: ['forward-step', 'next-track'],
    description: 'Next track',
    lucide: 'skip-forward',
    phosphor: 'skip-forward',
    tabler: 'player-skip-forward',
    materialSymbols: 'skip_next',
    heroicons: 'forward',
  },
  'skip-previous': {
    category: 'media-controls',
    aliases: ['backward-step', 'previous-track'],
    description: 'Previous track',
    lucide: 'skip-back',
    phosphor: 'skip-back',
    tabler: 'player-skip-back',
    materialSymbols: 'skip_previous',
    heroicons: 'backward',
  },
  'fast-forward': {
    category: 'media-controls',
    aliases: [],
    description: 'Fast forward',
    lucide: 'fast-forward',
    phosphor: 'fast-forward',
    tabler: 'player-track-next',
    materialSymbols: 'fast_forward',
    heroicons: null,
  },
  'rewind': {
    category: 'media-controls',
    aliases: [],
    description: 'Rewind',
    lucide: 'rewind',
    phosphor: 'rewind',
    tabler: 'player-track-prev',
    materialSymbols: 'fast_rewind',
    heroicons: null,
  },
  'shuffle': {
    category: 'media-controls',
    aliases: ['random'],
    description: 'Shuffle/random',
    lucide: 'shuffle',
    phosphor: 'shuffle',
    tabler: 'arrows-shuffle',
    materialSymbols: 'shuffle',
    heroicons: null,
  },
  'repeat': {
    category: 'media-controls',
    aliases: ['loop'],
    description: 'Repeat/loop',
    lucide: 'repeat',
    phosphor: 'repeat',
    tabler: 'repeat',
    materialSymbols: 'repeat',
    heroicons: 'arrow-path',
  },
  'record': {
    category: 'media-controls',
    aliases: [],
    description: 'Record',
    lucide: 'circle',
    phosphor: 'record',
    tabler: 'player-record',
    materialSymbols: 'fiber_manual_record',
    heroicons: null,
  },
  'filter': {
    category: 'data',
    aliases: ['funnel'],
    description: 'Filter results',
    lucide: 'filter',
    phosphor: 'funnel',
    tabler: 'filter',
    materialSymbols: 'filter_list',
    heroicons: 'funnel',
  },
  'sort': {
    category: 'data',
    aliases: [],
    description: 'Sort items',
    lucide: 'arrow-up-down',
    phosphor: 'sort-ascending',
    tabler: 'sort-ascending',
    materialSymbols: 'sort',
    heroicons: 'bars-arrow-down',
  },
  'list': {
    category: 'data',
    aliases: ['list-view'],
    description: 'List view',
    lucide: 'list',
    phosphor: 'list-dashes',
    tabler: 'list',
    materialSymbols: 'list',
    heroicons: 'list-bullet',
  },
  'table': {
    category: 'data',
    aliases: ['table-view'],
    description: 'Table/spreadsheet',
    lucide: 'table',
    phosphor: 'table',
    tabler: 'table',
    materialSymbols: 'table',
    heroicons: 'table-cells',
  },
  'grid': {
    category: 'data',
    aliases: ['grid-view', 'card-view'],
    description: 'Grid view',
    lucide: 'layout-grid',
    phosphor: 'squares-four',
    tabler: 'grid-dots',
    materialSymbols: 'grid_view',
    heroicons: 'squares-2x2',
  },
  'chart-bar': {
    category: 'data',
    aliases: ['bar-chart', 'chart'],
    description: 'Bar chart',
    lucide: 'chart-bar',
    phosphor: 'chart-bar',
    tabler: 'chart-bar',
    materialSymbols: 'bar_chart',
    heroicons: 'chart-bar',
  },
  'chart-line': {
    category: 'data',
    aliases: ['line-chart', 'analytics', 'trends'],
    description: 'Line chart',
    lucide: 'chart-line',
    phosphor: 'chart-line-up',
    tabler: 'chart-line',
    materialSymbols: 'show_chart',
    heroicons: null,
  },
  'chart-pie': {
    category: 'data',
    aliases: ['pie-chart', 'statistics'],
    description: 'Pie chart',
    lucide: 'chart-pie',
    phosphor: 'chart-pie-slice',
    tabler: 'chart-pie',
    materialSymbols: 'pie_chart',
    heroicons: 'chart-pie',
  },
  'view': {
    category: 'data',
    aliases: ['show', 'visible', 'eye'],
    description: 'Show/visible',
    lucide: 'eye',
    phosphor: 'eye',
    tabler: 'eye',
    materialSymbols: 'visibility',
    heroicons: 'eye',
  },
  'hide': {
    category: 'data',
    aliases: ['invisible', 'eye-off'],
    description: 'Hide/invisible',
    lucide: 'eye-off',
    phosphor: 'eye-slash',
    tabler: 'eye-off',
    materialSymbols: 'visibility_off',
    heroicons: 'eye-slash',
  },
  'search': {
    category: 'data',
    aliases: ['magnifying-glass', 'find'],
    description: 'Search content',
    lucide: 'search',
    phosphor: 'magnifying-glass',
    tabler: 'search',
    materialSymbols: 'search',
    heroicons: 'magnifying-glass',
  },
  'zoom-in': {
    category: 'data',
    aliases: [],
    description: 'Zoom in',
    lucide: 'zoom-in',
    phosphor: 'magnifying-glass-plus',
    tabler: 'zoom-in',
    materialSymbols: 'zoom_in',
    heroicons: 'magnifying-glass-plus',
  },
  'zoom-out': {
    category: 'data',
    aliases: [],
    description: 'Zoom out',
    lucide: 'zoom-out',
    phosphor: 'magnifying-glass-minus',
    tabler: 'zoom-out',
    materialSymbols: 'zoom_out',
    heroicons: 'magnifying-glass-minus',
  },
  'fullscreen': {
    category: 'data',
    aliases: ['maximize', 'expand'],
    description: 'Maximize/fullscreen',
    lucide: 'maximize',
    phosphor: 'arrows-out',
    tabler: 'arrows-maximize',
    materialSymbols: 'fullscreen',
    heroicons: 'arrows-pointing-out',
  },
  'exit-fullscreen': {
    category: 'data',
    aliases: ['minimize'],
    description: 'Minimize/exit fullscreen',
    lucide: 'minimize',
    phosphor: 'arrows-in',
    tabler: 'arrows-minimize',
    materialSymbols: 'fullscreen_exit',
    heroicons: 'arrows-pointing-in',
  },
  'board': {
    category: 'data',
    aliases: ['kanban', 'board-view'],
    description: 'Kanban board',
    lucide: 'kanban',
    phosphor: 'kanban',
    tabler: 'layout-kanban',
    materialSymbols: 'view_kanban',
    heroicons: 'view-columns',
  },
  'activity': {
    category: 'data',
    aliases: ['pulse'],
    description: 'Activity/pulse',
    lucide: 'activity',
    phosphor: 'pulse',
    tabler: 'activity-heartbeat',
    materialSymbols: 'monitoring',
    heroicons: null,
  },
  'calendar': {
    category: 'time',
    aliases: ['date'],
    description: 'Calendar/date',
    lucide: 'calendar',
    phosphor: 'calendar-blank',
    tabler: 'calendar',
    materialSymbols: 'calendar_today',
    heroicons: 'calendar',
  },
  'schedule': {
    category: 'time',
    aliases: ['events', 'calendar-days'],
    description: 'Schedule/events',
    lucide: 'calendar-days',
    phosphor: 'calendar-dots',
    tabler: 'calendar-event',
    materialSymbols: 'calendar_month',
    heroicons: 'calendar-days',
  },
  'scheduled': {
    category: 'time',
    aliases: ['due-date', 'calendar-check'],
    description: 'Scheduled/due date',
    lucide: 'calendar-check',
    phosphor: 'calendar-check',
    tabler: 'calendar-check',
    materialSymbols: 'event_available',
    heroicons: 'calendar-date-range',
  },
  'overdue': {
    category: 'time',
    aliases: ['deadline', 'calendar-x'],
    description: 'Overdue/deadline',
    lucide: 'calendar-x',
    phosphor: 'calendar-x',
    tabler: 'calendar-off',
    materialSymbols: 'event_busy',
    heroicons: null,
  },
  'time': {
    category: 'time',
    aliases: ['clock'],
    description: 'Clock/time',
    lucide: 'clock',
    phosphor: 'clock',
    tabler: 'clock',
    materialSymbols: 'schedule',
    heroicons: 'clock',
  },
  'timer': {
    category: 'time',
    aliases: ['countdown', 'stopwatch'],
    description: 'Timer/countdown',
    lucide: 'timer',
    phosphor: 'timer',
    tabler: 'hourglass',
    materialSymbols: 'timer',
    heroicons: null,
  },
  'watch': {
    category: 'time',
    aliases: ['smartwatch'],
    description: 'Smart watch',
    lucide: 'watch',
    phosphor: 'watch',
    tabler: 'device-watch',
    materialSymbols: 'watch',
    heroicons: null,
  },
  'success': {
    category: 'status',
    aliases: ['check-circle', 'complete'],
    description: 'Success indicator',
    lucide: 'circle-check',
    phosphor: 'check-circle',
    tabler: 'circle-check',
    materialSymbols: 'check_circle',
    heroicons: 'check-circle',
  },
  'error': {
    category: 'status',
    aliases: ['x-circle', 'failed'],
    description: 'Error alert',
    lucide: 'circle-x',
    phosphor: 'x-circle',
    tabler: 'circle-x',
    materialSymbols: 'error',
    heroicons: 'x-circle',
  },
  'warning': {
    category: 'status',
    aliases: ['alert', 'caution'],
    description: 'Warning alert',
    lucide: 'triangle-alert',
    phosphor: 'warning',
    tabler: 'alert-triangle',
    materialSymbols: 'warning',
    heroicons: 'exclamation-triangle',
  },
  'info': {
    category: 'status',
    aliases: ['information'],
    description: 'Information',
    lucide: 'info',
    phosphor: 'info',
    tabler: 'info-circle',
    materialSymbols: 'info',
    heroicons: 'information-circle',
  },
  'help': {
    category: 'status',
    aliases: ['question', 'faq'],
    description: 'Help/question',
    lucide: 'circle-help',
    phosphor: 'question',
    tabler: 'help-circle',
    materialSymbols: 'help',
    heroicons: 'question-mark-circle',
  },
  'loading': {
    category: 'status',
    aliases: ['spinner'],
    description: 'Loading spinner',
    lucide: 'loader-2',
    phosphor: 'spinner-gap',
    tabler: 'loader-2',
    materialSymbols: 'progress_activity',
    heroicons: 'arrow-path',
  },
  'filled-circle': {
    category: 'status',
    aliases: ['active', 'selected', 'radio', 'radio-selected', 'circle-dot', 'disc', 'dot'],
    description: 'Filled circle / active state',
    lucide: 'circle-dot',
    phosphor: 'circle',
    tabler: 'circle-dot',
    materialSymbols: 'radio_button_checked',
    heroicons: null,
  },
  'empty-circle': {
    category: 'status',
    aliases: ['inactive', 'unselected', 'radio-empty', 'radio-unselected', 'circle'],
    description: 'Empty circle / inactive state',
    lucide: 'circle',
    phosphor: 'circle',
    tabler: 'circle',
    materialSymbols: 'radio_button_unchecked',
    heroicons: null,
  },
  'verified': {
    category: 'status',
    aliases: ['badge-check'],
    description: 'Verified',
    lucide: 'badge-check',
    phosphor: 'seal-check',
    tabler: 'rosette-discount-check',
    materialSymbols: 'verified',
    heroicons: 'check-badge',
  },
  'smile': {
    category: 'status',
    aliases: ['happy', 'satisfied'],
    description: 'Emoji/mood',
    lucide: 'smile',
    phosphor: 'smiley',
    tabler: 'mood-happy',
    materialSymbols: 'sentiment_satisfied',
    heroicons: 'face-smile',
  },
  'frown': {
    category: 'status',
    aliases: ['sad', 'dissatisfied'],
    description: 'Sad emoji',
    lucide: 'frown',
    phosphor: 'smiley-sad',
    tabler: 'mood-sad',
    materialSymbols: 'sentiment_dissatisfied',
    heroicons: 'face-frown',
  },
  'checkbox': {
    category: 'form',
    aliases: ['square-check', 'checked'],
    description: 'Checkbox checked',
    lucide: 'square-check',
    phosphor: 'check-square',
    tabler: 'square-check',
    materialSymbols: 'check_box',
    heroicons: null,
  },
  'checkbox-empty': {
    category: 'form',
    aliases: ['unchecked', 'square'],
    description: 'Checkbox unchecked',
    lucide: 'square',
    phosphor: 'square',
    tabler: 'square',
    materialSymbols: 'check_box_outline_blank',
    heroicons: null,
  },
  'toggle': {
    category: 'form',
    aliases: ['switch', 'toggle-on'],
    description: 'Toggle switch on',
    lucide: 'toggle-right',
    phosphor: 'toggle-right',
    tabler: 'toggle-right',
    materialSymbols: 'toggle_on',
    heroicons: null,
  },
  'toggle-off': {
    category: 'form',
    aliases: ['switch-off'],
    description: 'Toggle switch off',
    lucide: 'toggle-left',
    phosphor: 'toggle-left',
    tabler: 'toggle-left',
    materialSymbols: 'toggle_off',
    heroicons: null,
  },
  'like': {
    category: 'social',
    aliases: ['favorite', 'heart'],
    description: 'Heart/like',
    lucide: 'heart',
    phosphor: 'heart',
    tabler: 'heart',
    materialSymbols: 'favorite',
    heroicons: 'heart',
  },
  'unlike': {
    category: 'social',
    aliases: ['heart-crack'],
    description: 'Unlike',
    lucide: 'heart-off',
    phosphor: 'heart-break',
    tabler: 'heart-broken',
    materialSymbols: 'heart_broken',
    heroicons: null,
  },
  'star': {
    category: 'social',
    aliases: ['favorite', 'rating'],
    description: 'Star/favorite',
    lucide: 'star',
    phosphor: 'star',
    tabler: 'star',
    materialSymbols: 'star',
    heroicons: 'star',
  },
  'bookmark': {
    category: 'social',
    aliases: ['save'],
    description: 'Bookmark/save for later',
    lucide: 'bookmark',
    phosphor: 'bookmark-simple',
    tabler: 'bookmark',
    materialSymbols: 'bookmark',
    heroicons: 'bookmark',
  },
  'thumbs-up': {
    category: 'social',
    aliases: ['upvote'],
    description: 'Thumbs up',
    lucide: 'thumbs-up',
    phosphor: 'thumbs-up',
    tabler: 'thumb-up',
    materialSymbols: 'thumb_up',
    heroicons: 'hand-thumb-up',
  },
  'thumbs-down': {
    category: 'social',
    aliases: ['dislike', 'downvote'],
    description: 'Thumbs down',
    lucide: 'thumbs-down',
    phosphor: 'thumbs-down',
    tabler: 'thumb-down',
    materialSymbols: 'thumb_down',
    heroicons: 'hand-thumb-down',
  },
  'reply': {
    category: 'social',
    aliases: [],
    description: 'Reply',
    lucide: 'reply',
    phosphor: 'arrow-bend-up-left',
    tabler: 'arrow-back-up',
    materialSymbols: 'reply',
    heroicons: 'arrow-uturn-left',
  },
  'comment': {
    category: 'social',
    aliases: ['message'],
    description: 'Comment/reply',
    lucide: 'message-square',
    phosphor: 'chat-circle',
    tabler: 'message',
    materialSymbols: 'comment',
    heroicons: 'chat-bubble-left',
  },
  'comments': {
    category: 'social',
    aliases: ['discussion'],
    description: 'Multiple comments',
    lucide: 'messages-square',
    phosphor: 'chats-circle',
    tabler: 'messages',
    materialSymbols: 'forum',
    heroicons: 'chat-bubble-left-right',
  },
  'typing': {
    category: 'social',
    aliases: ['message-dots'],
    description: 'Typing indicator',
    lucide: 'message-square-more',
    phosphor: 'chat-circle-dots',
    tabler: 'message-dots',
    materialSymbols: 'more_horiz',
    heroicons: 'chat-bubble-left-ellipsis',
  },
  'mention': {
    category: 'social',
    aliases: ['at'],
    description: 'At symbol/mention',
    lucide: 'at-sign',
    phosphor: 'at',
    tabler: 'at',
    materialSymbols: 'alternate_email',
    heroicons: 'at-symbol',
  },
  'block': {
    category: 'social',
    aliases: ['ban', 'restricted'],
    description: 'Block/ban',
    lucide: 'ban',
    phosphor: 'prohibit',
    tabler: 'ban',
    materialSymbols: 'block',
    heroicons: 'no-symbol',
  },
  'flag': {
    category: 'social',
    aliases: ['report'],
    description: 'Flag/report',
    lucide: 'flag',
    phosphor: 'flag',
    tabler: 'flag',
    materialSymbols: 'flag',
    heroicons: 'flag',
  },
  'pin': {
    category: 'social',
    aliases: ['thumbtack', 'pinned'],
    description: 'Pin item (thumbtack)',
    lucide: 'pin',
    phosphor: 'push-pin',
    tabler: 'pinned',
    materialSymbols: 'keep',
    heroicons: null,
  },
  'award': {
    category: 'gamification',
    aliases: ['badge', 'achievement'],
    description: 'Badge/award',
    lucide: 'award',
    phosphor: 'medal',
    tabler: 'award',
    materialSymbols: 'military_tech',
    heroicons: null,
  },
  'trophy': {
    category: 'gamification',
    aliases: ['winner'],
    description: 'Achievement/winner',
    lucide: 'trophy',
    phosphor: 'trophy',
    tabler: 'trophy',
    materialSymbols: 'trophy',
    heroicons: 'trophy',
  },
  'gift': {
    category: 'gamification',
    aliases: ['reward', 'present'],
    description: 'Gift/reward',
    lucide: 'gift',
    phosphor: 'gift',
    tabler: 'gift',
    materialSymbols: 'redeem',
    heroicons: 'gift',
  },
  'target': {
    category: 'gamification',
    aliases: ['goal'],
    description: 'Goal/target',
    lucide: 'target',
    phosphor: 'target',
    tabler: 'target',
    materialSymbols: 'target',
    heroicons: null,
  },
  'notifications': {
    category: 'communication',
    aliases: ['bell', 'alerts'],
    description: 'Notifications/alerts',
    lucide: 'bell',
    phosphor: 'bell',
    tabler: null,
    materialSymbols: 'notifications',
    heroicons: 'bell',
  },
  'email': {
    category: 'communication',
    aliases: ['mail', 'envelope'],
    description: 'Email',
    lucide: 'mail',
    phosphor: 'envelope-simple',
    tabler: null,
    materialSymbols: 'mail',
    heroicons: 'envelope',
  },
  'inbox': {
    category: 'communication',
    aliases: [],
    description: 'Inbox',
    lucide: 'inbox',
    phosphor: 'tray',
    tabler: null,
    materialSymbols: 'inbox',
    heroicons: 'inbox',
  },
  'phone': {
    category: 'communication',
    aliases: ['call'],
    description: 'Phone call',
    lucide: 'phone',
    phosphor: 'phone',
    tabler: null,
    materialSymbols: 'call',
    heroicons: 'phone',
  },
  'contacts': {
    category: 'communication',
    aliases: ['address-book'],
    description: 'Address book',
    lucide: 'contact',
    phosphor: 'address-book',
    tabler: null,
    materialSymbols: 'contacts',
    heroicons: 'identification',
  },
  'notifications-off': {
    category: 'communication',
    aliases: ['bell-off', 'alerts-off'],
    description: 'Notifications disabled',
    lucide: 'bell-off',
    phosphor: 'bell-slash',
    tabler: 'bell-off',
    materialSymbols: 'notifications_off',
    heroicons: null,
  },
  'at': {
    category: 'communication',
    aliases: ['mention', 'at-sign'],
    description: 'At symbol/mention',
    lucide: 'at-sign',
    phosphor: 'at',
    tabler: 'at',
    materialSymbols: 'alternate_email',
    heroicons: 'at-symbol',
  },
  'chat': {
    category: 'communication',
    aliases: ['message-square', 'im', 'direct-message'],
    description: 'Chat/instant message',
    lucide: 'message-square-text',
    phosphor: 'chat',
    tabler: 'message',
    materialSymbols: 'chat',
    heroicons: 'chat-bubble-left-right',
  },
  'lock': {
    category: 'security',
    aliases: ['locked', 'secure'],
    description: 'Locked/secure',
    lucide: 'lock',
    phosphor: 'lock',
    tabler: null,
    materialSymbols: 'lock',
    heroicons: 'lock-closed',
  },
  'unlock': {
    category: 'security',
    aliases: ['unlocked'],
    description: 'Unlocked',
    lucide: 'lock-open',
    phosphor: 'lock-open',
    tabler: null,
    materialSymbols: 'lock_open',
    heroicons: 'lock-open',
  },
  'security': {
    category: 'security',
    aliases: ['shield'],
    description: 'Security/protected',
    lucide: 'shield',
    phosphor: 'shield',
    tabler: null,
    materialSymbols: 'shield',
    heroicons: 'shield-exclamation',
  },
  'secure': {
    category: 'security',
    aliases: ['shield-check', 'protected'],
    description: 'Secure/verified',
    lucide: 'shield-check',
    phosphor: 'shield-check',
    tabler: null,
    materialSymbols: 'verified_user',
    heroicons: 'shield-check',
  },
  'key': {
    category: 'security',
    aliases: ['password', 'access'],
    description: 'Key/access',
    lucide: 'key-round',
    phosphor: 'key',
    tabler: null,
    materialSymbols: 'vpn_key',
    heroicons: 'key',
  },
  'security-off': {
    category: 'security',
    aliases: ['shield-off', 'unprotected'],
    description: 'Security disabled',
    lucide: 'shield-off',
    phosphor: 'shield-slash',
    tabler: 'shield-off',
    materialSymbols: null,
    heroicons: null,
  },
  'settings': {
    category: 'settings',
    aliases: ['gear', 'cog', 'preferences'],
    description: 'Settings/preferences',
    lucide: 'settings',
    phosphor: 'gear',
    tabler: null,
    materialSymbols: 'settings',
    heroicons: 'cog-6-tooth',
  },
  'sliders': {
    category: 'settings',
    aliases: ['adjustments'],
    description: 'Adjustments/settings',
    lucide: 'sliders-horizontal',
    phosphor: 'sliders',
    tabler: null,
    materialSymbols: 'tune',
    heroicons: 'adjustments-horizontal',
  },
  'theme': {
    category: 'settings',
    aliases: ['palette', 'appearance'],
    description: 'Theme/colors',
    lucide: 'palette',
    phosphor: 'palette',
    tabler: null,
    materialSymbols: 'palette',
    heroicons: 'swatch',
  },
  'light-mode': {
    category: 'settings',
    aliases: ['sun'],
    description: 'Light mode',
    lucide: 'sun',
    phosphor: 'sun',
    tabler: null,
    materialSymbols: 'light_mode',
    heroicons: 'sun',
  },
  'dark-mode': {
    category: 'settings',
    aliases: ['moon'],
    description: 'Dark mode',
    lucide: 'moon',
    phosphor: 'moon',
    tabler: null,
    materialSymbols: 'dark_mode',
    heroicons: 'moon',
  },
  'accessibility': {
    category: 'settings',
    aliases: [],
    description: 'Accessibility',
    lucide: 'accessibility',
    phosphor: 'wheelchair',
    tabler: null,
    materialSymbols: 'accessibility_new',
    heroicons: null,
  },
  'plugin': {
    category: 'settings',
    aliases: ['extension', 'puzzle'],
    description: 'Plugin/extension',
    lucide: 'puzzle',
    phosphor: 'puzzle-piece',
    tabler: null,
    materialSymbols: 'extension',
    heroicons: 'puzzle-piece',
  },
  'webhook': {
    category: 'settings',
    aliases: ['api'],
    description: 'API/endpoint',
    lucide: 'webhook',
    phosphor: 'webhooks-logo',
    tabler: null,
    materialSymbols: 'webhook',
    heroicons: null,
  },
  'globe': {
    category: 'settings',
    aliases: ['world', 'public', 'language'],
    description: 'Globe/world',
    lucide: 'globe',
    phosphor: 'globe',
    tabler: null,
    materialSymbols: 'language',
    heroicons: 'globe-alt',
  },
  'cart': {
    category: 'commerce',
    aliases: ['shopping-cart'],
    description: 'Shopping cart',
    lucide: 'shopping-cart',
    phosphor: 'shopping-cart',
    tabler: 'shopping-cart',
    materialSymbols: 'shopping_cart',
    heroicons: 'shopping-cart',
  },
  'add-to-cart': {
    category: 'commerce',
    aliases: ['cart-plus'],
    description: 'Add to cart',
    lucide: 'shopping-basket',
    phosphor: 'shopping-cart-simple',
    tabler: 'shopping-cart-plus',
    materialSymbols: 'add_shopping_cart',
    heroicons: null,
  },
  'payment': {
    category: 'commerce',
    aliases: ['credit-card', 'billing'],
    description: 'Credit card/payment',
    lucide: 'credit-card',
    phosphor: 'credit-card',
    tabler: 'credit-card',
    materialSymbols: 'credit_card',
    heroicons: 'credit-card',
  },
  'wallet': {
    category: 'commerce',
    aliases: [],
    description: 'Wallet',
    lucide: 'wallet',
    phosphor: 'wallet',
    tabler: 'wallet',
    materialSymbols: 'account_balance_wallet',
    heroicons: 'wallet',
  },
  'money': {
    category: 'commerce',
    aliases: ['dollar', 'currency'],
    description: 'Money/currency',
    lucide: 'circle-dollar-sign',
    phosphor: 'currency-dollar',
    tabler: 'coins',
    materialSymbols: 'payments',
    heroicons: 'banknotes',
  },
  'tag': {
    category: 'commerce',
    aliases: ['label', 'price'],
    description: 'Price tag/label',
    lucide: 'tag',
    phosphor: 'tag',
    tabler: 'tag',
    materialSymbols: 'sell',
    heroicons: 'tag',
  },
  'tags': {
    category: 'commerce',
    aliases: ['labels'],
    description: 'Multiple tags',
    lucide: 'tags',
    phosphor: 'tag',
    tabler: 'tags',
    materialSymbols: 'sell',
    heroicons: null,
  },
  'discount': {
    category: 'commerce',
    aliases: ['percent'],
    description: 'Discount/percentage',
    lucide: 'badge-percent',
    phosphor: 'percent',
    tabler: 'percentage',
    materialSymbols: 'percent',
    heroicons: 'percent-badge',
  },
  'coupon': {
    category: 'commerce',
    aliases: ['ticket'],
    description: 'Coupon/ticket',
    lucide: 'ticket-percent',
    phosphor: 'ticket',
    tabler: 'ticket',
    materialSymbols: 'confirmation_number',
    heroicons: 'ticket',
  },
  'package': {
    category: 'commerce',
    aliases: ['box', 'order'],
    description: 'Package/module',
    lucide: 'package',
    phosphor: 'package',
    tabler: 'package',
    materialSymbols: 'package',
    heroicons: 'cube',
  },
  'shipping': {
    category: 'commerce',
    aliases: ['truck'],
    description: 'Shipping/delivery',
    lucide: 'truck',
    phosphor: 'truck',
    tabler: 'truck',
    materialSymbols: 'local_shipping',
    heroicons: 'truck',
  },
  'delivery': {
    category: 'commerce',
    aliases: ['express'],
    description: 'Fast delivery',
    lucide: 'package-open',
    phosphor: 'truck',
    tabler: 'truck-delivery',
    materialSymbols: 'local_shipping',
    heroicons: 'truck',
  },
  'return': {
    category: 'commerce',
    aliases: [],
    description: 'Return/refund',
    lucide: 'undo-2',
    phosphor: 'arrow-u-up-left',
    tabler: 'receipt-refund',
    materialSymbols: 'assignment_return',
    heroicons: 'receipt-refund',
  },
  'receipt': {
    category: 'commerce',
    aliases: [],
    description: 'Receipt/invoice',
    lucide: 'receipt',
    phosphor: 'receipt',
    tabler: 'receipt',
    materialSymbols: 'receipt',
    heroicons: 'receipt-percent',
  },
  'invoice': {
    category: 'commerce',
    aliases: [],
    description: 'Invoice',
    lucide: 'receipt-text',
    phosphor: 'invoice',
    tabler: 'file-invoice',
    materialSymbols: 'receipt_long',
    heroicons: 'document-text',
  },
  'store': {
    category: 'commerce',
    aliases: ['shop'],
    description: 'Store/shop',
    lucide: 'store',
    phosphor: 'storefront',
    tabler: 'building-store',
    materialSymbols: 'storefront',
    heroicons: 'building-storefront',
  },
  'shopping-bag': {
    category: 'commerce',
    aliases: ['bag'],
    description: 'Shopping bag',
    lucide: 'shopping-bag',
    phosphor: 'bag',
    tabler: 'shopping-bag',
    materialSymbols: 'shopping_bag',
    heroicons: 'shopping-bag',
  },
  'bold': {
    category: 'text',
    aliases: [],
    description: 'Bold text',
    lucide: 'bold',
    phosphor: 'text-b',
    tabler: 'bold',
    materialSymbols: 'format_bold',
    heroicons: 'bold',
  },
  'italic': {
    category: 'text',
    aliases: [],
    description: 'Italic text',
    lucide: 'italic',
    phosphor: 'text-italic',
    tabler: 'italic',
    materialSymbols: 'format_italic',
    heroicons: 'italic',
  },
  'underline': {
    category: 'text',
    aliases: [],
    description: 'Underline text',
    lucide: 'underline',
    phosphor: 'text-underline',
    tabler: 'underline',
    materialSymbols: 'format_underlined',
    heroicons: 'underline',
  },
  'strikethrough': {
    category: 'text',
    aliases: [],
    description: 'Strikethrough text',
    lucide: 'strikethrough',
    phosphor: 'text-strikethrough',
    tabler: 'strikethrough',
    materialSymbols: 'format_strikethrough',
    heroicons: 'strikethrough',
  },
  'code': {
    category: 'text',
    aliases: [],
    description: 'Code snippet',
    lucide: 'code',
    phosphor: 'code',
    tabler: 'code',
    materialSymbols: 'code',
    heroicons: 'code-bracket',
  },
  'quote': {
    category: 'text',
    aliases: ['blockquote'],
    description: 'Blockquote',
    lucide: 'text-quote',
    phosphor: 'quotes',
    tabler: 'blockquote',
    materialSymbols: 'format_quote',
    heroicons: null,
  },
  'heading': {
    category: 'text',
    aliases: ['h1', 'title'],
    description: 'Heading/title',
    lucide: 'heading',
    phosphor: 'text-h',
    tabler: 'heading',
    materialSymbols: 'title',
    heroicons: 'h1',
  },
  'paragraph': {
    category: 'text',
    aliases: [],
    description: 'Paragraph',
    lucide: 'pilcrow',
    phosphor: 'paragraph',
    tabler: 'pilcrow',
    materialSymbols: 'notes',
    heroicons: null,
  },
  'bullet-list': {
    category: 'text',
    aliases: ['list-ul', 'unordered-list'],
    description: 'Bullet list',
    lucide: 'list',
    phosphor: 'list-bullets',
    tabler: 'list',
    materialSymbols: 'format_list_bulleted',
    heroicons: 'list-bullet',
  },
  'numbered-list': {
    category: 'text',
    aliases: ['list-ol', 'ordered-list'],
    description: 'Numbered list',
    lucide: 'list-ordered',
    phosphor: 'list-numbers',
    tabler: 'list-numbers',
    materialSymbols: 'format_list_numbered',
    heroicons: 'numbered-list',
  },
  'checklist': {
    category: 'text',
    aliases: ['todo-list'],
    description: 'Checklist',
    lucide: 'list-checks',
    phosphor: 'list-checks',
    tabler: 'list-check',
    materialSymbols: 'checklist',
    heroicons: null,
  },
  'indent': {
    category: 'text',
    aliases: [],
    description: 'Indent text',
    lucide: 'indent-increase',
    phosphor: 'text-indent',
    tabler: 'indent-increase',
    materialSymbols: 'format_indent_increase',
    heroicons: null,
  },
  'outdent': {
    category: 'text',
    aliases: [],
    description: 'Outdent text',
    lucide: 'indent-decrease',
    phosphor: 'text-outdent',
    tabler: 'indent-decrease',
    materialSymbols: 'format_indent_decrease',
    heroicons: null,
  },
  'align-left': {
    category: 'text',
    aliases: [],
    description: 'Align left',
    lucide: 'align-left',
    phosphor: 'text-align-left',
    tabler: 'align-left',
    materialSymbols: 'format_align_left',
    heroicons: null,
  },
  'align-center': {
    category: 'text',
    aliases: [],
    description: 'Align center',
    lucide: 'align-center',
    phosphor: 'text-align-center',
    tabler: 'align-center',
    materialSymbols: 'format_align_center',
    heroicons: null,
  },
  'align-right': {
    category: 'text',
    aliases: [],
    description: 'Align right',
    lucide: 'align-right',
    phosphor: 'text-align-right',
    tabler: 'align-right',
    materialSymbols: 'format_align_right',
    heroicons: null,
  },
  'justify': {
    category: 'text',
    aliases: ['align-justify'],
    description: 'Justify text',
    lucide: 'align-justify',
    phosphor: 'text-align-justify',
    tabler: 'align-justified',
    materialSymbols: 'format_align_justify',
    heroicons: null,
  },
  'emoji': {
    category: 'text',
    aliases: ['smiley'],
    description: 'Emoji picker',
    lucide: 'smile-plus',
    phosphor: 'smiley-sticker',
    tabler: 'mood-smile',
    materialSymbols: 'mood',
    heroicons: 'face-smile',
  },
  'type': {
    category: 'text',
    aliases: ['typography', 'font'],
    description: 'Typography/font',
    lucide: 'type',
    phosphor: 'text-t',
    tabler: 'typography',
    materialSymbols: 'text_fields',
    heroicons: null,
  },
  'brush': {
    category: 'editing',
    aliases: ['paint'],
    description: 'Brush/paint',
    lucide: 'paintbrush',
    phosphor: 'paint-brush',
    tabler: 'brush',
    materialSymbols: 'brush',
    heroicons: 'paint-brush',
  },
  'pen': {
    category: 'editing',
    aliases: ['draw'],
    description: 'Pen/draw',
    lucide: 'pen',
    phosphor: 'pen-nib',
    tabler: 'pencil',
    materialSymbols: 'edit',
    heroicons: 'pencil',
  },
  'color': {
    category: 'editing',
    aliases: ['eyedropper', 'color-picker'],
    description: 'Color picker',
    lucide: 'pipette',
    phosphor: 'eyedropper',
    tabler: 'color-picker',
    materialSymbols: 'colorize',
    heroicons: 'eye-dropper',
  },
  'eraser': {
    category: 'editing',
    aliases: ['clear'],
    description: 'Eraser/clear',
    lucide: 'eraser',
    phosphor: 'eraser',
    tabler: 'eraser',
    materialSymbols: null,
    heroicons: null,
  },
  'mouse-pointer': {
    category: 'editing',
    aliases: ['cursor', 'select', 'pointer'],
    description: 'Mouse pointer/cursor',
    lucide: 'mouse-pointer',
    phosphor: 'cursor',
    tabler: 'pointer',
    materialSymbols: 'arrow_selector_tool',
    heroicons: null,
  },
  'layers': {
    category: 'organization',
    aliases: ['stack'],
    description: 'Layers/stack',
    lucide: 'layers',
    phosphor: 'stack',
    tabler: 'stack-2',
    materialSymbols: 'layers',
    heroicons: 'rectangle-stack',
  },
  'fork': {
    category: 'development',
    description: 'Subtask',
    lucide: 'git-fork',
    phosphor: 'git-fork',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'tree': {
    category: 'organization',
    aliases: ['hierarchy', 'sitemap', 'org-chart'],
    description: 'Tree/hierarchy structure',
    lucide: 'network',
    phosphor: 'tree-structure',
    tabler: 'hierarchy',
    materialSymbols: 'account_tree',
    heroicons: null,
  },
  'progress': {
    category: 'organization',
    aliases: [],
    description: 'Progress',
    lucide: 'circle-percent',
    phosphor: 'hourglass',
    tabler: 'progress',
    materialSymbols: 'progress_activity',
    heroicons: null,
  },
  'milestone': {
    category: 'organization',
    aliases: ['diamond'],
    description: 'Milestone',
    lucide: 'milestone',
    phosphor: 'flag-pennant',
    tabler: 'diamond',
    materialSymbols: 'diamond',
    heroicons: null,
  },
  'tasks': {
    category: 'organization',
    aliases: ['todos'],
    description: 'Task list/todo',
    lucide: 'list-todo',
    phosphor: 'list-checks',
    tabler: 'list-check',
    materialSymbols: 'task_alt',
    heroicons: 'clipboard-document-list',
  },
  'location': {
    category: 'location',
    aliases: ['map-pin', 'marker'],
    description: 'Location marker',
    lucide: 'map-pin',
    phosphor: 'map-pin',
    tabler: 'map-pin',
    materialSymbols: 'location_on',
    heroicons: 'map-pin',
  },
  'map': {
    category: 'location',
    aliases: [],
    description: 'Map view',
    lucide: 'map',
    phosphor: 'map-trifold',
    tabler: 'map',
    materialSymbols: 'map',
    heroicons: 'map',
  },
  'directions': {
    category: 'location',
    aliases: ['route'],
    description: 'Directions',
    lucide: 'route',
    phosphor: 'signpost',
    tabler: 'route',
    materialSymbols: 'directions',
    heroicons: null,
  },
  'compass': {
    category: 'location',
    aliases: ['navigate'],
    description: 'Compass/direction',
    lucide: 'compass',
    phosphor: 'compass',
    tabler: 'compass',
    materialSymbols: 'explore',
    heroicons: null,
  },
  'current-location': {
    category: 'location',
    aliases: ['crosshairs', 'near-me'],
    description: 'Current location',
    lucide: 'locate-fixed',
    phosphor: 'crosshair',
    tabler: 'current-location',
    materialSymbols: 'my_location',
    heroicons: null,
  },
  'measure': {
    category: 'location',
    aliases: ['ruler', 'distance'],
    description: 'Measure/distance',
    lucide: 'ruler',
    phosphor: 'ruler',
    tabler: 'ruler',
    materialSymbols: 'straighten',
    heroicons: null,
  },
  'desktop': {
    category: 'device',
    aliases: ['monitor', 'computer'],
    description: 'Desktop computer',
    lucide: 'monitor',
    phosphor: 'desktop',
    tabler: null,
    materialSymbols: 'desktop_windows',
    heroicons: 'computer-desktop',
  },
  'laptop': {
    category: 'device',
    aliases: ['notebook'],
    description: 'Laptop computer',
    lucide: 'laptop',
    phosphor: 'laptop',
    tabler: null,
    materialSymbols: 'laptop_mac',
    heroicons: null,
  },
  'mobile': {
    category: 'device',
    aliases: ['smartphone', 'phone'],
    description: 'Mobile phone',
    lucide: 'smartphone',
    phosphor: 'device-mobile',
    tabler: null,
    materialSymbols: 'mobile',
    heroicons: 'device-phone-mobile',
  },
  'tablet': {
    category: 'device',
    aliases: ['ipad'],
    description: 'Tablet device',
    lucide: 'tablet',
    phosphor: 'device-tablet-speaker',
    tabler: null,
    materialSymbols: 'tablet',
    heroicons: 'device-tablet',
  },
  'keyboard': {
    category: 'device',
    aliases: [],
    description: 'Keyboard',
    lucide: 'keyboard',
    phosphor: 'keyboard',
    tabler: null,
    materialSymbols: 'keyboard',
    heroicons: null,
  },
  'cpu': {
    category: 'device',
    aliases: ['processor', 'chip'],
    description: 'Processor/chip',
    lucide: 'cpu',
    phosphor: 'cpu',
    tabler: null,
    materialSymbols: 'memory',
    heroicons: 'cpu-chip',
  },
  'storage': {
    category: 'device',
    aliases: ['hard-drive', 'disk'],
    description: 'Storage drive',
    lucide: 'hard-drive',
    phosphor: 'hard-drives',
    tabler: null,
    materialSymbols: 'storage',
    heroicons: 'circle-stack',
  },
  'usb': {
    category: 'device',
    aliases: [],
    description: 'USB connection',
    lucide: 'usb',
    phosphor: 'usb',
    tabler: null,
    materialSymbols: 'usb',
    heroicons: null,
  },
  'cast': {
    category: 'device',
    aliases: ['chromecast', 'airplay'],
    description: 'Cast/stream',
    lucide: 'cast',
    phosphor: 'screencast',
    tabler: null,
    materialSymbols: 'cast',
    heroicons: null,
  },
  'tv': {
    category: 'device',
    aliases: ['television', 'screen'],
    description: 'Television/screen',
    lucide: 'tv',
    phosphor: 'television',
    tabler: 'device-tv',
    materialSymbols: 'tv',
    heroicons: null,
  },
  'charging': {
    category: 'device',
    aliases: ['battery-charging'],
    description: 'Battery charging',
    lucide: 'battery-charging',
    phosphor: 'battery-charging',
    tabler: 'battery-charging',
    materialSymbols: 'battery_charging_full',
    heroicons: null,
  },
  'terminal': {
    category: 'development',
    aliases: ['console', 'command-line'],
    description: 'Terminal/command line',
    lucide: 'terminal',
    phosphor: 'terminal',
    tabler: null,
    materialSymbols: 'terminal',
    heroicons: 'command-line',
  },
  'database': {
    category: 'development',
    aliases: ['db'],
    description: 'Database',
    lucide: 'database',
    phosphor: 'database',
    tabler: null,
    materialSymbols: 'database',
    heroicons: 'circle-stack',
  },
  'server': {
    category: 'development',
    aliases: [],
    description: 'Server',
    lucide: 'server',
    phosphor: 'hard-drives',
    tabler: null,
    materialSymbols: 'dns',
    heroicons: 'server',
  },
  'cloud': {
    category: 'development',
    aliases: [],
    description: 'Cloud',
    lucide: 'cloud',
    phosphor: 'cloud',
    tabler: null,
    materialSymbols: 'cloud',
    heroicons: 'cloud',
  },
  'cloud-upload': {
    category: 'development',
    aliases: ['backup'],
    description: 'Cloud upload',
    lucide: 'cloud-upload',
    phosphor: 'cloud-arrow-up',
    tabler: null,
    materialSymbols: 'cloud_upload',
    heroicons: 'cloud-arrow-up',
  },
  'cloud-download': {
    category: 'development',
    aliases: [],
    description: 'Cloud download',
    lucide: 'cloud-download',
    phosphor: 'cloud-arrow-down',
    tabler: null,
    materialSymbols: 'cloud_download',
    heroicons: 'cloud-arrow-down',
  },
  'network': {
    category: 'connectivity',
    aliases: [],
    description: 'Network',
    lucide: 'network',
    phosphor: 'graph',
    tabler: null,
    materialSymbols: 'hub',
    heroicons: null,
  },
  'wifi': {
    category: 'connectivity',
    aliases: [],
    description: 'WiFi signal',
    lucide: 'wifi',
    phosphor: 'wifi-high',
    tabler: null,
    materialSymbols: 'wifi',
    heroicons: 'wifi',
  },
  'bluetooth': {
    category: 'connectivity',
    aliases: [],
    description: 'Bluetooth',
    lucide: 'bluetooth',
    phosphor: 'bluetooth',
    tabler: null,
    materialSymbols: 'bluetooth',
    heroicons: null,
  },
  'wifi-off': {
    category: 'connectivity',
    aliases: ['wifi-disabled', 'no-wifi', 'offline'],
    description: 'WiFi disabled',
    lucide: 'wifi-off',
    phosphor: 'wifi-slash',
    tabler: 'wifi-off',
    materialSymbols: 'wifi_off',
    heroicons: null,
  },
  'bug': {
    category: 'development',
    aliases: ['issue'],
    description: 'Bug/issue',
    lucide: 'bug',
    phosphor: 'bug',
    tabler: null,
    materialSymbols: 'bug_report',
    heroicons: 'bug-ant',
  },
  'branch': {
    category: 'development',
    description: 'Git branch',
    lucide: 'git-branch',
    phosphor: 'git-branch',
    tabler: null,
    materialSymbols: 'account_tree',
    heroicons: null,
  },
  'merge': {
    category: 'development',
    description: 'Git merge',
    lucide: 'git-merge',
    phosphor: 'git-merge',
    tabler: 'git-merge',
    materialSymbols: 'merge',
    heroicons: null,
  },
  'pull-request': {
    category: 'development',
    description: 'Pull request',
    lucide: 'git-pull-request',
    phosphor: 'git-pull-request',
    tabler: 'git-pull-request',
    materialSymbols: null,
    heroicons: null,
  },
  'commit': {
    category: 'development',
    aliases: ['commit'],
    description: 'Git commit',
    lucide: 'git-commit-horizontal',
    phosphor: 'git-commit',
    tabler: 'git-commit',
    materialSymbols: 'commit',
    heroicons: null,
  },
  'sparkles': {
    category: 'ai',
    aliases: ['ai', 'magic'],
    description: 'AI/magic/new',
    lucide: 'sparkles',
    phosphor: 'sparkle',
    tabler: null,
    materialSymbols: 'auto_awesome_mosaic',
    heroicons: 'sparkles',
  },
  'wand': {
    category: 'ai',
    aliases: ['wizard'],
    description: 'Magic wand/auto-fix',
    lucide: 'wand-sparkles',
    phosphor: 'magic-wand',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'bot': {
    category: 'ai',
    aliases: ['robot', 'automation'],
    description: 'Robot/automation',
    lucide: 'bot',
    phosphor: 'robot',
    tabler: null,
    materialSymbols: 'smart_toy',
    heroicons: null,
  },
  'tip': {
    category: 'status',
    aliases: ['idea', 'lightbulb', 'hint'],
    description: 'Tip/hint',
    lucide: 'lightbulb',
    phosphor: 'lightbulb',
    tabler: 'bulb',
    materialSymbols: 'lightbulb',
    heroicons: 'light-bulb',
  },
  'zap': {
    category: 'action',
    aliases: ['lightning', 'fast', 'instant'],
    description: 'Fast/instant action',
    lucide: 'zap',
    phosphor: 'lightning',
    tabler: 'bolt',
    materialSymbols: 'bolt',
    heroicons: 'bolt',
  },
  'power': {
    category: 'system',
    aliases: ['shutdown'],
    description: 'Power on/off',
    lucide: 'power',
    phosphor: 'power',
    tabler: null,
    materialSymbols: 'power_settings_new',
    heroicons: 'power',
  },
  'battery': {
    category: 'system',
    aliases: [],
    description: 'Battery status',
    lucide: 'battery',
    phosphor: 'battery-full',
    tabler: null,
    materialSymbols: 'battery_full',
    heroicons: 'battery-100',
  },
  'tool': {
    category: 'system',
    aliases: ['wrench'],
    description: 'Tool/fix',
    lucide: 'wrench',
    phosphor: 'wrench',
    tabler: null,
    materialSymbols: 'build',
    heroicons: 'wrench',
  },
  'tools': {
    category: 'system',
    aliases: ['toolbox'],
    description: 'Tools/toolbox',
    lucide: 'toolbox',
    phosphor: 'toolbox',
    tabler: null,
    materialSymbols: 'construction',
    heroicons: 'wrench-screwdriver',
  },
  'qr-code': {
    category: 'system',
    aliases: ['qr'],
    description: 'QR code',
    lucide: 'qr-code',
    phosphor: 'qr-code',
    tabler: null,
    materialSymbols: 'qr_code_2',
    heroicons: 'qr-code',
  },
  'barcode': {
    category: 'system',
    aliases: [],
    description: 'Barcode',
    lucide: 'barcode',
    phosphor: 'barcode',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'calculator': {
    category: 'system',
    aliases: [],
    description: 'Calculator',
    lucide: 'calculator',
    phosphor: 'calculator',
    tabler: null,
    materialSymbols: 'calculate',
    heroicons: 'calculator',
  },
  'random': {
    category: 'system',
    aliases: ['dice'],
    description: 'Random/dice',
    lucide: 'dices',
    phosphor: 'dice-five',
    tabler: null,
    materialSymbols: 'casino',
    heroicons: null,
  },
  'history': {
    category: 'system',
    aliases: ['restore'],
    description: 'History/restore',
    lucide: 'history',
    phosphor: 'clock-counter-clockwise',
    tabler: null,
    materialSymbols: 'history',
    heroicons: 'clock',
  },
  'command': {
    category: 'system',
    aliases: ['cmd'],
    description: 'Command key',
    lucide: 'command',
    phosphor: 'command',
    tabler: 'command',
    materialSymbols: 'keyboard_command_key',
    heroicons: null,
  },
  'hash': {
    category: 'system',
    aliases: ['hashtag', 'number-sign', 'pound'],
    description: 'Hash/number sign',
    lucide: 'hash',
    phosphor: 'hash',
    tabler: 'hash',
    materialSymbols: 'tag',
    heroicons: null,
  },
  'rain': {
    category: 'weather',
    aliases: ['rainy'],
    description: 'Rain',
    lucide: 'cloud-rain',
    phosphor: 'cloud-rain',
    tabler: null,
    materialSymbols: 'rainy',
    heroicons: null,
  },
  'storm': {
    category: 'weather',
    aliases: ['stormy', 'lightning'],
    description: 'Storm',
    lucide: 'cloud-lightning',
    phosphor: 'cloud-lightning',
    tabler: null,
    materialSymbols: 'thunderstorm',
    heroicons: 'bolt',
  },
  'snow': {
    category: 'weather',
    aliases: ['cold', 'snowflake'],
    description: 'Snow',
    lucide: 'snowflake',
    phosphor: 'snowflake',
    tabler: null,
    materialSymbols: 'ac_unit',
    heroicons: null,
  },
  'wind': {
    category: 'weather',
    aliases: ['windy'],
    description: 'Wind',
    lucide: 'wind',
    phosphor: 'wind',
    tabler: null,
    materialSymbols: 'air',
    heroicons: null,
  },
  'temperature': {
    category: 'weather',
    aliases: ['thermometer'],
    description: 'Temperature',
    lucide: 'thermometer',
    phosphor: 'thermometer',
    tabler: null,
    materialSymbols: 'thermostat',
    heroicons: null,
  },
  'water': {
    category: 'weather',
    aliases: ['droplet', 'humidity'],
    description: 'Water/humidity',
    lucide: 'droplet',
    phosphor: 'drop',
    tabler: null,
    materialSymbols: 'water_drop',
    heroicons: null,
  },
  'fire': {
    category: 'status',
    aliases: ['hot', 'flame', 'trending'],
    description: 'Hot/trending',
    lucide: 'flame',
    phosphor: 'fire',
    tabler: 'flame',
    materialSymbols: 'local_fire_department',
    heroicons: 'fire',
  },
  'trending-up': {
    category: 'finance',
    aliases: ['increase', 'growth'],
    description: 'Trending up/growth',
    lucide: 'trending-up',
    phosphor: 'trend-up',
    tabler: 'trending-up',
    materialSymbols: 'trending_up',
    heroicons: 'arrow-trending-up',
  },
  'trending-down': {
    category: 'finance',
    aliases: ['decrease', 'decline'],
    description: 'Trending down/decline',
    lucide: 'trending-down',
    phosphor: 'trend-down',
    tabler: 'trending-down',
    materialSymbols: 'trending_down',
    heroicons: 'arrow-trending-down',
  },
  'balance': {
    category: 'finance',
    aliases: ['scale'],
    description: 'Balance/scale',
    lucide: 'scale',
    phosphor: 'scales',
    tabler: 'scale',
    materialSymbols: 'balance',
    heroicons: 'scale',
  },
  'swap': {
    category: 'finance',
    aliases: ['transfer', 'exchange'],
    description: 'Transfer/swap',
    lucide: 'arrow-left-right',
    phosphor: 'arrows-left-right',
    tabler: 'arrows-exchange',
    materialSymbols: 'swap_horiz',
    heroicons: 'arrows-right-left',
  },
  'savings': {
    category: 'finance',
    aliases: ['piggy-bank'],
    description: 'Savings',
    lucide: 'piggy-bank',
    phosphor: 'piggy-bank',
    tabler: 'pig-money',
    materialSymbols: 'savings',
    heroicons: null,
  },
  'vault': {
    category: 'finance',
    aliases: ['safe'],
    description: 'Vault/safe',
    lucide: 'vault',
    phosphor: 'vault',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'docs': {
    category: 'education',
    aliases: ['book', 'documentation'],
    description: 'Book/documentation',
    lucide: 'book-text',
    phosphor: 'book',
    tabler: 'book',
    materialSymbols: 'menu_book',
    heroicons: 'book-open',
  },
  'book-open': {
    category: 'education',
    aliases: ['reading'],
    description: 'Reading/docs',
    lucide: 'book-open',
    phosphor: 'book-open',
    tabler: 'book-2',
    materialSymbols: 'auto_stories',
    heroicons: 'book-open',
  },
  'graduation': {
    category: 'education',
    aliases: ['education', 'academic'],
    description: 'Education/degree',
    lucide: 'graduation-cap',
    phosphor: 'graduation-cap',
    tabler: 'school',
    materialSymbols: 'school',
    heroicons: 'academic-cap',
  },
  'support': {
    category: 'status',
    aliases: ['lifebuoy'],
    description: 'Support',
    lucide: 'life-buoy',
    phosphor: 'lifebuoy',
    tabler: 'lifebuoy',
    materialSymbols: 'support',
    heroicons: 'lifebuoy',
  },
  'briefcase': {
    category: 'business',
    aliases: ['work', 'job'],
    description: 'Work/business',
    lucide: 'briefcase',
    phosphor: 'briefcase',
    tabler: 'briefcase',
    materialSymbols: 'work',
    heroicons: 'briefcase',
  },
  'company': {
    category: 'business',
    aliases: ['building', 'office'],
    description: 'Company/office',
    lucide: 'building-2',
    phosphor: 'buildings',
    tabler: 'building',
    materialSymbols: 'apartment',
    heroicons: 'building-office',
  },
  'organization': {
    category: 'business',
    aliases: ['org', 'corporate', 'enterprise'],
    description: 'Organization/corporate',
    lucide: 'building',
    phosphor: 'buildings',
    tabler: 'buildings',
    materialSymbols: 'corporate_fare',
    heroicons: 'building-office-2',
  },
  'news': {
    category: 'business',
    aliases: ['newspaper', 'article'],
    description: 'News/blog',
    lucide: 'newspaper',
    phosphor: 'newspaper',
    tabler: 'news',
    materialSymbols: 'newspaper',
    heroicons: 'newspaper',
  },
  'rss': {
    category: 'business',
    aliases: ['feed'],
    description: 'RSS feed',
    lucide: 'rss',
    phosphor: 'rss',
    tabler: 'rss',
    materialSymbols: 'rss_feed',
    heroicons: 'rss',
  },
  'coffee': {
    category: 'misc',
    aliases: ['cafe', 'break'],
    description: 'Coffee/break',
    lucide: 'coffee',
    phosphor: 'coffee',
    tabler: null,
    materialSymbols: 'local_cafe',
    heroicons: null,
  },
  'infinity': {
    category: 'misc',
    aliases: ['unlimited'],
    description: 'Infinite/unlimited',
    lucide: 'infinity',
    phosphor: 'infinity',
    tabler: null,
    materialSymbols: 'all_inclusive',
    heroicons: null,
  },
  'eco': {
    category: 'misc',
    aliases: ['leaf', 'nature'],
    description: 'Eco/nature',
    lucide: 'leaf',
    phosphor: 'leaf',
    tabler: null,
    materialSymbols: 'eco',
    heroicons: null,
  },
  'hexagon': {
    category: 'misc',
    aliases: [],
    description: 'Hexagon shape',
    lucide: 'hexagon',
    phosphor: 'hexagon',
    tabler: null,
    materialSymbols: 'hexagon',
    heroicons: null,
  },
  'triangle': {
    category: 'misc',
    aliases: [],
    description: 'Triangle shape',
    lucide: 'triangle',
    phosphor: 'triangle',
    tabler: null,
    materialSymbols: 'change_history',
    heroicons: null,
  },
  'github': {
    category: 'brand',
    aliases: [],
    description: 'GitHub',
    lucide: 'github',
    phosphor: 'github-logo',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'apple': {
    category: 'brand',
    aliases: [],
    description: 'Apple',
    lucide: 'apple',
    phosphor: 'apple-logo',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'facebook': {
    category: 'brand',
    aliases: [],
    description: 'Facebook',
    lucide: 'facebook',
    phosphor: 'facebook-logo',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'twitter': {
    category: 'brand',
    aliases: [],
    description: 'Twitter/X',
    lucide: 'twitter',
    phosphor: 'x-logo',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'linkedin': {
    category: 'brand',
    aliases: [],
    description: 'LinkedIn',
    lucide: 'linkedin',
    phosphor: 'linkedin-logo',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'slack': {
    category: 'brand',
    aliases: [],
    description: 'Slack',
    lucide: 'slack',
    phosphor: 'slack-logo',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'instagram': {
    category: 'brand',
    aliases: [],
    description: 'Instagram',
    lucide: 'instagram',
    phosphor: 'instagram-logo',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
  'youtube': {
    category: 'brand',
    aliases: [],
    description: 'YouTube',
    lucide: 'youtube',
    phosphor: 'youtube-logo',
    tabler: null,
    materialSymbols: null,
    heroicons: null,
  },
};
