name: Deploy CDN

on:
  push:
    tags:
      - 'v*'  # Push events to tags matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Setup CDN structure
        run: |
          # Extract version from the tag (remove the 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Preparing CDN for version $VERSION"
          
          # Create CDN directory structure
          mkdir -p cdn
          
          # Create images directory and copy logo
          mkdir -p cdn/images
          cp $GITHUB_WORKSPACE/scripts/assets/images/logo.png cdn/images/
          
          # Get the main package name from package.json
          MAIN_PACKAGE=$(node -p "require('./package.json').name.replace('@', '').replace('/', '-')")
          echo "Main package name: $MAIN_PACKAGE"

          # Get files to publish for the core package
          core_files_array=$(node -e "
            const pkg = require('./package.json');
            if (pkg.files && pkg.files.length > 0) {
              console.log(pkg.files.join(' '));
            } else {
              // Default if no files array
              console.log('src dist types README.md');
            }
          ")
          
          # Get the core package version from package.json
          CORE_VERSION=$(node -p "require('./package.json').version")
          echo "Core package version from package.json: $CORE_VERSION"
          
          # Create core package directory using the version from package.json
          mkdir -p cdn/@semantic-ui/core/$CORE_VERSION
          
          # Copy specified directories/files, preserving the exact directory structure
          for file_entry in $core_files_array; do
            if [ -e "$file_entry" ]; then
              if [ -d "$file_entry" ]; then
                # It's a directory, preserve the directory structure exactly
                mkdir -p "cdn/@semantic-ui/core/$CORE_VERSION/$file_entry"
                # Use cp -R to copy recursively, preserving the structure
                cp -R "$file_entry" "cdn/@semantic-ui/core/$CORE_VERSION/$(dirname "$file_entry")/"
              else
                # It's a file, make sure its directory exists
                dir_path=$(dirname "$file_entry")
                mkdir -p "cdn/@semantic-ui/core/$CORE_VERSION/$dir_path"
                # Copy the file to the correct path
                cp "$file_entry" "cdn/@semantic-ui/core/$CORE_VERSION/$file_entry"
              fi
              echo "Copied $file_entry for core package"
            else
              echo "Warning: $file_entry specified in package.json for core package but not found"
            fi
          done
          
          # Copy the actual package.json file
          cp package.json cdn/@semantic-ui/core/$CORE_VERSION/package.json
          
          # Create index.js and index.html files for the core package using templates
          cp $GITHUB_WORKSPACE/scripts/assets/templates/cdn/core-index.js.template cdn/@semantic-ui/core/$CORE_VERSION/index.js
          # Use perl instead of sed for better handling of special characters
          perl -i -pe "s|CORE_ENTRY|$core_entry|g" cdn/@semantic-ui/core/$CORE_VERSION/index.js
          
          cp $GITHUB_WORKSPACE/scripts/assets/templates/cdn/core-index.html.template cdn/@semantic-ui/core/$CORE_VERSION/index.html
          perl -i -pe "s|CORE_VERSION|$CORE_VERSION|g" cdn/@semantic-ui/core/$CORE_VERSION/index.html
          perl -i -pe "s|CORE_ENTRY|$core_entry|g" cdn/@semantic-ui/core/$CORE_VERSION/index.html
          
          # Process each package in packages directory
          cd packages
          for package in */; do
            # Remove trailing slash
            package_name=${package%/}
            
            # Read version from package.json
            pkg_version=$(node -p "require('./$package_name/package.json').version")
            
            echo "Processing @semantic-ui/$package_name v$pkg_version"
            
            # Create directory in CDN structure
            mkdir -p ../cdn/@semantic-ui/$package_name/$pkg_version
            
            # Get files to publish from package.json
            files_array=$(node -e "
              const pkg = require('./$package_name/package.json');
              if (pkg.files && pkg.files.length > 0) {
                console.log(pkg.files.join(' '));
              } else {
                // Default if no files array
                console.log('src types README.md');
              }
            ")
            
            # Copy each directory/file from the files array, preserving the exact directory structure
            for file_entry in $files_array; do
              if [ -e "$package_name/$file_entry" ]; then
                if [ -d "$package_name/$file_entry" ]; then
                  # It's a directory, preserve the directory structure exactly
                  mkdir -p "../cdn/@semantic-ui/$package_name/$pkg_version/$file_entry"
                  # Use cp -R to copy recursively, preserving the structure
                  cp -R "$package_name/$file_entry" "../cdn/@semantic-ui/$package_name/$pkg_version/$(dirname "$file_entry")/"
                else
                  # It's a file, make sure its directory exists
                  dir_path=$(dirname "$file_entry")
                  mkdir -p "../cdn/@semantic-ui/$package_name/$pkg_version/$dir_path"
                  # Copy the file to the correct path
                  cp "$package_name/$file_entry" "../cdn/@semantic-ui/$package_name/$pkg_version/$file_entry"
                fi
                echo "Copied $file_entry for $package_name"
              else
                echo "Warning: $file_entry specified in package.json for $package_name but not found"
              fi
            done
            
            # Copy the actual package.json file
            cp "$package_name/package.json" "../cdn/@semantic-ui/$package_name/$pkg_version/package.json"

            # Get entrypoint from package.json for redirection
            pkg_entry=$(node -e "
              const pkg = require('./$package_name/package.json');
              // Prioritize module over main for ESM
              let entry = pkg.module || pkg.main || 'index.js';
              console.log(entry);
            ")
            
            # Create index.js and index.html files using templates
            cp $GITHUB_WORKSPACE/scripts/assets/templates/cdn/package-index.js.template "../cdn/@semantic-ui/$package_name/$pkg_version/index.js"
            # Use perl instead of sed for better handling of special characters
            perl -i -pe "s|PACKAGE_ENTRY|$pkg_entry|g" "../cdn/@semantic-ui/$package_name/$pkg_version/index.js"
            
            cp $GITHUB_WORKSPACE/scripts/assets/templates/cdn/package-index.html.template "../cdn/@semantic-ui/$package_name/$pkg_version/index.html"
            perl -i -pe "s|PACKAGE_NAME|$package_name|g" "../cdn/@semantic-ui/$package_name/$pkg_version/index.html"
            perl -i -pe "s|PACKAGE_VERSION|$pkg_version|g" "../cdn/@semantic-ui/$package_name/$pkg_version/index.html"
            perl -i -pe "s|PACKAGE_ENTRY|$pkg_entry|g" "../cdn/@semantic-ui/$package_name/$pkg_version/index.html"
          done
          cd ..
          
          # Generate importmap for this version
          echo "Generating importmap for version $VERSION"
          
          # Get core package entrypoint
          core_entry=$(node -e "
            const pkg = require('./package.json');
            // Prioritize module over main for ESM
            let entry = pkg.module || pkg.main || 'index.js';
            console.log(entry);
          ")
          
          # Collect all package information for importmap generation
          echo "Collecting package information for importmap..."
          
          # Copy and use the importmap generation script from templates
          cp $GITHUB_WORKSPACE/scripts/assets/templates/cdn/generate-importmap.js.template generate-importmap.js
          
          # Execute the importmap generation script
          echo "Executing importmap generation script..."
          VERSION=$VERSION CORE_VERSION=$CORE_VERSION CORE_ENTRY=$core_entry LIT_VERSION=$LIT_VERSION node generate-importmap.js
          rm generate-importmap.js
          
          # The importmap generation script also handles the latest importmap update logic
          
          # Create CNAME file for GitHub Pages
          echo "cdn.semantic-ui.com" > cdn/CNAME
          
          # Create package root redirect files that point to latest version folders
          echo "Creating package root redirects to latest versions..."
          
          # Create redirects for core package
          mkdir -p cdn/@semantic-ui/core
          cp $GITHUB_WORKSPACE/scripts/assets/templates/cdn/core-redirect.html.template cdn/@semantic-ui/core/index.html
          perl -i -pe "s|CORE_VERSION|$CORE_VERSION|g" cdn/@semantic-ui/core/index.html
          
          # Create redirects for each package
          cd packages
          for package in */; do
            package_name=${package%/}
            pkg_version=$(node -p "require('./$package_name/package.json').version")
            
            echo "Creating redirect for @semantic-ui/$package_name to version $pkg_version"
            
            mkdir -p "../cdn/@semantic-ui/$package_name"
            cp $GITHUB_WORKSPACE/scripts/assets/templates/cdn/package-redirect.html.template "../cdn/@semantic-ui/$package_name/index.html"
            perl -i -pe "s|PACKAGE_NAME|@semantic-ui/$package_name|g" "../cdn/@semantic-ui/$package_name/index.html"
            perl -i -pe "s|PACKAGE_VERSION|$pkg_version|g" "../cdn/@semantic-ui/$package_name/index.html"
          done
          cd ..
          
          # Copy the importmap loader to the CDN root with new name
          echo "Copying importmap loader to CDN root..."
          cp $GITHUB_WORKSPACE/scripts/assets/templates/cdn/importmap-loader.js.template cdn/importmap.js
          
          # Get Lit version from renderer package dependencies
          echo "Getting Lit version from renderer package dependencies..."
          LIT_VERSION=$(node -e "
            const pkg = require('./packages/renderer/package.json');
            const litVersion = pkg.dependencies && pkg.dependencies.lit 
              ? pkg.dependencies.lit.replace(/[^0-9.]/g, '')
              : '3.0.0';  // fallback to stable version if not specified
            console.log(litVersion);
          ")
          echo "Using Lit version: $LIT_VERSION"
          
          # Download and bundle Lit dependency with version directory structure
          echo "Downloading Lit dependency from unpkg..."
          mkdir -p cdn/lit/$LIT_VERSION
          
          # Use curl to download the Lit package with specific version
          curl -s "https://www.unpkg.com/lit@$LIT_VERSION/index.js" > cdn/lit/$LIT_VERSION/index.js
          
          # Create an index.html file in the versioned directory
          cat > cdn/lit/$LIT_VERSION/index.html << EOF
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Lit v$LIT_VERSION</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
  <style>
    :root {
      --primary: #2185d0;
      --text: #333;
      --bg: #fff;
      --code-bg: #f5f5f5;
      --border: #eaeaea;
    }
    
    @media (prefers-color-scheme: dark) {
      :root {
        --primary: #54c8ff;
        --text: #f0f0f0;
        --bg: #121212;
        --code-bg: #1e1e1e;
        --border: #333;
      }
    }
    
    body { 
      font-family: 'Lato', -apple-system, sans-serif; 
      max-width: 800px; 
      margin: 0 auto; 
      padding: 2rem; 
      color: var(--text);
      background-color: var(--bg);
      line-height: 1.6;
    }
    
    h1, h2, h3 { color: var(--primary); }
    
    pre { 
      background: var(--code-bg); 
      padding: 1rem; 
      border-radius: 5px; 
      overflow-x: auto; 
    }
    
    code { 
      background: var(--code-bg); 
      padding: 0.2rem 0.4rem; 
      border-radius: 3px;
      font-family: monospace;
    }
    
    a { color: var(--primary); }
  </style>
</head>
<body>
  <h1>Lit <span style="opacity: 0.7;">v$LIT_VERSION</span></h1>
  <p>This is the Lit library hosted for Semantic UI Next. It's a dependency for the renderer package.</p>
  
  <h2>Usage</h2>
  <p>This package is automatically included in the importmap when using Semantic UI Next from the CDN:</p>
  <pre><code>import { html } from 'lit';</code></pre>
  
  <p>Main entry point: <a href="./index.js">index.js</a></p>
  
  <h2>Documentation</h2>
  <p>For Lit documentation, visit the <a href="https://lit.dev/" target="_blank">official Lit website</a>.</p>
  
  <p><a href="/index.html">Back to CDN home</a></p>
</body>
</html>
EOF
          
          # Create a redirect at the base path
          mkdir -p cdn/lit
          echo "Creating redirect for lit to version $LIT_VERSION"
          cat > cdn/lit/index.html << EOF
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="refresh" content="0;URL=./$LIT_VERSION/">
  <title>Redirecting to Lit $LIT_VERSION</title>
</head>
<body>
  <p>Redirecting to <a href="./$LIT_VERSION/">Lit v$LIT_VERSION</a></p>
</body>
</html>
EOF
          
          # Add Lit to our importmap
          echo "Adding Lit to importmap..."
          cd cdn
          # Copy the script template for adding Lit to importmaps
          cp $GITHUB_WORKSPACE/scripts/assets/templates/cdn/add-lit-to-importmap.js.template add-lit-to-importmap.js
          # Execute the script with ESM support, passing the LIT_VERSION
          LIT_VERSION=$LIT_VERSION node --input-type=module add-lit-to-importmap.js
          # Clean up
          rm add-lit-to-importmap.js
          cd ..
          
          # Create README.md for the CDN using the gh-pages README (better formatted)
          cp $GITHUB_WORKSPACE/scripts/assets/gh-pages/README.md cdn/README.md
          # Update the version references in the README
          sed -i "s/0.9.4/$VERSION/g" cdn/README.md
          
          # Create index file for the CDN root using the gh-pages version (better formatted)
          cp $GITHUB_WORKSPACE/scripts/assets/gh-pages/index.html cdn/index.html
          # Update version references in the index.html
          sed -i "s/0.9.4/$VERSION/g" cdn/index.html
          # Fix the CDN link reference - remove the /cdn/ part since files are at root now
          sed -i 's|<li><a href="/cdn/">CDN for packages</a></li>|<li><a href="/">CDN for packages</a></li>|' cdn/index.html
          sed -i 's|<a href="/cdn/" class="btn">Explore the CDN</a>|<a href="/" class="btn">Explore the CDN</a>|' cdn/index.html
          
          # Add importmap information to the README
          sed -i '/## Usage/a\\\n### Using Importmaps\\\n\\\nFor the best developer experience, we recommend using importmaps with Semantic UI Next. There are two main approaches:\\\n\\\n#### 1. Inline Importmap (Recommended)\\\n\\\nFor the best compatibility, inline the importmap directly in your HTML:\\\n\\\n```html\\\n<script type="importmap">\\\n{\\\n  "imports": {\\\n    "@semantic-ui/core": "https://cdn.semantic-ui.com/@semantic-ui/core/0.10.0/src/semantic-ui.js",\\\n    "@semantic-ui/reactivity": "https://cdn.semantic-ui.com/@semantic-ui/reactivity/0.10.0/src/index.js",\\\n    "lit": "https://cdn.semantic-ui.com/lit/index.js"\\\n    // ... add other packages as needed\\\n  }\\\n}\\\n</script>\\\n```\\\n\\\nYou can copy the full importmap from [importmap-latest.json](https://cdn.semantic-ui.com/importmap-latest.json).\\\n\\\n#### 2. Using the Importmap Loader\\\n\\\nFor a more dynamic approach, use our importmap loader script:\\\n\\\n```html\\\n<script src="https://cdn.semantic-ui.com/importmap.js"></script>\\\n```\\\n\\\nThis automatically loads the importmap with all packages and dependencies included. You can listen for the `importmap-ready` event to know when the importmap has been loaded:\\\n\\\n```javascript\\\nwindow.addEventListener("importmap-ready", (event) => {\\\n  console.log("Importmap is ready", event.detail.importmap);\\\n  // Start importing your modules\\\n});\\\n```' cdn/README.md
      # Verify deployment structure is ready
      - name: Verify deployment structure
        run: |
          # Debug what's being deployed
          echo "Content of cdn directory (root):"
          ls -la cdn/
          
          # Verify CNAME file exists
          if [ ! -f "cdn/CNAME" ]; then
            echo "CNAME file missing, creating it"
            echo "cdn.semantic-ui.com" > cdn/CNAME
          fi
          
          if [ -d "cdn/@semantic-ui" ]; then
            echo "Content of cdn/@semantic-ui:"
            ls -la cdn/@semantic-ui/ | head -n 10
          fi

      # Upload CDN artifact for deployment
      - name: Upload CDN artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./cdn
          name: github-pages
          # Don't clean up existing files - this is critical for maintaining previous versions
          # The GitHub Pages action will merge the content with existing files
          # rather than replacing everything

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # This deployment preserves files not included in this artifact
        # which allows us to maintain all historical package versions