name: 'Coverage Report'
on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 'Install Deps'
      run: npm install
    - name: 'Install Playwright'
      run: npx playwright install --with-deps # install playwright
    - name: 'Test'
      run: npm run ci:coverage
    - name: 'Package Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v2
      with:
        name: 'Package'
        vite-config-path: './tests/config/vitest/ci-coverage.config.js'
        json-summary-path: './tests/coverage/coverage-summary.json'
        json-final-path: './tests/coverage/coverage-final.json'
        file-coverage-mode: 'changes'
