name: 'Test Suite'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write
  # Required to put a comment into the pull-request
  pull-requests: write

jobs:
  unit-test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run ci:test:unit

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Vitest Tests
          path: tests/results/test-results-unit-junit.xml
          reporter: java-junit

  browser:
    name: Run Browser E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: 'Cache Playwright Build'
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
          ~/.cache/playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Dependencies
        run: npm ci

      - name: 'Use Cached Playwright'
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: 'Install Playwright'
        run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'

      - name: Run Browser Tests
        run: npm run ci:test:browser

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Vitest Tests
          path: tests/results/test-results-browser-junit.xml
          reporter: java-junit


